### ISSUE TITLE
CloudWatch LogGroup "AWSAccelerator-FirehoseRecordsProcessor" 

### ISSUE THREAD

**Issue by awsarpit** [awslabs/landing-zone-accelerator-on-aws#106]
**Describe the bug**
We have deployed LZA solution to the Control Tower landing zone which has enabled the centralised logging in the Log Archive account. However, we identified that CloudWatch log group has a huge amount of stored bytes in the log streams generated.

On further analysing the log stream, we noticed that it is treating each enter as a new event in the log stream and thus charging for large number of PutEvent API calls

**Expected behavior**
Following are the expected outcomes:
- Capture all logging information in a single log event
- Option to disable centralisation of this logging in the configuration file

**Please complete the following information about the solution:**

- [*] Version: [1.3.1]
- [*] Region: [ap-south-1]
- [*] Was the solution modified from the version published on this repository?
- [*] If the answer to the previous question was yes, are the changes available on GitHub?
   Changes are available in "development/v.1.3.3" branch
- [*] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

<img width="1176" alt="Screenshot 2023-03-28 at 4 21 16 PM" src="https://user-images.githubusercontent.com/122075856/228214156-bc3968f1-5f29-4e6f-ab61-be53eb68d745.png">

Additional Information :
This branch has been used for this specific enterprise customer, hence we are looking for this information over this particular branch

**Comment by nagmesh** [comment]
@awsarpit 

Thank you for your question. If your compliance allows exclusions to be added to the data gathered, then please consider using [exclusions](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.CloudWatchLogsConfig.html)

In global config, specify this particular log in LogArchive to be excluded as
```yaml
...
logging:
  ...
  cloudwatchLogs:
    # enable: false
    exclusions: 
      - accounts:
          - LogArchive
        logGroupNames:
          - /aws/lambda/AWSAccelerator-FirehoseRecordsProcessor
```

Entire CloudWatch replication can also be turned off by specifying
```yaml
logging:
  ...
  cloudwatchLogs:
    enable: false
 ```

**Comment by rycerrat** [comment]
Hi awsarpit,

Thanks for reaching out to the LZA team!

It looks like you have a couple questions and expected behaviors around the centralized-logging solution in LZA. I'll try to iron those out below:

Following are the expected outcomes:

- Capture all logging information in a single log event
- Option to disable centralisation of this logging in the configuration file

As far as capturing all logging information in a single log event per lambda function -- this is not a typical logging pattern used. The LZA outputs necessary log events during the Lambda invocation, and to have this occur in a single log event would require batching these and only logging once at the end of the Lambda invocation. Batching logs is an anti-pattern because if the Lambda fails ungracefully, nothing would be logged.

As far as disabling centralization of logging in the configuration file, this is supported for each individual aspect of centralized logging:

https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.CloudWatchLogsConfig.html

For example, to disable CloudWatch Logs:

```
cloudwatchLogs:
  dynamicPartitioning: path/to/filter.json
  # default is true, if undefined this is set to true
  # if set to false, no replication is performed which is useful in test or temporary environments
  enable: true
  exclusions:
   # in these OUs do not do log replication
   - organizationalUnits:
       - Research
       - ProofOfConcept
     excludeAll: true
   # in these accounts exclude pattern testApp
   - accounts:
       - WorkloadAccount1
       - WorkloadAccount1
     logGroupNames:
       - testApp*
   # in these accounts exclude logs in specific regions
   - accounts:
       - WorkloadAccount1
       - WorkloadAccount1
     regions:
       - us-west-2
       - eu-west-1
     logGroupNames:
       - pattern1*
```

If you want to disable CloudWatch logs centralization entirely, you could set `enable:false` or you could exclude certain log groups or accounts within the `exclusions` block of the configuration.

I'll go ahead and close this issue out but if you need anything else, please feel free to reach out.

Cheers,
Ryan
