### ISSUE TITLE
Guard duty S3 protection doesnt honour manifest settings

### ISSUE THREAD

**Issue by deepend-dev** [awslabs/landing-zone-accelerator-on-aws#12]
**Describe the bug**
S3 protection gets enabled on guard duty for all account irrespective of settings are `disabled` on manifest

**To Reproduce**
1. Disable s3protection on guardduty on manifest 
![image](https://user-images.githubusercontent.com/55054090/190178496-54f3ed26-dea3-4560-8f12-2a16c4396531.png)

2. It is still comes up as enabled
![image](https://user-images.githubusercontent.com/55054090/190178773-8f2258ee-c819-403c-967a-83b458adc68a.png)

**Expected behavior**
S3 protection should be disabled 

**Please complete the following information about the solution:**

- [ x ] Version: [e.g. v1.1.0]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0021) - Video On Demand workflow with AWS Step Functions, MediaConvert, MediaPackage, S3, CloudFront and DynamoDB. Version **v5.0.0**_". If the description does not contain the version information, you can look at the mappings section of the template:

```yaml
guardduty:
    enable: true
    excludeRegions: []
    s3Protection:
      enable: false
      excludeRegions: []
    exportConfiguration:
      enable: true
      destinationType: S3
      exportFrequency: FIFTEEN_MINUTES
```

- [x] Region: ap-south-1
- [x] Was the solution modified from the version published on this repository? No
- [x] If the answer to the previous question was yes, are the changes available on GitHub? No
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [x] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
