### ISSUE TITLE
The "Condition" block was not created: iam-config.yaml

### ISSUE THREAD

**Issue by asaflevimidlink** [awslabs/landing-zone-accelerator-on-aws#205]
**Describe the bug**
I'm trying to customize iam-config.yaml with roleSets and add a bool Condition.

**To Reproduce**
While editing iam-config.yaml with various "condition" ways, the role was created successfully, but the "condition" block was not. CodeCommit Pipeline logs do not describe the cause, such as an incorrect writing format.

**Expected behavior**
IAM role with the following content:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "<role_arn>"
            },
            "Action": "sts:AssumeRole",
            "Condition": {
                "Bool": {
                    "aws:MultiFactorAuthPresent": "true"
                }
            }
        }
    ]
}
```

**Please complete the following information about the solution:**

- [ ] Version: 1.4.2
CloudFormation: SO0199

- [ ] Region: us-east-1
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? Yes
- [ ] Were there any errors in the CloudWatch Logs? No

**Additional context**
Below are described the code attempts to insert the condition option:
```
providers: []
policySets: []
roleSets:
  - deploymentTargets:
      organizationalUnits:
        - Security
        - Sandbox
    roles:
      - name: <role-name>
        instanceProfile: true
        assumedBy:
          - type: account
            principal: <role_arn>
            condition:
              Bool:
                aws:MultiFactorAuthPresent: true
        policies:
          awsManaged:
            - ReadOnlyAccess
            - CloudFrontFullAccess
```

```
providers: []
policySets: []
roleSets:
  - deploymentTargets:
      organizationalUnits:
        - Security
        - Sandbox
    roles:
      - name: <role-name>
        instanceProfile: true
        assumedBy:
          - type: account
            principal: <role_arn>
            condition:
              Bool:
                aws:MultiFactorAuthPresent: 'true'
            policies:
              awsManaged:
                - ReadOnlyAccess
                - CloudFrontFullAccess
```

```
providers: []
policySets: []
roleSets:
  - deploymentTargets:
      organizationalUnits:
        - Security
        - Sandbox
    roles:
      - name: <role-name>
        instanceProfile: true
        assumedBy:
          - type: account
            principal: <role-arn>
        condition:
          Bool:
            "aws:MultiFactorAuthPresent": true
        policies:
          awsManaged:
            - ReadOnlyAccess
            - CloudFrontFullAccess
```

**Current result**

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "<role_arn>"
            },
            "Action": "sts:AssumeRole"
        }
    ]
}
```
