### ISSUE TITLE
CloudWatch Log Groups fail to deploy to Organizational Units

### ISSUE THREAD

**Issue by erwaxler** [awslabs/landing-zone-accelerator-on-aws#206]
**Describe the bug**
When attempting to deploy CloudWatch Log Groups to an organizational unit, no CloudWatch Logs Group is created. These log groups are created successfully when `deploymentTargets` are accounts.

**To Reproduce**
Steps to reproduce the behavior.
1. Add the following block to `security-config.yaml:`
``` 
cloudWatch:
  metricSets: []
  alarmSets: []
  logGroups:
    - logGroupName: Test-log-group
      logRetentionInDays: 90
      terminationProtected: false
      encryption:
        useLzaManagedKey: true
      deploymentTargets:
        organizationalUnits:
          - Security
```
2. Run the pipeline.

**Expected behavior**
CloudWatch Logs groups are created.

**Please complete the following information about the solution:**

- [ ] Version: 1.4.2
- [ ] Region: us-east-1
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? N/A
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? Yes
- [ ] Were there any errors in the CloudWatch Logs? No
