### ISSUE TITLE
Renaming VPC in LZA config causes pipeline to fail

### ISSUE THREAD

**Issue by twdcnz** [awslabs/landing-zone-accelerator-on-aws#208]
**Describe the bug**
I have a new LZA landing zone that deployed successfully. I wanted to change the name of a VPC. I change the VPC name in the config, re-ran the AWSAccelerator-Pipeline pipeline, it failed at the Network_VPCs phase.

The logs (below) tell me the original VPC has dependencies and can't be deleted. When I went into the console I deleted it with no problems.

Logs
`
Stack ARN:
arn:aws:cloudformation:ap-southeast-2:325959740000:stack/AWSAccelerator-NetworkVpcDnsStack-325959740000-ap-southeast-2/7b72bb80-1eb3-11ee-b8fb-06a4c967e6ea

Total time: 1.06s

66/68 Currently in progress: AWSAccelerator-NetworkVpcStack-916467217000-ap-southeast-2, OriginalVpcNameVpc083C052D
AWSAccelerator-NetworkVpcStack-916467217000-ap-southeast-2 | 66/68 | 3:28:45 AM | DELETE_FAILED        | AWS::EC2::VPC                         | OriginalVpcNameVpc083C052D Resource handler returned message: "The vpc 'vpc-02764386ed26a4281' has dependencies and cannot be deleted. (Service: Ec2, Status Code: 400, Request ID: cb1ded7f-6d22-4721-a6db-f3cb74849904)" (RequestToken: 9e3b0f8d-d59d-2d5b-a877-582438a58b11, HandlerErrorCode: InvalidRequest)
66/68 Currently in progress: AWSAccelerator-NetworkVpcStack-916467217000-ap-southeast-2
AWSAccelerator-NetworkVpcStack-916467217000-ap-southeast-2 | 66/68 | 3:31:47 AM | DELETE_IN_PROGRESS   | AWS::EC2::VPC                         | OriginalVpcNameVpc083C052D 
66/68 Currently in progress: AWSAccelerator-NetworkVpcStack-916467217000-ap-southeast-2, OriginalVpcNameVpc083C052D
AWSAccelerator-NetworkVpcStack-916467217000-ap-southeast-2 | 66/68 | 3:47:50 AM | DELETE_FAILED        | AWS::EC2::VPC                         | OriginalVpcNameVpc083C052D Resource handler returned message: "The vpc 'vpc-02764386ed26a4281' has dependencies and cannot be deleted. (Service: Ec2, Status Code: 400, Request ID: b9187a72-b9c2-4837-9907-b53d5383ac33)" (RequestToken: 46ef9faf-ee7d-05e9-60aa-a1b6be0be3d4, HandlerErrorCode: InvalidRequest)
66/68 Currently in progress: AWSAccelerator-NetworkVpcStack-916467217000-ap-southeast-2
AWSAccelerator-NetworkVpcStack-916467217000-ap-southeast-2 | 66/68 | 3:50:52 AM | DELETE_IN_PROGRESS   | AWS::EC2::VPC                         | OriginalVpcNameVpc083C052D 
66/68 Currently in progress: AWSAccelerator-NetworkVpcStack-916467217000-ap-southeast-2, OriginalVpcNameVpc083C052D`

**To Reproduce**
Steps to reproduce the behavior.

Deploy this VPC as part of the AWS best practices. Change the VPC Name and run the pipeline again.

```
vpcs:
  - name: VpcName
    account: Workload1
    region: *HOME_REGION
    cidrs:
      - 10.0.0.0/16
    internetGateway: true
    enableDnsHostnames: true
    enableDnsSupport: true
    instanceTenancy: default
    routeTables:
      - name: Public-RT
        routes: []
      - name: Private-RT-A
        routes:
          - name: IgwRoute
            destination: 0.0.0.0/0
            type: internetGateway
            target: IGW
          - name: S3Gateway
            type: gatewayEndpoint
            target: s3
          - name: DynamoDBGateway
            type: gatewayEndpoint
            target: dynamodb
      - name: Private-RT-B
        routes:
          - name: IgwRoute
            destination: 0.0.0.0/0
            type: internetGateway
            target: IGW
          - name: S3Gateway
            type: gatewayEndpoint
            target: s3
          - name: DynamoDBGateway
            type: gatewayEndpoint
            target: dynamodb
      - name: Private-RT-C
        routes:
          - name: IgwRoute
            destination: 0.0.0.0/0
            type: internetGateway
            target: IGW
          - name: S3Gateway
            type: gatewayEndpoint
            target: s3
          - name: DynamoDBGateway
            type: gatewayEndpoint
            target: dynamodb
    subnets:
      - name: Public-Subnet-A
        availabilityZone: a
        routeTable: Public-RT
        ipv4CidrBlock: 10.0.0.0/24
      - name: Public-Subnet-B
        availabilityZone: b
        routeTable: Public-RT
        ipv4CidrBlock: 10.0.1.0/24
      - name: Public-Subnet-C
        availabilityZone: c
        routeTable: Public-RT
        ipv4CidrBlock: 10.0.2.0/24
      - name: Private-Subnet-A
        availabilityZone: a
        routeTable: Private-RT-A
        ipv4CidrBlock: 10.0.3.0/24
      - name: Private-Subnet-B
        availabilityZone: b
        routeTable: Private-RT-B
        ipv4CidrBlock: 10.0.4.0/24
      - name: Private-Subnet-C
        availabilityZone: c
        routeTable: Private-RT-C
        ipv4CidrBlock: 10.0.5.0/24
    transitGatewayAttachments: []
    gatewayEndpoints:
      defaultPolicy: Default
      endpoints:
        - service: s3
        - service: dynamodb
    interfaceEndpoints:
      central: false
      defaultPolicy: Default
      subnets:
        - Private-Subnet-A
        - Private-Subnet-B
        - Private-Subnet-C
      endpoints: []
```

**Expected behavior**

**Please complete the following information about the solution:**

- [x] Version: 1.4.2

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0021) - Video On Demand workflow with AWS Step Functions, MediaConvert, MediaPackage, S3, CloudFront and DynamoDB. Version **v5.0.0**_". If the description does not contain the version information, you can look at the mappings section of the template:

```yaml
Mappings:
  SourceCode:
    General:
      S3Bucket: "solutions"
      KeyPrefix: "video-on-demand-on-aws/v5.0.0"
```

- [x] Region: ap-southeast-2
- [x] Was the solution modified from the version published on this repository? No
- [x] If the answer to the previous question was yes, are the changes available on GitHub? N/A
- [X] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? N/A
- [X] Were there any errors in the CloudWatch Logs? No

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
