### ISSUE TITLE
identityCenter: Error Assigning IAM Permissions to Management Account/Root OU

### ISSUE THREAD

**Issue by priolix** [awslabs/landing-zone-accelerator-on-aws#215]
**Describe the bug**

I encountered an error while testing the AWS IAM Identity Center features of the "landing-zone-accelerator-on-aws" solution. When attempting to assign permissions to the management account :
```yaml
identityCenter:
 name: idc-lza-glob-01
 delegatedAdminAccount: # Audit, Management or commented does not make it work
 identityCenterPermissionSets:
   - name: ips-lza-it-owners
     policies:
       awsManaged:
         - arn:aws:iam::aws:policy/AdministratorAccess
     sessionDuration: 60
   - name: ips-lza-billing-administrators
     policies:
       awsManaged:
         - arn:aws:iam::aws:policy/job-function/Billing
     sessionDuration: 60
 identityCenterAssignments:
   - name: ica-lza-it-owners
     permissionSetName: ips-lza-it-owners
     principalId: "ec7d0558-60d1-709c-b30d-81f909a1dfe7" # grp-lza-it-owners
     principalType: GROUP
     deploymentTargets:
       organizationalUnits:
         - Infrastructure
         - Testing
         - Root # Doesnt work
   - name: ica-lza-billing-administrators
     permissionSetName: ips-lza-billing-administrators
     principalId: "accd0558-6011-70e0-6533-03bfe0ffd108" #grp-lza-billing-administrators
     principalType: GROUP
     deploymentTargets:
       accounts:
         - Management # Doesnt work
```

The following error occurs:
```bach
Resource handler returned message: "User: arn:aws:sts::987654321012:assumed-role/cdk-accel-cfn-exec-role-987654321012-ca-central-1/AWSCloudFormation is not authorized to perform: sso:CreateAccountAssignment on resource: arn:aws:sso:::account/246801357913 (Service: SsoAdmin, Status Code: 400, Request ID: be277ab6-0b58-4582-a65b-707379a670f3)" (RequestToken: dc067927-de87-8ce6-80b5-5d2ac0e49267, HandlerErrorCode: GeneralServiceException)
```
Where **987654321012** is my Audit account
And **246801357913** my management account
(Anonymized numbers)

The bug or limitation prevents the successful assignment of permissions to the management account.

**To Reproduce**
1. Deploy the "landing-zone-accelerator-on-aws" solution.
2. Configure the `iam-config.yaml` file with the provided example from the official documentation.
3. Attempt to assign permissions to the management account.
4. Encounter the mentioned error.

**Expected behavior**
I expected the permissions to be successfully assigned to the management account without any errors.

**Please complete the following information about the solution:**

- [ ] Version: **1.4.1**
- [ ] Region: **ca-central-1**
- [ ] Was the solution modified from the version published on this repository? **No**
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? **yes**
- [ ] Were there any errors in the CloudWatch Logs? **The errors are explicit in the CDK output**

**Additional context**
Add any other context about the problem here. The error occurs when trying to assign permissions to the management account. Changing the delegated admin account from "Audit" to "Management" results in the following error:

```bach
(IdentityCenterAdminidentityCenterAdminEB714AB1) Received response status [FAILED] from custom resource. Message returned: You cannot register the master account/yourself as a delegated administrator for your organization.
```

I attempted to create a new resource with a different name in order to force the use of the correct delegated account. However, I encountered the following error:

```bach
Resource handler returned message: "User: arn:aws:sts::987654321012:assumed-role/cdk-accel-cfn-exec-role-987654321012-ca-central-1/AWSCloudFormation is not authorized to perform: sso:CreateAccountAssignment on resource: arn:aws:sso:::account/246801357913 (Service: SsoAdmin, Status Code: 400, Request ID: be277ab6-0b58-4582-a65b-707379a670f3)" (RequestToken: dc067927-de87-8ce6-80b5-5d2ac0e49267, HandlerErrorCode: GeneralServiceException)
```

We tried to deregister the delegated administrator account and run the LZA pipeline with delegatedAdminAccount commented out.

```yaml
identityCenter:
 name: idc-lza-glob-01
 # delegatedAdminAccount:
 identityCenterPermissionSets:
```

It appear that the solution will automatically assign a delegatedAdminAccount to Audit.

We believe there is a bug or limitation in the AWS IAM Identity Center Assignments feature of the "landing-zone-accelerator-on-aws" solution, preventing the successful assignment of permissions to the management account and by extention to the Root OU. 
Is there a way to properly manage IAM Identity Center Assigment on Mangement account through LZA ?
