### ISSUE TITLE
Budget Reports unable to generate a notification alert.

### ISSUE THREAD

**Issue by balapraneethreddy98** [awslabs/landing-zone-accelerator-on-aws#218]
**Describe the bug**
When configuring BudgetReport, the notification option provides us to generate alerts and forward that to the corresponding configured method, for example (email), but when configured and executed via the code pipeline, the budgets are created but no sign of the alerts associated with the budgets.

**To Reproduce**
1. Deploy the Landing zone accelerator using the following guide and IaaC templates
Link: https://aws.amazon.com/solutions/implementations/landing-zone-accelerator-on-aws/
2. Navigate to CodeCommit Service and aws-accelator-config repo.
3. Edit global-config.yml file as mentioned below.

**Expected behavior**
Create an alert notification when deployed.

Version: [v1.4.2]

```yaml
reports:
  budgets:
  - name: sandbox_root-budget-name
    timeUnit: MONTHLY
    type: COST
    amount: 500
    includeUpfront: true
    includeTax: true
    includeSupport: true
    includeSubscription: true
    includeRecurring: true
    includeOtherSubscription: true
    includeDiscount: true
    includeCredit: false
    includeRefund: false
    useBlended: false
    useAmortized: false
    unit: USD
    notification:
    - type: FORECASTED
      thresholdType: PERCENTAGE
      threshold: 100
      comparisonOperator: GREATER_THAN
      subscriptionType: EMAIL
      address: example-email@gmail.com
    deploymentTargets:
      organizationalUnits:
        - Root
```

- [x] Region: [e.g. us-east-2]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
-> Screenshot of no alerts being created after deployment of the global-config.yml code.

![MicrosoftTeams-image (2)](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/135895008/9d16d137-7fc8-45ae-896e-74c792605e50)
