### ISSUE TITLE
Define SSO to AAD in config

### ISSUE THREAD

**Issue by xxjt123xx** [awslabs/landing-zone-accelerator-on-aws#245]
**Is your feature request related to a problem? Please describe.**
I need to be able to setup SSO to AAD mapped to AAD groups

**Describe the feature you'd like**
I need to be able to setup SSO to AAD mapped to AAD groups

**Additional context**
I need to be able to setup SSO to AAD mapped to AAD groups

**Comment by fdjahnke** [comment]
Hello @xxjt123xx, thank you for filing a feature request with the Landing Zone Accelerator team!

Good news: assigning AWS access to your Azure AD (now Entra ID) groups is already supported today. In `iam-config.yaml`, the `identityCenter` block lets you define permission sets and `identityCenterAssignments` where you map a permission set to `principals` of `type: GROUP`, using the group name as it appears in your identity source (Azure AD / Active Directory):

```yaml
identityCenter:
  name: identityCenter1
  identityCenterAssignments:
    - name: Assignment1
      permissionSetName: PermissionSet1
      principals:
        - type: GROUP
          name: <your-AAD-group-name>
      deploymentTargets:
        organizationalUnits:
          - Security
```

One thing to note: the actual SSO federation between Azure AD and IAM Identity Center (the SAML/SCIM connection) is a one-time setup performed in the IAM Identity Center console and on the Azure AD side, and is not exposed by AWS as an infrastructure-as-code/API operation, so LZA cannot define that connection itself. Once federation and SCIM provisioning are in place, LZA manages the permission sets and group assignments for you.

We may revisit this in a future release if AWS exposes the federation setup to infrastructure-as-code. Closing this issue for now, please feel free to follow up if you have questions just make sure to ping me so that I'll see it.
