### ISSUE TITLE
AssumeBy for roleSet should support user as principal. 

### ISSUE THREAD

**Issue by bakharzy** [awslabs/landing-zone-accelerator-on-aws#257]
**Is your feature request related to a problem? Please describe.**

We are trying to create a Break the Glass role in an OU named Sandbox. We also want to specify which user can assume this role. We tried adding a roleSet in iam-config.yaml as the following: (excuse the indentation issues)

```
roleSets:
- deploymentTargets:
 organizationalUnits:
 - Sandbox 
roles:
 - name:break-glass-role 
assumedBy:
 - principal:arn:aws:iam::111111111111:user/some-user
    type:account 
policies:
 awsManaged:
 - AdministratorAccess
```
However, this does not work currently. It seems assumedBy only accepts three types: service, account or provider

https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/11a38bd38aa931a75121a81f50e222ccec6f4202/source/packages/%40aws-accelerator/config/lib/iam-config.ts#L1032C1-L1043C2

https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.AssumedByConfig.html#type

The error we receive in pipeline/Bootstrap stage:
2023-09-07 12:47:41.842 | info | AWSAccelerator-OperationsStack-2222222222-region-x | Role - assumed by type(account) principal(arn:aws:iam::111111111111:user/some-user) 
2023-09-07 12:47:41.842 | error | accounts-config | Account name not found for arn:aws:iam::111111111111:user/some-user Validate that the emails in the parameter ManagementAccountEmail of the AWSAccelerator-InstallerStack and account configs (accounts-config.yaml) match the correct account emails shown in AWS Organizations. 
2023-09-07 12:47:41.843 | error | app | configuration validation failed.

**Describe the feature you'd like**

We would like to be able to specify the exact user that can assume the role. Currently, only three types are available and user is not one of them.
