### ISSUE TITLE
AssumeBy for roleSet should support any supported AWS principal

### ISSUE THREAD

**Issue by lucashalbert** [awslabs/landing-zone-accelerator-on-aws#258]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]'

When creating any role via the [IamConfig](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.IamConfig.html) / [RoleSetConfig](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.RoleSetConfig.html) / [RoleConfig](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.RoleConfig.html) / [AssumedByConfig](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.AssumedByConfig.html), the `AssumedByConfig` Class should accommodate all AWS supported configuration `principal` types and conditions.

Currently the only types supported by the [`AssumedByConfig`](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.AssumedByConfig.html#type) class is `service`, `account`, or `provider`.

Here is an example
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "arn:aws:iam::123456789012:user/userA",
                    "arn:aws:iam::123456789012:role/roleA"
                ],
                "Federated": "arn:aws:iam::123456789012:saml-provider/providerA"
            },
            "Action": "sts:AssumeRole",
            "Condition": {
                "StringEquals": {
                    "sts:ExternalId": "abc123",
                    "sts:RoleSessionName": "sessionabc123"
                }
            }
        }
    ]
}
```

**Describe the feature you'd like**
I would like to be able to deploy roles via LZA using `IamConfig` with complex Assume/Trust relationship policies. I anticipate that the IamConfig would look soemthing like the following.

```yaml
---
roleSets:
  - deploymentTargets:
      organizationalUnits:
        - Root
    roles:
      - name: Example-Role
        assumedBy:
          - type: AWS
            principal:
              - arn:aws:iam::123456789012:user/userA
              - arn:aws:iam::123456789012:role/roleA
          - condition:
              - StringEquals:
                  - sts:ExternalId:
                      - abc123
                  - sts:RoleSessionName:
                      - sessionabc123
        policies:
          awsManaged:
            - AmazonSSMManagedInstanceCore
            - AmazonSSMDirectoryServiceAccess
            - CloudWatchAgentServerPolicy
        boundaryPolicy: Default-Boundary-Policy
...
```

**Additional context**
This issue semi-relates to #257
