### ISSUE TITLE
Wrong policy role document for remediation lambda functions

### ISSUE THREAD

**Issue by FlemmingBehrend** [awslabs/landing-zone-accelerator-on-aws#262]
**Describe the bug**
In the `security-config.yaml` file when creating a new custom config rule the remediation section contains a bug.

```yaml
awsConfig:
  ...
  ruleSets:
    - deploymentTargets:
        organizationalUnits:
          - Root
      rules:
        - name: my-remediation-rule
           type: Custom
           ...
          remediation:
            # This role is used to create the role for the lambda function. It should only be used for the SSM document assume role.
            rolePolicyFile: custom-config-rules/xxx-role.json
            automatic: true
            targetId: My-SSM-Document
            targetAccountName: Audit
            retryAttemptSeconds: 60
            maximumAutomaticAttempts: 5
            parameters:
              - name: ResourceId
                value: RESOURCE_ID
                type: String
              - name: RemediationFunctionName
                value: ${ACCEL_LOOKUP::RemediationFunctionName}
                type: String
            targetDocumentLambda:
              handler: remediation.handler
              # This role is never used in the code
              rolePolicyFile: custom-config-rules/yyy-role.json
              runtime: nodejs18.x
              sourceFilePath: custom-config-rules/my-remediation-src.zip
              timeout: 300
```

The error is here in the code: 
https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/source/packages/%40aws-accelerator/accelerator/lib/stacks/security-resources-stack.ts#L775-L797

```typescript
    const remediationRole = this.createRemediationRole(
      rule.name,
      path.join(this.props.configDirPath, rule.remediation.rolePolicyFile), // here we use the top level rolePolicyFile
      `arn:${cdk.Stack.of(this).partition}:ssm:${cdk.Stack.of(this).region}:${
        rule.remediation.targetAccountName
          ? this.props.accountsConfig.getAccountId(rule.remediation.targetAccountName)
          : this.props.accountsConfig.getAuditAccountId()
      }:document/${rule.remediation.targetId}`,
      !!rule.remediation.targetDocumentLambda,
    );

    // If remediation document use action as aws:invokeLambdaFunction, create the lambda function
    let remediationLambdaFunction: cdk.aws_lambda.Function | undefined;
    if (rule.remediation.targetDocumentLambda) {
      remediationLambdaFunction = new cdk.aws_lambda.Function(this, pascalCase(rule.name) + '-RemediationFunction', {
        role: remediationRole, // here we set the new role created based on the top level file
        runtime: new cdk.aws_lambda.Runtime(rule.remediation.targetDocumentLambda.runtime),
        handler: rule.remediation.targetDocumentLambda.handler,
        code: cdk.aws_lambda.Code.fromAsset(
          path.join(this.props.configDirPath, rule.remediation.targetDocumentLambda.sourceFilePath),
        ),
        description: `Function used in ${rule.remediation.targetId} SSM document for "${rule.name}" custom config rule to remediation`,
      });
```

Also the documentation for using a remediation lambda function could be improved.

**To Reproduce**
1. Create a new custom rule with a remediation and create two different policy `xxx-role.json` and `yyy-role.json`.
2. Run the pipeline
3. Go to the remediation lambda function and see that the role `xxx-role.json` and not `yyy-role.json` is used

**Expected behavior**

The role from the `targetDocumentLambda` section should have been used as the lambda execution role.

**Please complete the following information about the solution:**

- [ v1.4.3 ] Version: [e.g. v1.1.0]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0021) - Video On Demand workflow with AWS Step Functions, MediaConvert, MediaPackage, S3, CloudFront and DynamoDB. Version **v5.0.0**_". If the description does not contain the version information, you can look at the mappings section of the template:

```yaml
Mappings:
  SourceCode:
    General:
      S3Bucket: "solutions"
      KeyPrefix: "video-on-demand-on-aws/v5.0.0"
```

- [ eu-west-1 ] Region: [e.g. us-east-1]
- [ no ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ yes ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ no ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
