### ISSUE TITLE
Control Tower and LZA logging duplication

### ISSUE THREAD

**Issue by priolix** [awslabs/landing-zone-accelerator-on-aws#264]
**Describe the bug**
CloudTrail logs seem to be replicated when the solution is deployed alongside AWS Control Tower.

**To Reproduce**
1. Deploy the solution alongside AWS Control Tower.
![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/22840429/e82c32d0-7aed-4596-a398-0a135f2ac819)
2. Observe the replication of CloudTrail logs.

**Expected behavior**
CloudTrail logs should not be replicated when the solution is deployed alongside AWS Control Tower.

**Please complete the following information about the solution:**

- Version: **v1.4.3**
- Region: **ca-central-1**
- Was the solution modified from the version published on this repository? **No**
- Were there any errors in the CloudWatch Logs? **No**

**Additional context**
CloudTrail log duplication appears to be related to the deployment of the solution alongside AWS Control Tower. AWS Config logs indicate that only logs from the master account are stored by the accelerator.
**global-config.yaml** :
```yaml
homeRegion: &HOME_REGION ca-central-1
enabledRegions:
  - *HOME_REGION
managementAccountAccessRole: AWSControlTowerExecution
cloudwatchLogRetentionInDays: 3653
terminationProtection: true
centralizeCdkBuckets:
  enable: true
controlTower:
  enable: true
logging:
  account: LogArchive
  cloudtrail:
    enable: false
    organizationTrail: false
    organizationTrailSettings:
      multiRegionTrail: true
      globalServiceEvents: true
      managementEvents: true
      s3DataEvents: true
      lambdaDataEvents: true
      sendToCloudWatchLogs: true
      apiErrorRateInsight: false
      apiCallRateInsight: false
    accountTrails:
      - name: AccountTrail
        regions:
          - *HOME_REGION
        deploymentTargets:
          accounts: []
          organizationalUnits:
            - Root
        settings:
          multiRegionTrail: true
          globalServiceEvents: true
          managementEvents: true
          s3DataEvents: true
          lambdaDataEvents: true
          sendToCloudWatchLogs: true
          apiErrorRateInsight: false
          apiCallRateInsight: false
  sessionManager:
    sendToCloudWatchLogs: false
    sendToS3: true
  cloudwatchLogs:
    dynamicPartitioning: dynamic-partitioning/log-filters.json
reports:
  costAndUsageReport:
    compression: Parquet
    format: Parquet
    reportName: accelerator-cur
    s3Prefix: cur
    timeUnit: DAILY
    refreshClosedReports: true
    reportVersioning: CREATE_NEW_REPORT
```

**Landing Zone Accelerator**
Landing Zone Accelerator deploys its own logging configuration, including security-config.yaml and various log types such as AWSLogs, Cloudtrail-AccountTrail, CloudWatchLogs, cur, session, and vpc-flow-logs. It also handles S3 access logs for the accelerator.
<pre>
├── AWSLogs -> Config
├── Cloudtrail-AccountTrail
├── AWSLogs -> <b>Contain Cloud Trail logs for each account Possible duplication</b>
|   ├── 503892147625
|   └── 726149830512
├──CloudWatchLogs
|   ├── 2022
|   ├── 2023
|   ├── processing-failedprocessing-failed
|   └── security-hub
├──cur
├──session -> SSM console history
└──vpc-flow-logs
</pre>

**Control Tower**
Control Tower also manages logging, including AWS ControlTowerCloudTrailRole and aws-controltower-logs-918467205374-ca-central-1 log group. This log group contains logs related to Control Tower and AWSConfig logs for each account.
<pre>
└── aws-controltower-logs-918467205374-ca-central-1
    └── o-rg4kpt73sw
        └── AWSLogs
                ├── 503892147625 -> contain each day the config snapshot
                ├── 726149830512
                └── o-rg4kpt73sw -> Contain per account CloudTrail-Digest and CloudTrail
                    ├── 503892147625 -> <b>Contain Cloud Trail logs for each account Possible duplication</b>
                    └── 726149830512
</pre>

**To resume**
We are facing 2 problems : 
1. We have a log duplication one by control tower the other one by the LZA solution.
2. LZA AWSLogs contains only the ConfigSnapshot for the master account (The Control Tower one for all accounts)
