### ISSUE TITLE
Synth and Validation steps do not pick up misconfigured VPC Interface Endpoints

### ISSUE THREAD

**Issue by hplm** [awslabs/landing-zone-accelerator-on-aws#271]
**Describe the bug**
When creating VPC Interface Endpoints, misconfigured entries do not get validated or checked, resulting in successful pipeline releases, but with inexistent endpoints. Troubleshooting is very difficult and misleading. 

Example of misconfigured endpoints on `network-config.yaml`:

```yaml
    interfaceEndpointConfig:
      defaultPolicy: Default
      endpoints:
        - ec2
        - ec2messages
        - ssm
        - ssmmessages
        - rds
        - lambda
        - execute-api
        - sns
        - sqs
        - states
        - sync-states
``` 
Correctly configured endpoints:
```yaml
    interfaceEndpoints:
      defaultPolicy: Default
      endpoints:
        - service: ec2
        - service: ec2messages
        - service: ssm
        - service: ssmmessages
        - service: rds
        - service: lambda
        - service: execute-api
        - service: sns
        - service: sqs
        - service: states
        - service: sync-states
```

**To Reproduce**
To reproduce the error, simply deploy the `interfaceEndpointConfig` object as above in any VPC or VPC template. 

**Expected behavior**
LZA pipeline synth and validation steps should pick up the misconfiguration and alert the users for effective fix. 

**Please complete the following information about the solution:**

- [x] Version: 1.4.3
- [x] Region: ap-southeast-2
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs? 
***Unclear on which Log Group to search for errors, since pipeline didn't present any exceptions***

**Additional context**
Happy to assist on the resolution. Thanks!
