### ISSUE TITLE
Found Account not in configuration

### ISSUE THREAD

**Issue by joeshawfieldatayo** [awslabs/landing-zone-accelerator-on-aws#28]
**Describe the bug**
Prepare phase fails for existing accounts in existing Landing Zone when added to config.

498 | AWSAccelerator-PrepareStack-036499323218-us-east-1 \| 4:44:51 PM \| CREATE_FAILED        \| Custom::ValidateEnvironmentConfig                  \| ValidateEnvironmentConfig/Resource/Default (ValidateEnvironmentConfigB40B464F) Received response status [FAILED] from custom resource. Message returned: Error: Found account with id xxxxx in OU Infrastructure that is not in the configuration.,Found account with id xxxxxx in OU Infrastructure that is not in the configuration.
Pipeline: AWSAccelerator-Pipeline
Phase: Prepare

**To Reproduce**
Existing landing Zone created in Control Tower. Installed Landing zone accelerator 1.2.2
Modified Config to add existing OU and Accounts (Matching Name and Email)

```yaml
  enable: true
  organizationalUnits:
    - name: core
    - name: Security
    - name: Development
    - name: Infrastructure
    - name: Network
    - name: Production
    - name: Sandbox
  serviceControlPolicies: []
  taggingPolicies: []
  backupPolicies: []
```

accounts-config.yaml

```yaml
  workloadAccounts:
    - name: caplz-security-services
      description: >-
        The security account
      email: xxxxx
      organizationalUnit: Infrastructure
    - name: caplz-shared-services
      description: >-
        The shared services account
      email: xxxxxx
      organizationalUnit: Infrastructure
```

Both Accounts are indeed in this OU and are registered.

ERROR:

Failed resources:
--
498 | AWSAccelerator-PrepareStack-036499323218-us-east-1 \| 4:44:51 PM \| CREATE_FAILED        \| Custom::ValidateEnvironmentConfig                  \| ValidateEnvironmentConfig/Resource/Default (ValidateEnvironmentConfigB40B464F) Received response status [FAILED] from custom resource. Message returned: Error: Found account with id xxxxx3306 in OU Infrastructure that is not in the configuration.,Found account with id xxxxxx344 in OU Infrastructure that is not in the configuration.

**Expected behavior**
Recognize Account Config as Matching AWS Actual

**Please complete the following information about the solution:**

- [release/v1.2.2] Version: [e.g. v1.1.0]

- [ us-east-1] Region: [e.g. us-east-1]
- [no] Was the solution modified from the version published on this repository?
- [no] If the answer to the previous question was yes, are the changes available on GitHub?
- [yes] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [yes ] Were there any errors in the CloudWatch Logs?

**Screenshots**

![image](https://user-images.githubusercontent.com/96444717/207395463-7192a750-da19-4674-b324-b1164e93a5e3.png)

**Additional context**
