### ISSUE TITLE
Identity Center Permission Set Assignments do not work with multiple deployment targets

### ISSUE THREAD

**Issue by schnipseljagd** [awslabs/landing-zone-accelerator-on-aws#287]
**Describe the bug**
When assigning multiple deployment targets to a permission set assignment the deploy pipeline fails in `Deploy/Operations` step with the following error:
```
$ /codebuild/output/src1810/src/s3/00/source/packages/@aws-accelerator/accelerator/node_modules/.bin/ts-node --transpile-only cdk.ts synth --stage operations --require-approval never --config-dir /codebuild/output/src1810/src/s3/01 --partition aws
--
113 | 2023-10-18 12:42:58.805 \| error \| app \| There is already a Construct with name 'AcceleratorGetLambdaKey' in OperationsStack [AWSAccelerator-OperationsStack-<REDACTED>-eu-central-1]
114 | 2023-10-18 12:42:58.805 \| error \| toolkit \| Error: There is already a Construct with name 'AcceleratorGetLambdaKey' in OperationsStack [AWSAccelerator-OperationsStack-<REDACTED>-eu-central-1]
115 | 2023-10-18 12:42:58.935 \| error \| accelerator \| Runtime Error
116 | /codebuild/output/src1810/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/accelerator.ts:57
117 | throw new Error('Synthesis failed');
118 | ^
119 |  
120 | Error: Synthesis failed
121 | at process.<anonymous> (/codebuild/output/src1810/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/accelerator.ts:41:9)
122 | at process.emit (node:events:525:35)
123 | at process.emit (node:domain:489:12)
124 | at process.emit.sharedData.processEmitHook.installedValue [as emit] (/codebuild/output/src1810/src/s3/00/source/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)
125 | at process._fatalException (node:internal/process/execution:149:25)
126 | 2023-10-18 12:42:59.043 \| error \| toolkit \| Subprocess exited with error 7
127 | 2023-10-18 12:42:59.043 \| error \| toolkit \| Options were: {"command":"synth","enableSingleAccountMode":false,"partition":"aws","stackPrefix":"AWSAccelerator","stage":"operations","configDirPath":"/codebuild/output/src1810/src/s3/01","requireApproval":"never","cdkOptions":{"centralizeBuckets":true,"useManagementAccessRole":true},"useExistingRoles":false}
128 | Synthesis of stacks failed
129 | error Command failed with exit code 1.
130 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**To Reproduce**
Use the following `iam-config.yaml` and uncomment the last line:
```
providers: []
policySets: []
groupSets: []
userSets: []
roleSets: []
identityCenter:
  name: IdentityCenter
  delegatedAdminAccount: Audit
  identityCenterPermissionSets:
    - name: AdministratorAccess
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/AdministratorAccess
      sessionDuration: 600
  identityCenterAssignments:
    - name: PlatformEngineeringAdminAssignment
      permissionSetName: AdministratorAccess
      principals:
        - type: GROUP
          name: platform-engineering
      deploymentTargets:
        organizationalUnits:
          - Workloads/Production
          # - Workloads/Staging currently bugged, cannot have more than 1

```

**Expected behavior**
Like for other resources I would expect that I can add multiple accounts or organizationalUnits as deployment targets.

**Please complete the following information about the solution:**

- [x] Version: [e.g. v1.5.0]
- [x] Region: eu-central-1
- [x] Was the solution modified from the version published on this repository? No
- [x] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? yes
- [x] Were there any errors in the CloudWatch Logs? See aboce

**Screenshots**
See quote above.

**Additional context**
We've tried using `organizationalUnits` as well as `accounts` and the error occured for both.

This might be a potential fix:

```
diff --git a/source/packages/@aws-accelerator/accelerator/lib/stacks/operations-stack.ts b/source/packages/@aws-accelerator/accelerator/lib/stacks/operations-stack.ts
index 2d81d208..14d70f13 100644
--- a/source/packages/@aws-accelerator/accelerator/lib/stacks/operations-stack.ts
+++ b/source/packages/@aws-accelerator/accelerator/lib/stacks/operations-stack.ts
@@ -89,6 +89,7 @@ export class OperationsStack extends AcceleratorStack {
    * KMS Key used to encrypt CloudWatch logs
    */
   private cloudwatchKey: cdk.aws_kms.Key;
+  private acceleraterLambdaKey: any;
 
   /**
    * Constructor for OperationsStack
@@ -1021,6 +1022,8 @@ export class OperationsStack extends AcceleratorStack {
       this.acceleratorResourceNames.parameters.identityStoreId,
     );
 
+    this.acceleraterLambdaKey = this.acceleraterLambdaKey ?? this.getAcceleratorKey(AcceleratorKeyType.LAMBDA_KEY)
+
     const usersGroupsMetadata = new UsersGroupsMetadata(
       this,
       pascalCase(`UsersGroupsMetadata-${assignment.name}-${targetAccountId}`),
@@ -1028,7 +1031,7 @@ export class OperationsStack extends AcceleratorStack {
         identityStoreId: identityStoreId,
         principals: assignment.principals,
         resourceUniqueIdentifier: `${targetAccountId}-${assignment.name}`,
-        customResourceLambdaEnvironmentEncryptionKmsKey: this.getAcceleratorKey(AcceleratorKeyType.LAMBDA_KEY),
+        customResourceLambdaEnvironmentEncryptionKmsKey: this.acceleraterLambdaKey,
         customResourceLambdaCloudWatchLogKmsKey: this.cloudwatchKey,
         customResourceLambdaLogRetentionInDays: this.props.globalConfig.cloudwatchLogRetentionInDays,
       },
```
