### ISSUE TITLE
Update to v1.5.0 from 1.4.3: 

### ISSUE THREAD

**Issue by snemir2** [awslabs/landing-zone-accelerator-on-aws#288]
**Describe the bug**
After upgrading from v1.4.3 to the currently latest v1.5.0, the AWSAccelerator-Pipeline Build step fails. 

Error:
```


2023-10-18 19:09:01.074 \| info \| network-config-validator \| network-config.yaml file validation started
--
909 | 2023-10-18 19:09:01.087 \| info \| organization-config-validator \| organization-config.yaml file validation started
910 | 2023-10-18 19:09:01.088 \| info \| security-config-validator \| security-config.yaml file validation started
911 | 2023-10-18 19:09:01.096 \| warn \| config-validator \| Config file validation failed !!!
912 | 2023-10-18 19:09:01.110 \| warn \| config-validator \| iam-config.yaml has 1 issues:
913 | Deployment target account(s) for the following role(s): EC2-Default-SSM-AD-Role reference policies that are not available in the target accounts.
914 | error Command failed with exit code 1.
915 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
916 |  
917 | [Container] 2023/10/18 19:09:01 Command did not exit successfully yarn validate-config $CODEBUILD_SRC_DIR_Config exit status 1
```

This is from iam-config.yaml (presumably related ):
```
 - deploymentTargets:
      organizationalUnits:
        - Root
    roles:
      - name: EC2-Default-SSM-AD-Role
        instanceProfile: true
        assumedBy:
          - type: service
            principal: ec2.amazonaws.com
        policies:
          awsManaged:
            - AmazonSSMManagedInstanceCore
            - AmazonSSMDirectoryServiceAccess
            - CloudWatchAgentServerPolicy
        boundaryPolicy: AWSAccelerator-Default-Boundary-Policy
```

**Expected behavior**
This is expected to work.  Nothing changed in the config from the successful deployment  in 1.4.3

**Please complete the following information about the solution:**

- [ ] Version: 1.5.0

- [ ] Region:  us-east-2
- [ ] Was the solution modified from the version published on this repository? no
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? N/A
- [ ] Were there any errors in the CloudWatch Logs? NA

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
