### ISSUE TITLE
identityCenterPermissionSets - add custom tags

### ISSUE THREAD

**Issue by dbaileyut** [awslabs/landing-zone-accelerator-on-aws#299]
**Is your feature request related to a problem? Please describe.**
I would like to manage Permission Sets in LZA but can't set custom tags

**Describe the feature you'd like**
Add a tags property to the config and implement it:

```
identityCenterPermissionSets:
  - name: PermissionSet1
    policies:
      awsManaged:
        - arn:aws:iam::aws:policy/AdministratorAccess
        - PowerUserAccess
    tags:
      foo: bar
      xyz: abc
```

**Additional context**
