### ISSUE TITLE
Unable to add customer managed policies to IAM roles

### ISSUE THREAD

**Issue by tbmorris** [awslabs/landing-zone-accelerator-on-aws#30]
**Describe the bug**
I appear unable to add customer managed policies to IAM roles.

**To Reproduce**
Try to add a customer managed policy to an IAM role within iam-config.yaml

**Expected behavior**
I am expecting to be able to add customer managed policies to IAM roles.  Specifically, I am trying to add the LZA generated Session Manager roles to this specific role.

**Please complete the following information about the solution:**

- [ ] Version: v1.2.2
- [ ] Region: us-gov-west-1
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? N/A
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? N/A
- [ ] Were there any errors in the CloudWatch Logs? No

**Additional context**

I am trying to create all IAM roles necessary to use EKS in the iam-config.yaml file.  I can create multiple IAM roles with no problem.  When I add the role with only AWS managed policies there are no problems.  If I try the same action with only customer managed polices or with both customer managed polices and AWS managed policies, it fails with no apparent error (see attached CodeBuild logs).  I have tried assigning customer managed policies with both arn and name, and both have the same results.  I even tried to use the wrong customer managed policy name (as seen in the attached CodeBuild log), and I still have no error in the logs, but end up with a failure.

```yaml
roleSets:
  # Roles for EKS
  - deploymentTargets:
      accounts:
        - NCCTDev
    roles:
      - name: eksRole
        assumedBy:
          - type: service
            principal: eks.amazonaws.com
        policies:
          awsManaged:
            - AmazonEKSClusterPolicy
      - name: eksNodeRole-temp
        assumedBy:
          - type: service
            principal: ec2.amazonaws.com
        policies:
          awsManaged:
            - AmazonEKSWorkerNodePolicy
            - AmazonEKS_CNI_Policy
            - AmazonS3FullAccess
            - AmazonEC2ContainerRegistryReadOnly
          customerManaged:
            - arn:aws-us-gov:iam::****:policy/AWSAccelerator-SessionManagerLogging-us-gov-west-1
            - arn:aws-us-gov:iam::****:policy/AWSAccelerator-SessionManagerUserKMS-us-gov-west-1
```
[CodeBuild-Output.txt](https://github.com/awslabs/landing-zone-accelerator-on-aws/files/10238183/CodeBuild-Output.txt)
