### ISSUE TITLE
`No stacks match` while using `applications` custom config

### ISSUE THREAD

**Issue by bmorrison-console** [awslabs/landing-zone-accelerator-on-aws#300]
**Describe the bug**

Hello

Thanks for such an awesome project!

We're having trouble getting an `applications` configuration working in our test LZA v1.5.1 instance's customizations-config.yaml because we are consistently getting the following error at cdk deploy time (both locally and in codebuild):

```
2023-10-26 07:30:17.800 | error | toolkit | No stacks match the name(s) example_persona-lza-CustomizationsStack-555555555555-ap-southeast-2
```

(where 555555555555 is the correct workload account we are attempting to deploy the `application` block to).

**To Reproduce**

Given the following configuration in customizations-config.yaml (note: this version is based off of the test config found at https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/source/packages/%40aws-accelerator/accelerator/test/configs/all-enabled-ou-targets/customizations-config.yaml, but we see the same error for any `applications:` config. We just included this as it's bound to be most 'correct' /readable for you):

```
applications:
  - name: appA
    vpc: Dev
    deploymentTargets:
      accounts:
        - Network
      excludedRegions:
        - us-west-2
    autoscaling:
      name: appA-asg
      maxSize: 4
      minSize: 1
      desiredSize: 2
      launchTemplate: appA-lt
      healthCheckGracePeriod: 300
      healthCheckType: ELB # EC2|ELB
      targetGroups:
        - appA-nlb-tg
      subnets:
        - Dev-App-A
        - Dev-App-B
    launchTemplate:
      name: appA-lt
      blockDeviceMappings:
        - deviceName: /dev/xvda
          ebs:
            deleteOnTermination: true
            encrypted: false
            kmsKeyId: xxx
        - deviceName: /dev/xvdg
          ebs:
            deleteOnTermination: true
            encrypted: true
            volumeSize: 20
      securityGroups:
        - App
      iamInstanceProfile: EC2-Default-SSM-AD-Role
      imageId: ${ACCEL_LOOKUP::ImageId:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}
      instanceType: t3.xlarge
      networkInterfaces:
        - deleteOnTermination: true
          description: secondary network interface
          deviceIndex: 1
          groups:
            - App
          networkCardIndex: 1
          subnetId: Dev-App-A
    targetGroups:
      - name: appA-nlb-tg
        port: 80
        protocol: HTTP
        type: instance
        protocolVersion: HTTP1
        connectionTermination: true
        preserveClientIp: true
        proxyProtocolV2: true
      - name: appA-alb-tg-1
        port: 80
        protocol: HTTP
        type: instance
        connectionTermination: true
        preserveClientIp: true
        proxyProtocolV2: true
        healthCheck:
          enabled: true
          port: 80
          protocol: HTTP
    networkLoadBalancer:
      name: appA-nlb
      scheme: internal
      deletionProtection: true
      subnets:
        - Dev-App-A
        - Dev-App-B
      crossZoneLoadBalancing: true
      listeners:
        - name: appA-listener-1
          port: 80
          protocol: TCP
          targetGroup: appA-nlb-tg
```

**Expected behavior**

We expect all stacks created by the synth above to be deployed successful with no cdk deploy errors.

**Please complete the following information about the solution:**

- [x] Version: 1.5.1

- [x] Region: ap-southeast-2

- [x] Was the solution modified from the version published on this repository?  No

- [x] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes
- [x] Were there any errors in the CloudWatch Logs? codebuild errors

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

The Customizations codebuild action in our pipeline fails with:

```
[Container] 2023/10/26 07:28:44.809818 Running command if [ ! -z "${ACCELERATOR_STAGE}" ]; then yarn run ts-node --transpile-only cdk.ts synth --stage $ACCELERATOR_STAGE --require-approval never --config-dir $CODEBUILD_SRC_DIR_Config --partition aws; fi
yarn run v1.22.19
$ /codebuild/output/src1811/src/s3/00/source/packages/@aws-accelerator/accelerator/node_modules/.bin/ts-node --transpile-only cdk.ts synth --stage customizations --require-approval never --config-dir /codebuild/output/src1811/src/s3/01 --partition aws
Done in 70.74s.

[Container] 2023/10/26 07:29:57.414477 Running command if [ "diff" != "${CDK_OPTIONS}" ]; then yarn run ts-node --transpile-only cdk.ts --require-approval never $CDK_OPTIONS --config-dir $CODEBUILD_SRC_DIR_Config --partition aws --app cdk.out; fi
yarn run v1.22.19
$ /codebuild/output/src1811/src/s3/00/source/packages/@aws-accelerator/accelerator/node_modules/.bin/ts-node --transpile-only cdk.ts --require-approval never deploy --stage customizations --config-dir /codebuild/output/src1811/src/s3/01 --partition aws --app cdk.out

✨  Synthesis time: 0.02s

example_persona-lza-CustomizationsStack-111111111111-ap-southeast-2: deploying... [1/1]
example_persona-lza-CustomizationsStack-111111111111-ap-southeast-2: creating CloudFormation changeset...

 ✅  example_persona-lza-CustomizationsStack-111111111111-ap-southeast-2 (no changes)

✨  Deployment time: 1.08s

Stack ARN:
arn:aws:cloudformation:ap-southeast-2:111111111111:stack/example_persona-lza-CustomizationsStack-111111111111-ap-southeast-2/3fb85d80-6d81-11ee-a1e4-0a808fb4eb49

✨  Total time: 1.1s

✨  Synthesis time: 0.01s

Assuming role arn:aws:iam::222222222222:role/AWSControlTowerExecution for 3600 seconds

✨  Synthesis time: 0.01s

Assuming role arn:aws:iam::333333333333:role/AWSControlTowerExecution for 3600 seconds

✨  Synthesis time: 0.01s

Assuming role arn:aws:iam::444444444444:role/AWSControlTowerExecution for 3600 seconds
example_persona-lza-CustomizationsStack-333333333333-ap-southeast-2: deploying... [1/1]
example_persona-lza-CustomizationsStack-222222222222-ap-southeast-2: deploying... [1/1]
example_persona-lza-CustomizationsStack-444444444444-ap-southeast-2: deploying... [1/1]
example_persona-lza-CustomizationsStack-222222222222-ap-southeast-2: creating CloudFormation changeset...
example_persona-lza-CustomizationsStack-333333333333-ap-southeast-2: creating CloudFormation changeset...
example_persona-lza-CustomizationsStack-444444444444-ap-southeast-2: creating CloudFormation changeset...

 ✅  example_persona-lza-CustomizationsStack-222222222222-ap-southeast-2 (no changes)

✨  Deployment time: 0.66s

Stack ARN:
arn:aws:cloudformation:ap-southeast-2:222222222222:stack/example_persona-lza-CustomizationsStack-222222222222-ap-southeast-2/76c13cc0-7236-11ee-82bc-029dede7538b

✨  Total time: 0.66s

 ✅  example_persona-lza-CustomizationsStack-333333333333-ap-southeast-2 (no changes)

✨  Deployment time: 0.72s

Stack ARN:
arn:aws:cloudformation:ap-southeast-2:333333333333:stack/example_persona-lza-CustomizationsStack-333333333333-ap-southeast-2/4708ec80-6d81-11ee-8116-02e47b4becef

✨  Total time: 0.72s

✨  Synthesis time: 0.01s

Assuming role arn:aws:iam::666666666666:role/AWSControlTowerExecution for 3600 seconds

✨  Synthesis time: 0.01s

Assuming role arn:aws:iam::222222222222:role/AWSControlTowerExecution for 3600 seconds
example_persona-lza-CustomizationsStack-666666666666-ap-southeast-2: deploying... [1/1]
2023-10-26 07:30:17.800 | error | toolkit | No stacks match the name(s) example_persona-lza-CustomizationsStack-555555555555-ap-southeast-2
Deployment failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[Container] 2023/10/26 07:30:17.826459 Command did not exit successfully if [ "diff" != "${CDK_OPTIONS}" ]; then yarn run ts-node --transpile-only cdk.ts --require-approval never $CDK_OPTIONS --config-dir $CODEBUILD_SRC_DIR_Config --partition aws --app cdk.out; fi exit status 1
[Container] 2023/10/26 07:30:17.829554 Phase complete: BUILD State: FAILED
[Container] 2023/10/26 07:30:17.829565 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: if [ "diff" != "${CDK_OPTIONS}" ]; then yarn run ts-node --transpile-only cdk.ts --require-approval never $CDK_OPTIONS --config-dir $CODEBUILD_SRC_DIR_Config --partition aws --app cdk.out; fi. Reason: exit status 1
```

In the above output, the account ID 555555555555 maps to our `Network` account, so the correct `account` in the  `AppConfigItem` is being resolved to the correct account ID. The `synth` stage of the build worked fine, however at deploy time we received the following error from CDK:

```
2023-10-26 07:30:17.800 | error | toolkit | No stacks match the name(s) example_persona-lza-CustomizationsStack-555555555555-ap-southeast-2
```

It is worth noting we have no problems with deploying custom stacks via a `customizations` block. Canned CFN templates are being consumed fine, we only receive this error whenever we specify an `applications` block.

Please note we are brand new to the LZA solution so this may well be an issue with our configuration and/or test LZA setup. However, we're struggling to find a way passed the above error. Possible there something wrong in our configuration to cause this?

Fortunately, I was able to re-produce the error locally. I'll add some simple analysis of what we see going on locally as a comment on this Issue, in case that helps with diagnosing what's going wrong here.

Thanks again!
