### ISSUE TITLE
Service Catalog - Incorrect typing in documentation

### ISSUE THREAD

**Issue by joshuahigginson1** [awslabs/landing-zone-accelerator-on-aws#305]
**Describe the bug**

Documentation regarding the Landing Zone Accelerator Service Catalog 'Launch Constraints' describes possible options for the 'Launch Constraint Type' as:

```
      constraints:
        # Specify an explicit IAM role that AWS Service Catalog will assume, to
        # deploy, update, or terminate a product.
        launch:
          type: Role | localRole
```

When running a pipeline with localRole set, a CFN validation error is raised. 

Please update references from 'localRole' to 'LocalRole' in your documentation.

**To Reproduce**
Run an AWS Landing Zone Accelerator customization with the launch constraint type 'localRole', as specified in documentation.

**Expected behavior**
Build pipeline should NOT fail.
**Please complete the following information about the solution:**

- [v1.5.1] Version: [e.g. v1.5.1]

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [global] Region: [e.g. us-east-1]
- [no] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [yes] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [no] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
