### ISSUE TITLE
LogArchive account general questions

### ISSUE THREAD

**Issue by david-midlink** [awslabs/landing-zone-accelerator-on-aws#306]
Hello,

Based on the AWS LZA documentation, it appears that account names with spaces are not supported. 
https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.AccountConfig.html#:~:text=The%20name%20should%20not%20contain%20any%20spaces%20as%20this%20isn%27t%20supported%20by%20the%20Accelerator.

If I already have a control tower that was set up with an account named "Log Archive" (which includes spaces), and then I apply the LZA on it, I notice that in the accounts.yaml file, the account name is represented as "LogArchive" (without spaces). Moreover, in the global.yaml file, there's a Logging option that references the "LogArchive" account. I'm curious about how this will function. Will it operate correctly given the space in the original name "Log Archive", or could this lead to potential issues?

Regards,
David

**Comment by kafka0nkoffee** [comment]
Hi @david-midlink ,
Just came across this while looking for an answer for the same question myself, after not finding a solid answer anywhere I just went ahead and deployed the LZA accounts-config with the account name as "LogArchive" instead of "Log Archive" and everything has been working as expected. Not sure when the aws folks will respond but in the meantime I hope this unblocks you.

**Comment by david-midlink** [comment]
Hi,

Thank you for the update. I've managed to get the LZA up and running. However, I've observed that the account is named "LogArchive" in the account.yaml file, and this same name appears under the account option in the global.yaml file. Given that LZA is unable to handle spaces in account names, I'm curious about how this might affect the system's functionality.

```
logging:
  account: LogArchive
  cloudtrail:
    enable: false
    organizationTrail: false
    organizationTrailSettings:
      multiRegionTrail: true
      globalServiceEvents: true
      managementEvents: true
      s3DataEvents: true
      lambdaDataEvents: true
      sendToCloudWatchLogs: true
      apiErrorRateInsight: false
      apiCallRateInsight: false
    accountTrails: []
    lifecycleRules: []
  sessionManager:
    sendToCloudWatchLogs: false
    sendToS3: false
    excludeRegions: []
    excludeAccounts: []
    lifecycleRules: []
    attachPolicyToIamRoles: []
```
