### ISSUE TITLE
Support multiple sets of shared VPC interface endpoints

### ISSUE THREAD

**Issue by jasoncourcoux-e2e** [awslabs/landing-zone-accelerator-on-aws#313]
It would be useful to be able to have multiple sets of VPC interface endpoints.  

This is to support use-cases such as:

- Dev/Prod sets of endpoints
- Separation of platform and workload traffic
- Separation of traffic between workload accounts

In our particular use case, we have a number of workloads with the same CIDR range and we would like to restrict all traffic to go via private link, rather than plugging into a central transit gateway.

This could be implemented by allowing a configurable id instead (or as well as) the central/useCentralEndpoints boolean flag. Where the id distinguishes which set of shared endpoints to use.

e.g. on the vpc sharing the endpoints:
```
...
    interfaceEndpoints:
      sharedEndpointsId: workload-a
      subnets:
        - Network-Endpoints-A
        - Network-Endpoints-B
        - Network-Endpoints-C
      endpoints:
        - service: ec2
        - service: sts
    ...
```

And this could be used by the following in the place of useCentralEndpoints:
```
   sharedEndpointsId: workload-a
```

**Comment by 2Wdavidcunliffe** [comment]
I'm also interested in this resolution; I'm currently working on a deployment that spans two regions, and we have duplicate architecture across the regions as one is the Home and the other is Disaster Recovery. Currently, everything is duplicated except the routes for endpoint mappings.

**Comment by EthanSedgwick** [comment]
I'm also interested in this resolution

**Comment by Athanasii** [comment]
Hello @jasoncourcoux-e2e, thank you for filing a feature request with the Landing Zone Accelerator team! Our team will evaluate the applicability of this request for a future release. 

We will keep this issue open for tracking purposes and keep you aware of any status updates going forward. Thank you for supporting Landing Zone Accelerator!

**Comment by bo1984** [comment]
The workaround is a bit complex, but I'll try to provide a rough summary. The important thing to note is the ability to avoid DNS collisions that will fail either your stacks or with the LZA pipeline, the LZA generated networking stacks. When you look at a config where centralized endpoints, and I'll use our [sample config](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/reference/sample-configurations/lza-sample-config/network-config.yaml) as a reference point. This is our centralized VPC, and more specifically it's endpoints:

**Central VPC**
```
gatewayEndpoints:
      defaultPolicy: Default
      endpoints:
        - service: s3
        - service: dynamodb
    interfaceEndpoints:
      central: true
      defaultPolicy: Default
      subnets:
        - Network-Endpoints-A
        - Network-Endpoints-B
      endpoints:
        - service: ec2
        - service: ec2messages
        - service: ssm
        - service: ssmmessages
        - service: kms
        - service: logs
```

**Spoke VPC**
```
gatewayEndpoints:
      defaultPolicy: Default
      endpoints:
        - service: s3
        - service: dynamodb
    useCentralEndpoints: true
```

What LZA does here at a high-level is:

1) Creates the VPC Interface endpoints
2) Creates the Private Hosted Zones that have an alias record pointed towards the interface endpoint
3) LZA provisions a Lambda that will authorize the VPCs (that have `useCentralEndpoints` set to `true`) and associates the hosted zone to that VPC.

I wanted to give a run through of that as the process would be similar should you chose to lean on our customizations layer to perform this. For steps one and two, you can lean on the native CloudFormation (CFN) objects in a CFN template to provision these resources. For step 3, you'll need to lean on automation (Lambda within the CFN stack) to perform the logic. Please note that with this automation, we have cross-account API calls being made, so you'll need to also account for that for VPCs that will use a secondary centralized VPC for endpoint distribution. 
```
