### ISSUE TITLE
NetworkVpc Stack exceeds the allowed maximum 500

### ISSUE THREAD

**Issue by jobalbz** [awslabs/landing-zone-accelerator-on-aws#320]
2023-11-10 21:26:54.992 | [31merror[39m | accelerator | Number of resources in stack 'LZADev-NetworkVpcStack-xxxxxxxxxxx-ca-central-1': 545 is greater than allowed maximum of 500: AWS::SSM::Parameter (129), AWS::EC2::PrefixList (1), Custom::DeleteDefaultVpc (1), AWS::IAM::Role (10), AWS::Lambda::Function (3), AWS::Logs::LogGroup (9), AWS::EC2::VPC (6), AWS::IAM::Policy (6), AWS::EC2::FlowLog (12), Custom::DeleteDefaultSecurityGroupRules (6), AWS::EC2::VPCCidrBlock (1), AWS::EC2::RouteTable (6), AWS::EC2::Route (6), AWS::EC2::Subnet (83), AWS::EC2::SubnetRouteTableAssociation (83), AWS::RAM::ResourceShare (47), Custom::SsmPutParameterValue (5), AWS::EC2::TransitGatewayVpcAttachment (6), AWS::EC2::SecurityGroup (20), AWS::EC2::SecurityGroupIngress (65), AWS::EC2::NetworkAcl (5), AWS::EC2::SubnetNetworkAclAssociation (15), AWS::EC2::NetworkAclEntry (20)

**Comment by bo1984** [comment]
Hi Joseph! Thank you for using the Landing Zone Accelerator on AWS solution. Looking at the error you've provided, it looks like you're running into a hard limit of the AWS CloudFormation service. In particular, this is the number of resources that a CloudFormation stack can support, which is documented [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html). 

```
Resources | Maximum number of resources that you can declare in your AWS CloudFormation template. | 500 resources | To specify more resources, separate your template into multiple templates by using, for example, nested stacks.
```

Looking at the number of VPCs you're provisioning in the network-config, it looks like you're provisioning 6x VPCs in a single account and region. Is it possible to decouple these to other accounts?

**Comment by bo1984** [comment]
Hi Joseph! Unfortunately the CloudFormation service limit is one that cannot be adjusted and as a result, there are little options outside of decoupling the VPCs from one account. The centralized architecture where you have a centralized VPC for inspection can still be used, but you'd have to rely more on Transit Gateway and performing attachments to the respective VPCs.

**Comment by jobalbz** [comment]
@bo1984 Is this the actual intent of the design for a centralized VPC architecture - less than 6 VPCs? I don't think the ASEA has this limitations. The stack limit can be addressed nested stacks.

**Comment by bo1984** [comment]
@jobalbz that is correct, ASEA does utilized nested stacks to where they're able to utilize the centralized architecture that you referenced, where you could have all of your Workload VPCs in one account. The LZA solution was designed to manage resource dependencies, which can be more difficult in a nested stack approach. This is definitely the case with how we handle our networking stack; the following [documentation](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/managing-resource-dependencies.html) in our implementation guide shows the dependencies with our resources.

If you're trying to achieve a centralized architecture for endpoint distribution, inspection, etc.. it can be achieved. I will keep this issue open on question related if you chose to go down this path.

**Comment by dominikkeil-tqgg** [comment]
I just ran into the same issue but for an OperationsStack 🙄

We're only just starting to build out our AWS Org

<span>
2023-11-24 17:16:48.519 \| error \| accelerator \| Number of resources in stack 'AWSAccelerator-OperationsStack-XXXXXXXXXXXX-yy-zzzz-1': 650 is greater than allowed maximum of 500: AWS::SSM::Parameter (2), Custom::SsmGetParameterValue (1), AWS::IAM::Role (136), AWS::Lambda::Function (133), AWS::Logs::LogGroup (67), AWS::SSO::PermissionSet (11), AWS::IAM::Policy (133), AWS::CloudFormation::CustomResource (66), AWS::SSO::Assignment (101)
</span>

idk how you're gonna tackle this but given the product is to be used like a black box and completely controlled via the config files, this is something I think needs fixing in your design

**Comment by bo1984** [comment]
Hi Dominik, can you provide me a sanitized version of your iam-config?

**Comment by dominikkeil-tqgg** [comment]
> Hi Dominik, can you provide me a sanitized version of your iam-config?

Sure... I can't 100% guarantee I didn't make some things the same that weren't originally during redacting but at least I think I don't have 🙈

The problem came up for an account in OU `Koslais`

I know there's duplication in there in terms of assignments.. That is because for more consistent naming, I was going to rename some permission sets and assignments and would only want to remove the old ones after the new ones are confirmed working. However, this led to the OperationsStack in an account in above mentioned OU to get to almost 700 resources, which then errored during deployment.

Sadly this is a general theme I've observed with LZA so far: Sometimes stuff fails in deployment that could potentially be caught in preparation.

```yaml
common_stuff:
  DEFAULT_SESSION_DURATION: &DEFAULT_SESSION_DURATION 240
  allOUs: &allOUs
    - Root
    - Shayetey
    - Faadee
    - Jassann
    - Elduddin
    - Maethu
    - Koslais
    - Chaydus
    - Addeliya
    - Aatud
    - Londalin
    - Oseid
    - Mellem
    - Jularro
    - Sats
    - Trahino
  nonprodOUs: &nonprodOUs
    - Shayetey
    - Maethu
    - Londalin
    - Oseid
    - Mellem
    - Jularro
    - Sats
    - Trahino
  prodOUs: &prodOUs
    - Root
    - Faadee
    - Jassann
    - Elduddin
    - Maethu
    - Koslais
    - Chaydus
    - Addeliya
    - Aatud

providers: []
policySets: []
roleSets: []
groupSets: []
userSets: []
identityCenter:
  name: IdentityCenterRoot
  identityCenterPermissionSets:
    - name: ViewOnlyAccess
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
      sessionDuration: *DEFAULT_SESSION_DURATION

    - name: ReadOnlyAccess
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/ReadOnlyAccess
      sessionDuration: *DEFAULT_SESSION_DURATION

    - name: SecurityAudit
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/SecurityAudit
      sessionDuration: *DEFAULT_SESSION_DURATION

    - name: PowerUserAccess
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/PowerUserAccess
      sessionDuration: *DEFAULT_SESSION_DURATION

    - name: AdministratorAccess
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/AdministratorAccess
      sessionDuration: *DEFAULT_SESSION_DURATION

    - name: BreakGlassAccess
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/AdministratorAccess
      sessionDuration: *DEFAULT_SESSION_DURATION

    - name: SecurityAuditAccess
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/SecurityAudit
      sessionDuration: *DEFAULT_SESSION_DURATION
    - name: AdminAccess
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/AdministratorAccess
      sessionDuration: *DEFAULT_SESSION_DURATION

    - name: Shafiya
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/ReadOnlyAccess
          - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        customerManaged: # this can only take policy names and assumes they're present at deploy time
          - policy1
          - policy2
          - policy3
          - policy4
      sessionDuration: *DEFAULT_SESSION_DURATION
    - name: Abdorg
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
      sessionDuration: *DEFAULT_SESSION_DURATION
    - name: Leaslun
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
      sessionDuration: *DEFAULT_SESSION_DURATION

  identityCenterAssignments:
    - name: GOTHIY-SecurityAudit
      principals:
        - type: GROUP
          name: GOTHIY
      permissionSetName: SecurityAudit
      deploymentTargets:
        organizationalUnits: *allOUs
        excludedAccounts:
          - Management

    - name: GOTHIY-PowerUserAccess
      principals:
        - type: GROUP
          name: GOTHIY
      permissionSetName: PowerUserAccess
      deploymentTargets:
        organizationalUnits:
          - Faadee
        accounts:
          - Audit
          - Maethu 

    - name: BEROORIN-ViewOnlyAccess
      principals:
        - type: GROUP
          name: BEROORIN
      permissionSetName: ViewOnlyAccess
      deploymentTargets:
        organizationalUnits: *allOUs
        excludedAccounts:
          - Management

    - name: BEROORIN-ReadOnlyAccess
      principals:
        - type: GROUP
          name: BEROORIN
      permissionSetName: ReadOnlyAccess
      deploymentTargets:
        organizationalUnits: *nonprodOUs
        excludedAccounts: []

    - name: BEROORIN-AdministratorAccess
      principals:
        - type: GROUP
          name: BEROORIN
      permissionSetName: AdministratorAccess
      deploymentTargets:
        organizationalUnits: *nonprodOUs
        excludedAccounts: []

    - name: BEROORIN-BreakGlassAccess
      principals:
        - type: GROUP
          name: BEROORIN
      permissionSetName: BreakGlassAccess
      deploymentTargets:
        organizationalUnits: *prodOUs
        excludedAccounts:
          - Management

    - name: SecurityAuditAssignment
      permissionSetName: SecurityAuditAccess
      principalId: &GOTHIY "ID HERE"
      principalType: GROUP
      deploymentTargets:
        accounts:
          - Grafonne
          - Ishanasy
          - Abettie
          - Kemelah
          - Baybee
          - Haijadre
          - Abdenia
          - Faadee
          - Maethu
          - Eassan

    - name: SecurityAuditPowerUserAssignment
      permissionSetName: PowerUserAccess
      principalId: *GOTHIY
      principalType: GROUP
      deploymentTargets:
        accounts:
          - Ishanasy
          - Faadee
          - Maethu 

    - name: Admin
      permissionSetName: AdminAccess
      principalId: &BEROORIN "ID HERE"
      principalType: GROUP
      deploymentTargets:
        accounts:
          - Abettie
          - Kemelah
          - Baybee
          - Haijadre
          - Abdenia
          - Faadee
          - Maethu
          - Eassan
          - TQGG-Production
          - tqgg-infra

    - name: GAMAYSPowerUser
      permissionSetName: PowerUserAccess
      principalId: &GAMAYS "9394f892-50e1-7034-5c49-bed536b43d5a"
      principalType: GROUP
      deploymentTargets:
        accounts:
          - Abettie

    - name: GAMAYSReadOnly
      permissionSetName: ReadOnlyAccess
      principalId: *GAMAYS
      principalType: GROUP
      deploymentTargets:
        accounts:
          - Abettie
          - Kemelah
          - Baybee

    - name: NONPROD_Massula
      permissionSetName: AdminAccess
      principalType: GROUP
      principalId: &JAMATY "ID HERE"
      deploymentTargets:
        accounts:
          - Hirana
          - Atilaur
    - name: PROD_Massula
      permissionSetName: AdminAccess
      principalType: GROUP
      principalId: &GIDEL "ID HERE"
      deploymentTargets:
        accounts:
          - Prierey

    - name: Shaest
      permissionSetName: ReadOnlyAccess
      principalType: GROUP
      principalId: &SORDU "ID HERE"
      deploymentTargets:
        accounts:
          - Eassan
    - name: Olhonna
      permissionSetName: Shafiya
      principalType: GROUP
      principalId: *SORDU
      deploymentTargets:
        accounts:
          - Eassan
    - name: Praany
      permissionSetName: Shafiya
      principalType: GROUP
      principalId: *BEROORIN
      deploymentTargets:
        accounts:
          - Eassan
    - name: Abdorg
      permissionSetName: Abdorg
      principalType: GROUP
      principalId: &DOLAAS "ID HERE"
      deploymentTargets:
        accounts:
          - Eassan
    - name: Leaslun
      permissionSetName: Leaslun
      principalType: GROUP
      principalId: &GEYLAH "ID HERE"
      deploymentTargets:
        accounts:
          - Eassan
```
