### ISSUE TITLE
Unable to create Target Group of type ip

### ISSUE THREAD

**Issue by hpf-mrnf** [awslabs/landing-zone-accelerator-on-aws#332]
**Describe the bug**
When creating target group of type ip, received the following error in Network_Associations stage of the pipeline : **Could not create target group for xxxxxxxxxxxx in vpc xxxxxxx. Please review the target group configuration**

**To Reproduce**
Define a Target group in VPC block as follow:
```
      - name: tg-alb-perimeter-dev00
        port: 80
        protocol: HTTP
        protocolVersion: HTTP1
        type: ip
        healthCheck:
          enabled: true
          port: 80
          protocol: HTTP
```

**Expected behavior**
The target group should be created in specified account (VPC account)

- [ ] Version: v1.5.1

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [ ] Region: ca-central-1
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes

**Additional context**
Deploying the same target group but with type _instance_ worked fine.

**Comment by bo1984** [comment]
targetGroups:
      - name: tg-alb-perimeter-dev00
        port: 80
        protocol: HTTP
        protocolVersion: HTTP1
        type: ip
        healthCheck:
          enabled: true
          port: 80
          protocol: HTTP
        targets:
          - "10.140.96.10"

**Comment by bo1984** [comment]
Hi @hpf-mrnf ! Thank you for utilizing the Landing Zone Accelerator on AWS solution. I was able to replicate the issue that you experienced. For target groups with `ip` set as the target, the logic expects for `targets` to be defined. I was able to get this working in my own VPC (note that the target has to be an IP address, if you're specifying a static IP address, within your VPC range). Otherwise, it has to be an NLB target, if you're defining one.

Here's my example:

```
targetGroups:
      - name: tg-alb-perimeter-dev00
        port: 80
        protocol: HTTP
        protocolVersion: HTTP1
        type: ip
        healthCheck:
          enabled: true
          port: 80
          protocol: HTTP
        targets:
          - "10.140.96.10"
```

I will be filing a bug report on your behalf as you should be able to create a target group for the type of IP without specifying targets. I will keep this issue open should you have any other relevant questions or concerns.
