### ISSUE TITLE
Unable to create Listener of type redirect

### ISSUE THREAD

**Issue by hpf-mrnf** [awslabs/landing-zone-accelerator-on-aws#336]
**Describe the bug**
Unable to create Listener of type redirect in the applicationLoadBalancers block. The construct indicates that you have to specify the targetGroup even for a listener of type redirect. But when deploying the Listener, error bellow occors:
**You cannot specify 'target group ARN' for actions of type 'redirect'** at the Network_Associations step.

Also tried to remove the targetGroup from the listener and got error bellow:
**Error: Could not parse content:
Invalid value undefined supplied to /vpcs/1/loadBalancers/applicationLoadBalancers/0/listeners/0/targetGroup** at the Build stage.

**To Reproduce**
Define the listener as follow:

```
loadBalancers:
      applicationLoadBalancers:
        - name: alb-perimeter-dev-01
          scheme: internet-facing
          subnets:
            - PerimeterNat-A
            - PerimeterNat-B
          securityGroups:
            - Web-Dev
          listeners:
            - name: listener-alb-perimeter-dev01-80
              port: 80
              protocol: HTTP
              targetGroup: tg-dev-default
              order: 1
              type: redirect
              redirectConfig:
                statusCode: HTTP_301
                host: '#{host}'
                path: '/#{path}'
                port: 443
                protocol: HTTPS
                query: '#{query}'
           
```
**Expected behavior**
We should be able to crete listeners of type redirect without defining the targetGroup Arn as supported by the AWS::ElasticLoadBalancingV2::Listener

**Please complete the following information about the solution:**

- [ ] Version: 1.5.1
- [ ] Region: ca-central-1
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/132080444/cee1d1d3-846d-468c-a904-253e9ca8debf)

![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/132080444/c2ff50dc-0964-4993-ba08-f64c00b4bcc4)
