### ISSUE TITLE
Global tags overrides first level network tags

### ISSUE THREAD

**Issue by bruno-chavez** [awslabs/landing-zone-accelerator-on-aws#355]
**Describe the bug**
Global tags defined in `global-config.yaml` override tags defined in `network-config.yaml`, looks like it affects all resources defined at the first level, meaning that nested resources have properly defined tags. Only tested on [prefix lists](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.NetworkConfig.html#prefixLists), [transit gateways](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.NetworkConfig.html#transitGateways), [central networking services](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.NetworkConfig.html#centralNetworkServices), [vpcs](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.NetworkConfig.html#vpcs) and [customer gateways](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.NetworkConfig.html#customerGateways) .

Not sure if feature or bug since the [documentation](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.GlobalConfig.html#tags) does not mention anything regarding this interaction, but is definitely an issue for me since I loose control on how can I tag my networking resources.

**To Reproduce**
1. Define global tags in `global-config.yaml`:
```yaml
tags:
  - key: test1
    value: a
  - key: test2
    value: b
```
2. Define tags in any resource inside `network-config.yaml`, in this example transit gateway and transit gateway route tables:
```yaml
transitGateways:
  - name: twg-test
    account: test
    region: us-east-1
    routeTables:
      - name: test-table
        tags:     <- works fine
          - key: test1
            value: c
          - key: test2
            value: d
    asn: 65500
    dnsSupport: enable
    vpnEcmpSupport: enable
    defaultRouteTableAssociation: disable
    defaultRouteTablePropagation: disable
    autoAcceptSharingAttachments: enable
    tags:          <- doesn't work
        - key: test1
           value: c
        - key: test2
           value: d
```
3. Deploy

**Expected behavior**
Tags defined in `network-config.yaml` should either override global defaults completely or don't at all.

**Please complete the following information about the solution:**

- [x] Version: v1.5.1
- [x] Region: us-east-1
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes
- [x] Were there any errors in the CloudWatch Logs? No

**Screenshots**
**Additional context**
