### ISSUE TITLE
Macie - policyFindingsPublishingFrequency and publishSensitiveDataFindings ignored

### ISSUE THREAD

**Issue by sebolabs** [awslabs/landing-zone-accelerator-on-aws#368]
**Describe the bug**
The following Macie configuration options do not get applied when set to non-default values:
- policyFindingsPublishingFrequency
- publishSensitiveDataFindings

**To Reproduce**
With this:
```
# security-config.yaml

centralSecurityServices:
[...]
  macie:
    enable: true
    excludeRegions: []
    policyFindingsPublishingFrequency: SIX_HOURS
    publishSensitiveDataFindings: true
[...]
```
I end up having this:
![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/8235212/ef511838-1958-49d6-943d-a29ba24e3c81)

**Expected behavior**
- Publish sensitive data findings to Security Hub should be checked
- Update frequency for policy findings should be 6 hours

**Please complete the following information about the solution:**
- [x] Version: `v1.5.2`
- [x] Region: `eu-west-1`
- [x] Was the solution modified from the version published on this repository? `No`
- [x] If the answer to the previous question was yes, are the changes available on GitHub? `N/A`
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? `N/A`
- [x] Were there any errors in the CloudWatch Logs? `No`

**Additional information:**
- Macie-SecurityHub integration is enabled
