### ISSUE TITLE
Solution v1.6.0 OU is not ignored

### ISSUE THREAD

**Issue by smparekh** [awslabs/landing-zone-accelerator-on-aws#378]
**Describe the bug**
v1.6.0 ignore: true not ignoring OU
```
AWSAccelerator-PrepareStack-328290235917-us-gov-west-1 |  55/102 | 4:31:04 AM | CREATE_FAILED        | Custom::ValidateEnvironmentConfiguration           | ValidateEnvironmentConfig/ValidateEnvironmentResource/Default (ValidateEnvironmentConfigValidateEnvironmentResourceD10DC179) Received response status [FAILED] from custom resource. Message returned: Organizational Unit 'Temporary' with id of 'ou-rnr0-3o7gmjuf' was not found in the organization configuration.
```

**To Reproduce**
I have a organization-config.yml with this content
```
enable: true
organizationalUnits:
  - name: Security
  - name: Infrastructure
  - name: Temporary
    ignore: true
quarantineNewAccounts:
  enable: true
  scpPolicyName: Quarantine
serviceControlPolicies:
  - name: AcceleratorGuardrails1
    description: >
      Accelerator GuardRails 1
    policy: service-control-policies/guardrails-1.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits:
        - Infrastructure
  - name: AcceleratorGuardrails2
    description: >
      Accelerator GuardRails 2
    policy: service-control-policies/guardrails-2.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits:
        - Infrastructure
  - name: Quarantine
    description: >
      This SCP is used to prevent changes to new accounts until the Accelerator
      has been executed successfully.
      This policy will be applied upon account creation if enabled.
    policy: service-control-policies/quarantine.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits: []
# Tagging and backup policies are not present in GovCloud
taggingPolicies: []
backupPolicies: []
```

**Expected behavior**
Temporary OU to be ignored

**Please complete the following information about the solution:**

- [x] Version: v1.6.0

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [x] Region: us-gov-west-1
- [x] Was the solution modified from the version published on this repository? - No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [x] Were there any errors in the CloudWatch Logs? - Yes, see above

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
