### ISSUE TITLE
feat(customizations): Add stack parameters

### ISSUE THREAD

**Issue by flochaz** [awslabs/landing-zone-accelerator-on-aws#38]
It would be great if we could specify parameters to `customizations.cloudFormationStacks`. Example:

Example:
```
customizations:
  cloudFormationStacks:
    - deploymentTargets:
        organizationalUnits:
          - SDLC
      description: Project A - Auto CDK bootstrap stack
      name: cdk-bootstrap-template
      regions:
        - us-east-1
      runOrder: 1
      template: cloudformation-templates/cdk-bootstrap-template.yaml
      terminationProtection: true
      parameters:
        - CDK_VERSION: 2.48.0
        - QUALIFIER: projectA
```
