### ISSUE TITLE
Unable to Create Registered Targets in Target Group

### ISSUE THREAD

**Issue by pamelaeteng26** [awslabs/landing-zone-accelerator-on-aws#385]
**Describe the bug**
When attempting to create a target group of type 'ip' in VPC, the target group is created but the registered target is not created. No errors are reported in the pipeline; however, the deployed targets do not reflect in the specified account.

**To Reproduce**
Define a target group in the VPC block with the following specifications, specify an IP address from the subnets of the virtual private cloud (VPC) in another account separate from where the target group is deployed.
  
  ```
 - name: tg-alb-perimeter-dev00
        port: 80
        protocol: HTTP
        protocolVersion: HTTP1
        type: ip
        healthCheck:
          enabled: true
          port: 80
          protocol: HTTP
          targets:
           - "10.0.0.0/8" #for-example 
```

**Expected behavior**
The registered target should be successfully created in the specified VPC account.

**Please complete the following information about the solution:**

- [x] Version: [v1.6.0]

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [x] Region: [e.g. eu-west-2]
- [x] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes
- [x] Were there any errors in the CloudWatch Logs? No
