### ISSUE TITLE
Quota limits always created in home region

### ISSUE THREAD

**Issue by thomaslarsen** [awslabs/landing-zone-accelerator-on-aws#386]
**Describe the bug**
When specifying quota limits in the `global-config.yaml` configuration file, they always get created in the home region even if the `regions` setting is specified.

Specifying limits without the `regions` setting like this works fine, i.e. they get created in the home region:
```
limits:
  - serviceCode: codebuild
    quotaCode: L-9D07B6EF
    desiredValue: 300
    deploymentTargets:
      accounts:
        - Management
```

However when specifying a limit for a different region like this, it still only gets created in the home region:
```
limits:
  - serviceCode: lambda
    quotaCode: L-B99A9384
    desiredValue: 100
    regions:
      - us-east-1
    deploymentTargets:
      accounts:
        - Management
```
**To Reproduce**
Add a limit request to the `global-config.yaml` file with a region different from the home region.

**Expected behavior**
The expected behaviour is that the limit request is applied in the region(s) specified under the `regions` setting.

**Please complete the following information about the solution:**

- [x] Version: 1.6.0

- [x] Region: eu-central-1
- [x] The solution is based on the [TSE-SE reference configuration](https://github.com/aws-samples/landing-zone-accelerator-on-aws-for-tse-se), but has been modified to suit specific needs
- [x] If the answer to the previous question was yes, are the changes available on GitHub? No
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes
- [x] Were there any errors in the CloudWatch Logs? No

**Comment by bo1984** [comment]
Hi Thomas! Thank you for reaching out and utilizing the Landing Zone Accelerator on AWS (LZA) solution. I've taken a similar configuration that you specified in your initial post:

```
limits:
  - serviceCode: lambda
    quotaCode: L-B99A9384
    desiredValue: 100
    regions:
      - eu-west-1
    deploymentTargets:
      accounts:
        - Network
```

In my configuration, I have `us-east-1` set as my `homeRegion`. When I do a synth on my stack, I was able to see that logger statement [here](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/11a38bd38aa931a75121a81f50e222ccec6f4202/source/packages/%40aws-accelerator/accelerator/lib/stacks/operations-stack.ts#L309) invoked in the `increaseLimits` based in the `Operations` stack in `us-east-1`.

```
2024-01-25 11:18:00.606 | info | AWSAccelerator-OperationsStack-[REMOVED]-us-east-1 | Regions property not specified, creating service quota increase L-B99A9384 in home region
```

I will go ahead and create a bug report for this issue. I will keep this issue open in the meantime to maintain communication on the status of this issue. Please let us know if you have any other questions or concerns in the meantime.
