### ISSUE TITLE
Deploying solution to GovCloud results in error in PrepareStack

### ISSUE THREAD

**Issue by smparekh** [awslabs/landing-zone-accelerator-on-aws#390]
**Describe the bug**
According to Step 2.5 of the instructions (https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/option-1-deploy-to-new-standard-and-aws-govcloud-us-accounts.html) to deploy to US GovCloud I modified the accounts-config.yaml to include the Account Ids

to reflect the account Ids from the mapping table in commercial deployment:
```
# govCloud accounts-config.yaml
mandatoryAccounts:
  - name: Management
    description: >-
      The management (primary) account. Do not change the name field for this mandatory account.
    email: mgmt@quindar.space
    organizationalUnit: Root
  - name: LogArchive
    description: >-
      The log archive account. Do not change the name field for this mandatory account.
    # pre-populated from input in installer stack.
    # vended govCloud account email for log archive
    email: logarchive-gc@quindar.space
    organizationalUnit: Security
  - name: Audit
    description: >-
      The security audit account (also referred to as the audit account). Do not change the name field for this mandatory account.
    # pre-populated from input in installer stack.
    # vended govCloud account email for audit
    email: audit-gc@quindar.space
    organizationalUnit: Security
workloadAccounts: []
accountIds:
  - email: mgmt@quindar.space
    accountId: 'XXXXXXXXXXXX'
  - email: logarchive-gc@quindar.space
    accountId: 'XXXXXXXXXXXX'
  - email: audit-gc@quindar.space
    accountId: 'XXXXXXXXXXXX'
```

Results in an error in Prepare Stack:
```
Received response status [FAILED] from custom resource. Message returned: Organizational Unit "Infrastructure" not found.,Organizational Unit "Security" not found.,Mandatory account audit-gc@quindar.space does not exist in AWS or is suspended,Mandatory account logarchive-gc@quindar.space does not exist in AWS or is suspended,Organizational Unit Infrastructure does not exist in AWS. Either remove from configuration or add OU via console.,Organizational Unit Security does not exist in AWS. Either remove from configuration or add OU via console. Logs: /aws/lambda/AWSAccelerator-PrepareSta-ValidateEnvironmentConfi-OgJsr2elVRzf at Runtime.Xur [as handler] (/var/task/index.js:10296:320469) at processTicksAndRejections (node:internal/process/task_queues:96:5) (RequestId: 3d44682d-445b-4efc-b01e-7132bb69037b)
```

OUs exist:
<img width="954" alt="Screenshot 2024-02-01 at 17 53 43" src="https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/2242057/fcc291e7-8c33-4317-b03f-164400adcb41">

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
Deployment should proceed as expected with the AccountIds being invited into the Org

**Please complete the following information about the solution:**

- [x] Version: v1.6.0

- [x] Region: us-gov-west-1
- [x] Was the solution modified from the version published on this repository? NO
- [x] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [x] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
