### ISSUE TITLE
SNSTopic does not support other services than CloudWatch

### ISSUE THREAD

**Issue by yannickvr** [awslabs/landing-zone-accelerator-on-aws#409]
**Describe the bug**

After creating an SNS topic from the global-config file, it's access policy only allows publishing from CloudWatch. I also want to use Budgets and have it send it's alerts to the SNS topic.

I'm not sure where the bug actually is: does the SNS implementation miss an option to update it's policy or should AWS budgets update the policy to allow itself? 

**To Reproduce**
```
snsTopics:
  deploymentTargets:
    organizationalUnits:
      - Root
  topics:
    - name: budgets
      emailAddresses:
        - budgets@domain.com
reports:
  budgets:
      - name: budget-example
        deploymentTargets:
          accounts:
            - Management    
        unit: USD
        notifications:
        - type: ACTUAL
          thresholdType: PERCENTAGE
          threshold: 100
          comparisonOperator: GREATER_THAN
          subscriptionType: SNS
          recipients:
          - arn:aws:sns:eu-west-1:01234567890:aws-accelerator-budgets
```

**Expected behavior**
I would expect to be able to create an SNS topic and a AWS Budget report, and send the budget alerts to the SNS topic, without any custom fixes.

**Please complete the following information about the solution:**

- [1.6.0 ] Version: [e.g. v1.5.1]

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [ eu-west-1] Region: [e.g. us-east-1]
- [n ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
