### ISSUE TITLE
Pipeline times out at AuditManagerEnableOrganizationAdminAccount on eu-west-3

### ISSUE THREAD

**Issue by zaid-themedcompany** [awslabs/landing-zone-accelerator-on-aws#416]
**Describe the bug**
When running LZA for healthcare configuration [here](https://github.com/awslabs/landing-zone-accelerator-on-aws/tree/main/reference/sample-configurations/lza-sample-config-healthcare) and I deploy the solution to eu-west-3 (Paris) then the **AWSAccelerator-Pipeline** fails in the **Organization** stage and stack **AWSAccelerator-OrganizationsStack-xxxxx-eu-west-3** runs till it times out, and fails to create logical Id **AuditManagerEnableOrganizationAdminAccount**

Is this happening config used for lza healthcare required Audit manager service which isn't available in Paris eu-west-3?

**To Reproduce**
Run the lza with the healthcare configuration (excerpt below)

```
##################################################################################################################
# For additional configurable services, features, and property descriptions,                                     #
# please review our network configuration reference in our README.md:                                            #
# https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.SecurityConfig.html  #
##################################################################################################################

homeRegion: &HOME_REGION us-east-1
centralSecurityServices:
  ##################################################################################################################
  # Based upon AWS Security Reference Architecture (AWS SRA),                                                      #
  # Assigning delegated administrator to security tooling (Audit) account                                          #
  # https://docs.aws.amazon.com/prescriptive-guidance/latest/security-reference-architecture/security-tooling.html #
  ##################################################################################################################
  delegatedAdminAccount: Audit
  ebsDefaultVolumeEncryption:
    enable: true
    excludeRegions: []
  s3PublicAccessBlock:
    enable: true
    excludeAccounts: []
  scpRevertChangesConfig:
    enable: true
    snsTopicName: Security
  macie:
    enable: true
    excludeRegions: []
    policyFindingsPublishingFrequency: FIFTEEN_MINUTES
    publishSensitiveDataFindings: true
  guardduty:
    enable: true
    excludeRegions: []
    s3Protection:
      enable: true
      excludeRegions: []
    exportConfiguration:
      enable: true
      overrideExisting: true
      destinationType: S3
      exportFrequency: FIFTEEN_MINUTES
  auditManager:
    enable: true
    excludeRegions: []
    defaultReportsConfiguration:
      enable: true
      destinationType: S3
    lifecycleRules:
      - enabled: true
        abortIncompleteMultipartUpload: 7
        expiration: 1000
        noncurrentVersionExpiration: 1000
  detective:
    enable: false
    excludeRegions: []
  ##################################################################################################################
  # AWS Security Hub Configurations                                                                                #
  ##################################################################################################################
  securityHub:
    enable: true
    regionAggregation: true
    excludeRegions: []
    standards:

```

**Expected behavior**
It should pass and the **AWSAccelerator-Pipeline** finishes successfully

**Please complete the following information about the solution:**

- [ ] Version: 1.6.1

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [ ] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by zaid-themedcompany** [comment]
Also deleting the stack takes ages (I suppose again because there is no AWS Audit manager in eu-west-3)
![CloudFormation - deleting_failed_Stack](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/102984462/1a916a25-5dcb-4617-9578-632d80c439f4)
?

**Comment by zaid-themedcompany** [comment]
I tried a workaround to exclude Paris region from the audit Manager in security-config.yaml, but no luck: 


```
  auditManager:
    enable: true
    excludeRegions:
      - eu-west-3
```

I also tried exclude Paris from the awsConfig using the following:

```
awsConfig:
  excludeRegions:
    - eu-west-3
```
But got the following error in the pipeline in **Security_Resources stage** and the stack **AWSAccelerator-SecurityResourcesStack-xxxxx-eu-west-3**
```
"Invalid request provided: NoAvailableConfigurationRecorder"
```
![CloudFormation - Stack AWSAccelerator-SecurityResourcesStack-eu-west-3 2024-03-07 14-08-05](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/102984462/228a1613-da67-46cf-9fa8-497b6043fe3a)
