### ISSUE TITLE
CloudFormation Stacks do not support lists as parameters.

### ISSUE THREAD

**Issue by yannickvr** [awslabs/landing-zone-accelerator-on-aws#417]
**Describe the bug**
I'm trying to deploy a CF template using the customizations-config. My template expects a list as parameter, but the stack synthesis fails:

```
2024-03-12 13:07:28.249 | error | accelerator | Resolution error: Supplied properties not correct for "CfnStackSetProps"
  stackInstancesGroup: element 0: supplied properties not correct for "StackInstancesProperty"
    deploymentTargets: supplied properties not correct for "DeploymentTargetsProperty"
      organizationalUnitIds: "r-gqx8," should be a list.
/codebuild/output/src564/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/accelerator.ts:58
    throw new Error('Synthesis failed');
    ^
```

**To Reproduce**
- Add a CloudFormation template to `customizations-config.yaml` as below:
```
homeRegion: &HOME_REGION eu-central-1
customizations:
  cloudFormationStackSets: []
  cloudFormationStacks: []
    - name: example
      description: example
      regions:
        - *HOME_REGION
      deploymentTargets:
        accounts:
          - Management
      runOrder: 1
      template: ./cfn-templates/example.yml
      terminationProtection: true  
      parameters:
        - name: ListParam
          value: 
            - r-gqx8  
```

Note: for value i tried:

- value: [ value ]
- value: "value"
- value: value,
- value: "value,"

All give either the same error, or error at build validation.
 
Parameter in CFN template:

```
Parameters:
  ListParam:
    Type: CommaDelimitedList
```

**Expected behavior**
Stack is deployed without errors

**Please complete the following information about the solution:**

- [x] Version: 1.6.1
- [x] Region: eu-central-1
- [x] Was the solution modified from the version published on this repository? no
- [x] If the answer to the previous question was yes, are the changes available on GitHub? 
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? n/a
- [x] Were there any errors in the CloudWatch Logs? Yes, see bug description

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
