### ISSUE TITLE
ssmAutomation is not sharing documents with other accounts

### ISSUE THREAD

**Issue by senyberg** [awslabs/landing-zone-accelerator-on-aws#419]
**Describe the bug**
ssmAutomation is not sharing documents created by LZA, despite configuring it to do so. 

Documentation (https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/latest/classes/_aws_accelerator_config.DocumentSetConfig.html#shareTargets) says it should share.

The document is found in the Audit account.

Configuration snippet:

```
ssmAutomation:
    documentSets:
      - shareTargets:
          organizationalUnits:
            - Workloads
        documents:
          # Calls the AWS CLI to enable access logs on a specified ELB
          - name: SSM-ELB-Enable-Logging
            template: ssm-documents/ssm-elb-enable-logging.yaml
```

**To Reproduce**
Configure ssmAutomation as above, run pipeline

**Expected behavior**
SSM Automation document should be shared with shared account(s)

**Please complete the following information about the solution:**

- [x] Version: 1.6.1

- [x] Region: eu-north-1
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?
