### ISSUE TITLE
Stale transit gateway ID 

### ISSUE THREAD

**Issue by snemir2** [awslabs/landing-zone-accelerator-on-aws#426]
Hello --
After modifying the network configuration, the transient gateway was reprovisioned, and now I am getting the following error in one of the accounts.  The attachm) ent id is indeed is old.  But where does this stale ID is coming from? (I checked, and it is not the SSM parameter in the XXX account.  Assistance would be greatly appreciated; I hope to force the correct attachment ID to the LZA to complete the update. 
```
AWSAccelerator-NetworkVpcStack-XXX-us-east-2 | 8:27:26 PM | UPDATE_FAILED        | AWS::EC2::TransitGatewayVpcAttachment | CustomersMainVpcTransitGatewayAttachment (CustomersMainVpcTransitGatewayAttachment58A1C7E8) Resource handler returned message: "Transit Gateway Attachment tgw-attach-0c1877472ff48523e was deleted or does not exist. (Service: Ec2, Status Code: 400, Request ID: 66694516-44d6-4e1f-b24c-d7c82a84a282)" (RequestToken: bcccd3b9-08c4-0aef-3800-e5a082b53cb6, HandlerErrorCode: NotFound)
    new TransitGatewayAttachment (/codebuild/output/src2132/src/s3/00/source/packages/@aws-accelerator/constructs/lib/aws-ec2/transit-gateway.ts:326:20)
    \_ TgwResources.createTgwAttachments (/codebuild/output/src2132/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/network-stacks/network-vpc-stack/tgw-resources.ts:202:24)
    \_ new TgwResources (/codebuild/output/src2132/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/network-stacks/network-vpc-stack/tgw-resources.ts:58:34)
    \_ new NetworkVpcStack (/codebuild/output/src2132/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/network-stacks/network-vpc-stack/network-vpc-stack.ts:79:26)
    \_ createNetworkVpcStacks (/codebuild/output/src2132/src/s3/00/source/packages/@aws-accelerator/accelerator/utils/stack-utils.ts:923:22)
    \_ createMultiAccountMultiRegionStacks (/codebuild/output/src2132/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:182:29)
    \_ main (/codebuild/output/src2132/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:243:5)
    \_ processTicksAndRejections (node:internal/process/task_queues:96:5)
    \_ async /codebuild/output/src2132/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:251:5
```

**Comment by snemir2** [comment]
Hi @bo1984  - 
The attachment does not exist anymore.   
The change that   caused this was actually in global config, just added 
```
tags:
 - key: "map-migrated"
   value: "migXXXX"
```

But a while back, Removed and since readded transit gateway attachment:
![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/10503843/9f1d334a-a575-455f-991d-604dbc836565)




The vpcTemplate looks like the following now
```
- name: Customers-templated-VPC
    region: *HOME_REGION
    internetGateway: true
    enableDnsHostnames: true
    enableDnsSupport: true
    deploymentTargets:
      organizationalUnits:
        - Customers
    instanceTenancy: default
    ipamAllocations:
      - ipamPoolName: home-region-customers-pool
        netmaskLength: 18

    routeTables:
      - name: Customers-Private-Attachment-route
        routes:
        - name: TgwRoute
          destination: 10.1.0.0/16 #central vpc
          type: transitGateway
          target: Network-Main-TGW

      - name: Customers-Private-RT-A
        routes:
          - name: TgwRoute
            destination: 10.1.0.0/16 #central vpc
            type: transitGateway
            target: Network-Main-TGW
          - name: S3Gateway
            type: gatewayEndpoint
            target: s3
          - name: DynamoDBGateway
            type: gatewayEndpoint
            target: dynamodb
          - name: NatRoute
            destination: 0.0.0.0/0
            type: natGateway
            target: Nat-Network-Customers-A
      - name: Customers-Private-RT-B
        routes:
          - name: TgwRoute
            destination: 10.1.0.0/16 #central vpc
            type: transitGateway
            target: Network-Main-TGW
          - name: S3Gateway
            type: gatewayEndpoint
            target: s3
          - name: DynamoDBGateway
            type: gatewayEndpoint
            target: dynamodb
          - name: NatRoute
            destination: 0.0.0.0/0
            type: natGateway
            target: Nat-Network-Customers-B
      - name: Customers-Public-RT
        routes:
          - name: IgwRoute
            destination: 0.0.0.0/0
            type: internetGateway
            target: IGW
          - name: TgwRoute
            destination:  10.1.0.0/16 
            type: transitGateway
            target: Network-Main-TGW
          - name: S3Gateway
            type: gatewayEndpoint
            target: s3
          - name: DynamoDBGateway
            type: gatewayEndpoint
            target: dynamodb

    subnets:
      - name: Customers-Public-A
        availabilityZone: a
        routeTable: Customers-Public-RT
        ipamAllocation:
          ipamPoolName: home-region-customers-pool
          netmaskLength: 22
      - name: Customers-Public-B
        availabilityZone: b
        routeTable: Customers-Public-RT
        ipamAllocation:
          ipamPoolName: home-region-customers-pool
          netmaskLength: 22
      - name: Customers-Private-A
        availabilityZone: a
        routeTable: Customers-Private-RT-A
        ipamAllocation:
          ipamPoolName: home-region-customers-pool
          netmaskLength: 20
      - name: Customers-Private-B
        availabilityZone: b
        routeTable: Customers-Private-RT-B
        ipamAllocation:
          ipamPoolName: home-region-customers-pool
          netmaskLength: 20

      - name: Customers-MainTgwAttach-A
        availabilityZone: a
        routeTable: Customers-Private-Attachment-route
        ipamAllocation:
          ipamPoolName: home-region-customers-pool
          netmaskLength: 25
      - name: Customers-MainTgwAttach-B
        availabilityZone: b
        routeTable: Customers-Private-Attachment-route
        ipamAllocation:
          ipamPoolName: home-region-customers-pool
          netmaskLength: 25
    natGateways:
      - name: Nat-Network-Customers-A
        subnet: Customers-Public-A
      - name: Nat-Network-Customers-B
        subnet: Customers-Public-B


    transitGatewayAttachments:
      - name: Customers-Main
        transitGateway:
          name: Network-Main-TGW
          account: Network
        routeTableAssociations:
          - Network-Main-Segregated
        routeTablePropagations: 
        #DO NOT PROPOGATE ROUTES, NOT ADDRESSABLE FROM OTHER NETWORKS
           # - Network-Main-Core
           - Network-Main-Shared
        subnets:
          - Customers-MainTgwAttach-A
          - Customers-MainTgwAttach-B
    gatewayEndpoints:
      defaultPolicy: Default
      endpoints:
        - service: s3
        - service: dynamodb
  

    useCentralEndpoints: false
    resolverRules:
```
