### ISSUE TITLE
ORG_ID policy replacement variable for Customizations

### ISSUE THREAD

**Issue by teddevaal** [awslabs/landing-zone-accelerator-on-aws#429]
**Describe the feature you'd like**
When deploying a [CloudFormationStackConfig](https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/latest/classes/_aws_accelerator_config.CloudFormationStackConfig.html) Customization, I would like to have the ability to define `ACCEL_LOOKUP` variables as part of the configuration.

**Additional context**
```
customizations:
  cloudFormationStacks:
    - deploymentTargets:
        organizationalUnits:
          - Root
      description: Creates a Custom CloudFormation stack
      name: AWSAccelerator-Customization-Stack
      regions:
        - *HOME_REGION
      runOrder: 1
      template: customizations/cfn-templates/cfn-template.yaml
      parameters:
        - name: Frequency
          value: '24hours'
        - name: OrganisationId
          value: '${ORG_ID}'
```
