### ISSUE TITLE
Cannot reference TGW peering attachments cross region in the same account

### ISSUE THREAD

**Issue by ssakuh** [awslabs/landing-zone-accelerator-on-aws#44]
**Describe the bug**
You cannot reference TGW peering attachments in TGW route tables using `attachment.transitGatewayPeeringName` if using one Network account and multiple regions.

**To Reproduce**
Deploy the `network-associations` stack using a similar configuration for `network-config.yaml` as below :

```yaml
transitGatewayPeering:
  - name: Network-Main-eu-west-1-Peering
    autoAccept: true
    requester:
      transitGatewayName: Network-Main
      account: Network
      region: *HOME_REGION
      routeTableAssociations: cross-tgw-egress
      tags:
        - key: Name
          value: Network-Main-eu-west-1-Peering
    accepter:
      transitGatewayName: Network-Main-eu-west-1
      account: Network
      region: eu-west-1
      routeTableAssociations: cross-tgw-egress
      autoAccept: true
      applyTags: true

transitGateways:
  - name: Network-Main
    account: Network
    region: *HOME_REGION
    shareTargets:
      organizationalUnits:
        - Development
        - Production
    asn: 65521
    dnsSupport: enable
    vpnEcmpSupport: enable
    defaultRouteTableAssociation: disable
    defaultRouteTablePropagation: disable
    autoAcceptSharingAttachments: enable
    routeTables:
      - name: east-west
        routes:
          - destinationCidrBlock: 0.0.0.0/0
            name: Inspection
            attachment:
              account: Network
              vpcName: Network-Inspection
      - name: ingress
        routes:
          - destinationCidrBlock: 0.0.0.0/0
            name: Inspection
            attachment:
              account: Network
              vpcName: Network-Inspection
      - name: inspection
        routes:
          - destinationCidrBlock: 0.0.0.0/0
            name: Outbound
            attachment:
              account: Network
              vpcName: Outbound
      - name: cross-tgw-egress
        routes:
          - destinationCidrBlock: 10.1.0.0/16
            name: eu-west-1
            attachment:
              transitGatewayPeeringName: Network-Main-eu-west-1-Peering
  - name: Network-Main-eu-west-1
    account: Network
    region: eu-west-1
    shareTargets:
      organizationalUnits:
        - Development
        - Production
    asn: 65522
    dnsSupport: enable
    vpnEcmpSupport: enable
    defaultRouteTableAssociation: disable
    defaultRouteTablePropagation: disable
    autoAcceptSharingAttachments: enable
    routeTables:
      - name: east-west
        routes:
          - destinationCidrBlock: 0.0.0.0/0
            name: Outbound-eu-west-1
            attachment:
              account: Network
              vpcName: Outbound-eu-west-1
      - name: cross-tgw-egress
        routes:
          - destinationCidrBlock: 10.0.0.0/16
            name: us-east-1
            attachment:
              transitGatewayPeeringName: Network-Main-eu-west-1-Peering
```
**Expected behavior**
The solution should reference the TransitGatewayAttachment using a lookup, not the SSM parameter that does not exist in the other region.

This may be related to the `getTgwPeeringAttachmentId` method of `NetworkAssociationsStack`:

[ `landing-zone-accelerator-on-aws/source/packages/@aws-accelerator/accelerator/lib/stacks/network-associations-stack.ts` between lines 2140-2188 ]

```typescript
  private getTgwPeeringAttachmentId(transitGatewayPeeringName: string, tgwItem: TransitGatewayConfig): string {
    const requesterConfig = this.props.networkConfig.getTgwPeeringRequesterAccepterConfig(
      transitGatewayPeeringName,
      'requester',
    );
    const accepterConfig = this.props.networkConfig.getTgwPeeringRequesterAccepterConfig(
      transitGatewayPeeringName,
      'accepter',
    );

    if (!requesterConfig || !accepterConfig) {
      throw new Error(`Transit gateway peering ${transitGatewayPeeringName} not found !!!`);
    }

    // Get TGW attachment ID for requester
    if (this.props.accountsConfig.getAccountId(requesterConfig.account) === cdk.Stack.of(this).account) {
      return cdk.aws_ssm.StringParameter.valueForStringParameter(
        this,
        `/accelerator/network/transitGateways/${tgwItem.name}/peering/${transitGatewayPeeringName}/id`,
      );
    }

    // Get TGW attachment ID for accepter
    if (this.props.accountsConfig.getAccountId(accepterConfig.account) === cdk.Stack.of(this).account) {
      const transitGatewayId = this.transitGateways.get(accepterConfig.transitGatewayName);
      if (!transitGatewayId) {
        throw new Error(`Transit Gateway ${accepterConfig.transitGatewayName} not found`);
      }

      Logger.info(
        `[network-associations-stack] Looking up transit gateway peering attachment id of accepter account ${accepterConfig.account}`,
      );
      return TransitGatewayAttachment.fromLookup(
        this,
        pascalCase(`${accepterConfig.account}${transitGatewayPeeringName}TransitGatewayPeeringAttachment`),
        {
          name: transitGatewayPeeringName,
          owningAccountId: cdk.Stack.of(this).account,
          transitGatewayId,
          type: TransitGatewayAttachmentType.PEERING,
          kmsKey: this.cloudwatchKey,
          logRetentionInDays: this.logRetention,
        },
      ).transitGatewayAttachmentId;
    }

    throw new Error(`Transit Gateway attachment id not found for ${transitGatewayPeeringName}`);
  }
```

**Please complete the following information about the solution:**

- Version: [1.3.0]
- Region: [us-east-1, eu-west-1]
- Was the solution modified from the version published on this repository? no
- If the answer to the previous question was yes, are the changes available on GitHub? N/A
- Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? N/A
- Were there any errors in the CloudWatch Logs? Please see attached log file. [AWSAccelerator-ToolkitProject-network-error.txt](https://github.com/awslabs/landing-zone-accelerator-on-aws/files/10447094/AWSAccelerator-ToolkitProject-network-error.txt)

**Screenshots**
N/A

**Additional context**
N/A
