### ISSUE TITLE
ManagedAD ActiveDirectoryConfigurationInstanceConfig

### ISSUE THREAD

**Issue by teddevaal** [awslabs/landing-zone-accelerator-on-aws#446]
**Describe the bug**
The ManagedAD ActiveDirectoryConfigurationInstanceConfig configuration is tightly coupled with the configuration in [aws-directory-service construct](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/source/packages/%40aws-accelerator/constructs/lib/aws-directory-service/active-directory-configuration.ts#L300-L311). Therefore the solution only works if the userdata contains specific functions that the aws-directory-service construct is expecting (e.g. [New-AWSQuickStartResourceSignal](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/reference/sample-configurations/lza-sample-config/ad-config-scripts/AWSQuickStart.psm1#L45-L86)).

**To Reproduce**
```
   activeDirectoryConfigurationInstance:
     instanceType: t3.large
     vpcName: MyVpc
     subnetName: subnet
     imagePath: /aws/service/ami-windows-latest/Windows_Server-2016-English-Full-Base
     securityGroupInboundSources:
       - 10.0.0.0/16
     instanceRole: EC2-Default-SSM-AD-Role
     enableTerminationProtection: false
     userDataScripts: []
```

**Expected behavior**
When the AD Configuration Instance is created, I expect the instance to provision successfully regardless of what user data scripts are provided. I also expect the cfn-init logs to be accessible in CloudWatch to make debugging easier.

**Please complete the following information about the solution:**

- [-] Version: [e.g. v1.6.1]
- [-] Region: [e.g. ap-southeast-2]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [-] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
cfn-init log on the windows machine
<img width="1007" alt="Screenshot 2024-05-07 at 12 07 55 pm" src="https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/2188401/d91184bf-514f-4086-bfe5-32968979e7cc">
