### ISSUE TITLE
Duplicate CloudTrail Management Events

### ISSUE THREAD

**Issue by rjbaker** [awslabs/landing-zone-accelerator-on-aws#449]
**Describe the bug**

When deploying LZA into a management account with CloudTrail organization trail enabled, and both `s3DataEvents` & `lambdaDataEvents` enabled we would expect a single Management event selector to be created and two data event selectors.

Instead, three management event selectors are created, this produces multiple copies of CloudTrail management events, incurring additional and significant CloudTrail event data costs.

This appears to be caused by calls to `organizationsTrail.addEventSelector` e.g. https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/source/packages/%40aws-accelerator/accelerator/lib/stacks/organizations-stack.ts#L824 do not pass any [options](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudtrail.AddEventSelectorOptions.html). As a result, the `includeManagementEvents` option defaults to `true` for each additional event selector.

![Screenshot 2024-05-10 at 13 40 24](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/783245/09b8a693-bbb8-4418-8dd9-dbc8bc189144)

**To Reproduce**

 - (Re)Deploy or upgrade LZA to latest version.
 - Use following logging settings in `global-config.yaml`:
 ```
logging:
  account: LogArchive
  cloudtrail:
    enable: true
    organizationTrail: true
    organizationTrailSettings:
      multiRegionTrail: false
      globalServiceEvents: true
      managementEvents: true
      s3DataEvents: true
      lambdaDataEvents: true
      sendToCloudWatchLogs: true
      apiErrorRateInsight: false
      apiCallRateInsight: false
```
- Sign into organisation management account console
- Navigate to: `CloudTrail -> Trails`
- Select: `AWSAccelerator-Organizations-CloudTrail`

**Expected behavior**

Within the `AWSAccelerator-Organizations-CloudTrail` trail we would expect a single management event selector to be created and two data event selectors. Management events should be recorded once within this trail.

**Please complete the following information about the solution:**

- [ ] Version: [e.g. v1.5.1]

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [ ] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
