### ISSUE TITLE
Add support for SecurityHub automations

### ISSUE THREAD

**Issue by Thomas-McKanna** [awslabs/landing-zone-accelerator-on-aws#450]
LZA provides support for enabling SecurityHub standards and suppressing certain controls. It would be very nice if LZA could also be used to define SecurityHub Automation rules as well, especially since these rules are region specific and its tedious to try to manually keep rules for multiple regions consistent. According to [official docs](https://docs.aws.amazon.com/securityhub/latest/userguide/automation-rules.html#:~:text=Rule%20order,same%20finding%20or%20finding%20field.):

> An automation rule applies only in the AWS Region in which it's created. To apply a rule in multiple Regions, the delegated administrator must create the rule in each Region. This can be done through the Security Hub console, Security Hub API, or [AWS CloudFormation](https://docs.aws.amazon.com/securityhub/latest/userguide/creating-resources-with-cloudformation.html). You can also use a [multi-Region deployment script](https://github.com/awslabs/aws-securityhub-multiaccount-scripts/blob/master/automation_rules).

Automation rules could be defined like:

```yaml
centralSecurityServices:
  securityHub:
    automationRules:
      - name: DoXYZ
         description: xyz
         enabled: true
         criteria:
           - key: aaa
             operator: Equals
             values:
               - val1
               - val2
         automatedAction:
           workflowStatus: SUPPRESSED
           note: xyz
```

The order of the rules list would determine rule order in SecurityHub, and the rules would be replicated to all regions enabled in the LZA config.
