### ISSUE TITLE
Add support for AWS Resource Tagging Standard for SecurityHubStandardConfig class

### ISSUE THREAD

**Issue by gavin-sr** [awslabs/landing-zone-accelerator-on-aws#453]
````yaml
securityHub:
    enable: true
    regionAggregation: true
    excludeRegions: []
    standards:
      - name: AWS Resource Tagging Standard v1.0.0
        # https://docs.aws.amazon.com/securityhub/latest/userguide/standards-tagging.html#
        deploymentTargets:
          organizationalUnits:
            - Root
        enable: false
        controlsToDisable: []
````

https://docs.aws.amazon.com/securityhub/latest/userguide/standards-tagging.html#

**Comment by bgshacklett** [comment]
Why is this encoded into the types, rather than validating against the SecurityHub API anyway? Documentation indicates that valid values can be retrieved using `aws securityhub describe-standards`

**Comment by fdjahnke** [comment]
Hello @gavin-sr, thank you for filing this feature request with the Landing Zone Accelerator team!

This is now supported. As of **v1.15.0** (and in the latest release, **v1.16.1**), the Security Hub `standards[].name` field accepts any valid Security Hub standard name, so you can enable the AWS Resource Tagging Standard directly:

```yaml
securityHub:
  enable: true
  standards:
    - name: AWS Resource Tagging Standard v1.0.0
      deploymentTargets:
        organizationalUnits:
          - Root
      enable: true
      controlsToDisable: []
```

@bgshacklett, to your point: the standard name is no longer restricted to a hard-coded set. The field now accepts any string so newly released standards can be enabled without a code change.

Please upgrade to v1.15.0 or later. Closing this issue, please feel free to follow up if you have any questions on this issue just make sure to ping me so that I'll see it.
