### ISSUE TITLE
controlsToDisable does not disable per region

### ISSUE THREAD

**Issue by mongrol** [awslabs/landing-zone-accelerator-on-aws#459]
**Describe the bug**
Security Hub docco recommends disabling SH controls that are assessing global services to reduce noise and cost.
https://docs.aws.amazon.com/securityhub/latest/userguide/controls-to-disable.html

LZA, which doesn't support SH Central Configuration, does not appear to provide a way to disable specific controls and deploy that configuration to a region.

**To Reproduce**
I've attempted this in a couple of ways but it appears I'm assuming I would need to "deploy" the standard to specific regions, one with controlsToDisable populated.

```
standards: 
    - name: AWS Foundational Security Best Practices v1.0.0
      deploymentTargets:
      regions:
        - ap-southeast-2
      enable: true
      controlsToDisable: []
    - name: AWS Foundational Security Best Practices v1.0.0
      deploymentTargets:
      regions:
        - us-east-1
      enable: true
      controlsToDisable:
        - IAM.4
        - IAM.5
```

**Expected behavior**
With the config above I expect IAM.4 and IAM.5 to be disabled in us-east-1 only. The result of the above config is the controls are disabled in both regions.

**Please complete the following information about the solution:**

- [x] Version: 1.6.1

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [x] Region: ap-southeast-2, us-east-1
- [x] Was the solution modified from the version published on this repository? No
- [x] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes
- [x] Were there any errors in the CloudWatch Logs?

**Additional context**
Both SH lambda logs showed the correct entries for disabling the controls. Albiet in both regions.

**Comment by bo1984** [comment]
Hi @mongrol ! Thank you for utilizing the Landing Zone Accelerator on AWS solution. I have filed a feature request to help track exceptions around the global services (IAM, Route53, etc..) so that these resources aren't duplicated across multi-region configurations. If you have any questions or concerns in the meantime, please do not hesitate to ask.

**Comment by fdjahnke** [comment]
Hello @mongrol, thank you for filing an issue with the Landing Zone Accelerator team!

This has been resolved. As of **v1.16.0** (and in the latest release, **v1.16.1**), each Security Hub standard entry accepts its own `deploymentTargets`, so `controlsToDisable` is applied only within that standard's scope rather than across all regions. For your example, you can define two entries for the same standard scoped to different targets and disable controls in one without affecting the other:

```yaml
securityHub:
  enable: true
  standards:
    - name: AWS Foundational Security Best Practices v1.0.0
      deploymentTargets:
        organizationalUnits:
          - Root
        excludedRegions:
          - us-east-1
      enable: true
      controlsToDisable: []
    - name: AWS Foundational Security Best Practices v1.0.0
      deploymentTargets:
        organizationalUnits:
          - Root
        excludedRegions:
          - ap-southeast-2
      enable: true
      controlsToDisable:
        - IAM.4
        - IAM.5
```

Please upgrade to v1.16.0 or later. Closing this issue, please feel free to follow up if you have any questions on this issue just make sure to ping me so that I'll see it.
