### ISSUE TITLE
IAM Identity Center (ICC) (LZA v1.7.0+) fails to successfully create Management Account assignments - Failure message mentions missing iam:CreateSAMLProvider permission on the IIC Assignment Lambda IAM Role 

### ISSUE THREAD

**Issue by CirrusHQ-Pipeline-User** [awslabs/landing-zone-accelerator-on-aws#496]
Please provide the following information:
-->

**Describe the bug**

_**(NOTE WE HAVE COVERED POTENTIALLY SENSITIVE INFO WHERE APPLICABLE WITH X's)**_

We have an IAM Identity Center Instance which we've configured an external IdP for and is controlled by LZA. We deployed permission sets and assignments to many OUs and accounts, including the Management Account via LZA, which went through successfully without issue.

However, we noticed that all assignments except for the Management Account were successfully created. I investigated the CloudTrail logs for the `CreateAccountAssignment` API call and found one showing that the assignment for the Management Account was attempted and was recorded as `IN_PROGRESS`. Using the following command:

`aws sso-admin describe-account-assignment-creation-status --account-assignment-creation-request-id xxxxxxxxx --instance-arn arn:aws:sso:::instance/ssoins-xxxxxxxxx`

I was able to discover the error message, which I will paste below:

`"FailureReason": "Received a 403 status error: Access denied by IAM. Please check your policy, or wait for role propagation to complete. IAM Error: User: arn:aws:sts::xxx:assumed-role/xxxx-IdentityCenterStac-CustomIdentityCenterAssig-xxx/xxx-IdentityCenterStac-CustomIdentityCenterAssi-xxx is not authorized to perform: iam:CreateSAMLProvider on resource: arn:aws:iam::xxx:saml-provider/AWSSSO_xxx_DO_NOT_DELETE because no identity-based policy allows the iam:CreateSAMLProvider action (Service: AmazonIdentityManagement; Status Code: 403; Error Code: AccessDenied; Request ID: xxx; Proxy: null)"`

This is a surprising error, and the fact it didn't appear in the other assignments shows it's a Management Account assignment-specific issue. @erwaxler mentioned on a separate but linked thread: https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/215

https://docs.aws.amazon.com/singlesignon/latest/userguide/iam-auth-access-using-id-policies.html#policyexamplemanageconnecteddirectory

However, the permission in the error code (iam:CreateSAMLProvider) is not mentioned on that page.

Since the IAM Role is managed by LZA, we are unsure how to proceed. This seems like it will affect other customers, with an unclear path on how to proceed except for manually configuring the assignment for the Management Account, which defeats the purpose of the feature being added in v1.7.0, allowing it to be assigned by LZA.

**To Reproduce**

1. Enable IAM Identity Centre
2. Configure an external IdP (such as AzureAD)
3. Deploy IAM Identity Centre configurations, such as permission sets which are assigned, by LZA, to the Management Account
4. Use CloudTrail to investigate the request ID of the failed assignment attempt to the Management Account
5. Use the aws sso-admin describe-account-assignment-creation-status to check for failure codes of the failed assignment attempt to the Management Account

**Expected behavior**
Assignments to the Management Account are successful through LZA

**Please complete the following information about the solution:**

- [ ] Version: v1.7.1
- [ ] Region: eu-west-2
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? N/a
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? N/a
- [ ] Were there any errors in the CloudWatch Logs? Yes and error code was pasted above

**Screenshots**
N/a

**Additional context**
Linked issue is https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/215

**Comment by erwaxler** [comment]
Hi @CirrusHQ-Pipeline-User , thanks for creating this issue. I've created an item in the team's backlog to track this work, I will update this ticket accordingly. Thank you for your support of the Landing Zone Accelerator!

**Comment by hemanth-m19** [comment]
Hello! @CirrusHQ-Pipeline-User  and @erwaxler, I wanted to share some insights on our configuration that might help in diagnosing this issue effectively.

We've recently updated our LZA version to the latest (v1.7.1). Additionally, we have our IAM Identity Centre configured with an external identity provider (Okta) as well. This version update has successfully resolved previous issues, and as of now, we haven't encountered the problem you mentioned [here ](https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/496)

Below is the sample config I tested just then to double check:

```
identityCenter:
  name: IdentityCenter
  delegatedAdminAccount: Audit
  identityCenterPermissionSets:
    - name: OrgViewOnlyAccess
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
      sessionDuration: 60
    
    - name: OrgReadOnlyAccess
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/ReadOnlyAccess
        inlinePolicy: iam-policies/OrgReadOnlyAccess-inline-policy.json
      sessionDuration: 60

  identityCenterAssignments:
  - name: Assignment1
    permissionSetName: OrgViewOnlyAccess
    principals:
      - type: GROUP
        name: OrgAWSViewers
    deploymentTargets:
      organizationalUnits:
        - Root # Sucessfully assigned to all accounts

  - name: Assignment2
    permissionSetName: OrgReadOnlyAccess
    principals:
      - type: GROUP
        name: OrgAWSReaders
    deploymentTargets:
      accounts:
        - Management # Sucessfully assigned to Management account
```
