### ISSUE TITLE
CDK Fails to deploy Customizations using Global Replacements Syntax (v1.7.1)

### ISSUE THREAD

**Issue by joshuahigginson1** [awslabs/landing-zone-accelerator-on-aws#503]
**Describe the bug**
It has been observed that when running a build of the Landing Zone Accelerator which uses Global Replacements Syntax in v1.7.1 of the Landing Zone Accelerator,

During the customizations stage, when using a Global Replacement Variable in the NAME value for a CloudFormation Stack, i.e:

```yaml
    - name: "{{ CustomAcceleratorPrefix }}-ReadOnlyRoleCreation"
      description: "This CloudFormation template is used to create the Read Only role and policy for the infrastructure testers. It must be assumed from an IAM PermissionSet."
      template: ./cloudformation-templates/read-only-role-creation-cfn-template.yaml
      terminationProtection: false
      runOrder: 1
```

The Landing Zone Accelerator solution will correctly synthesise the stack:

```
✅  AWSAccelerator-CustomizationsStack-11111111-eu-west-2 (no changes)
--
194 |  
195 | ✨  Deployment time: 1.06s
196 |  
197 | Stack ARN:
198 | arn:aws:cloudformation:eu-west-2:11111111:stack/AWSAccelerator-CustomizationsStack-11111111-eu-west-2/<Changeset ID>
199 |  
200 | ✨  Total time: 1.2s
```

But the CDK will fail to deploy it after synthesis:

```
2024-07-01 08:05:39.745 \| error \| toolkit \| No stacks match the name(s) {{CustomAcceleratorPrefix}}-ReadOnlyRoleCreation-11111111-eu-west-2
--
1265 | Deployment failed
```

**To Reproduce**
- Create a new Customization using the global replacement syntax above.
- Run the pipeline with v1.7.1.

**Expected behavior**

**Please complete the following information about the solution:**

- [x ] Version

v1.71

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [ x] Region: [e.g. us-east-1]

Observed in All Regions

- [x] Was the solution modified from the version published on this repository?

No

- [x] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas]
(https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?

Yes

- [x] Were there any errors in the CloudWatch Logs?

Yes, Shown

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
