### ISSUE TITLE
Pseudo paramters in config files

### ISSUE THREAD

**Issue by LUKEALDRED** [awslabs/landing-zone-accelerator-on-aws#511]
**Is your feature request related to a problem? Please describe.**
lza-sample-config includes an AWS Config rule called **accelerator-s3-bucket-policy-grantee-check** in **security-config.yaml**
https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/reference/sample-configurations/lza-sample-config/security-config.yaml

AWS documentation describes this rule as follows: "Checks that the access granted by the Amazon S3 bucket is restricted by any of the AWS principals, federated users, service principals, IP addresses, or VPCs that you provide."
https://docs.aws.amazon.com/config/latest/developerguide/s3-bucket-policy-grantee-check.html

There are two elements at play here:
1. The bucket policy that specifies which principals are granted access to the S3 bucket
2. A parameter that is passed to the config rule, such as awsPrincipals

As this config rule is applied to Root the config rule is created in all accounts.

```
- deploymentTargets:
    organizationalUnits:
      - Root
```

If I explicitly pass an AWS account ID in the awsPrincipals parameter then this will match for one account but not others. I could pass all of the AWS account IDs in the awsPrincipals parameter but that would become unwieldly and potentially not very secure. Also I do not see a way to dynamically specify an AWS account ID using something like a pseudo parameter like you would with CloudFormation.

**Describe the feature you'd like**
Can we have the option of specifying a variable or pseudo parameter in the parameters for the config rule in security-config.yaml?
For example:
```
- name: accelerator-s3-bucket-policy-grantee-check
  inputParameters:
    awsPrincipals: ${AWS::AccountID}
  complianceResourceTypes:
    - AWS::S3::Bucket
  identifier: S3_BUCKET_POLICY_GRANTEE_CHECK
```
