### ISSUE TITLE
Transit Gateway: setting "defaultRouteTablePropagation: enable" seems to be not working.

### ISSUE THREAD

**Issue by yaolu-dtp** [awslabs/landing-zone-accelerator-on-aws#522]
**Describe the bug**

Set `defaultRouteTablePropagation: enable` appears to be not working, as there is no way to set ` propagationDefaultRouteTableId` according to doco https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_TransitGatewayOptions.html

This is a follow up from https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/481, where IPAM is utilized for VpcTemplates.

**To Reproduce**
Steps to reproduce the behavior.

```
transitGateways:
  - name: Network-Main
    account: SharedNetworkService
    region: *HOME_REGION
    shareTargets:
      organizationalUnits:
        - Infrastructure
    asn: 65521
    dnsSupport: enable
    vpnEcmpSupport: enable
    defaultRouteTableAssociation: disable
    defaultRouteTablePropagation: enable   <=================== This one
    autoAcceptSharingAttachments: enable
    routeTables:
      - name: Network-Main-Core
        routes: # Add other VPCs as well.
        - destinationCidrBlock: 0.0.0.0/0
          attachment:
            vpcName: Network-Centralized-Egress
            account: SharedNetworkService
      - name: Network-Main-Inspection
        routes:
        - destinationCidrBlock: 0.0.0.0/0
          attachment:
            vpcName: Network-Inspection
            account: SharedNetworkService
      - name: Network-Main-Segregated
        routes: []
      - name: Network-Main-Shared
        routes: []
      - name: Network-Main-Standalone
        routes: []
```

It causes error in CFN
```
AWSAccelerator-NetworkPrepStack-xxxxxxxxxxxxxxx failed: Error: The stack named AWSAccelerator-NetworkPrepStack-xxxxxxxxxxxxxxx failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "enable DefaultRouteTablePropagation conflicts with PropagationDefaultRouteTableId null (Service: Ec2, Status Code: 400, Request ID: xxxxxxxxxxxxxxx)" (RequestToken: xxxxxxxxxxxxxxx, HandlerErrorCode: GeneralServiceException)
```

Also,

I don't think the snapshot here will actually work either
https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/76117a978937ea8c7a5d1e58e2c3e2b2584ec0ba/source/packages/%40aws-accelerator/constructs/test/aws-ec2/__snapshots__/transit-gateway.test.ts.snap#L301

PropagationDefaultRouteTableId is not included in the snapshot. 

**Expected behavior**

defaultRouteTablePropagation should be functioning while allowing to set defaultRouteTablePropagation

**Please complete the following information about the solution:**

- [x] Version: [Tested in v1.8.0, should be the same for all versions]

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [x] Region: [ap-southeast-2]
- [x] Was the solution modified from the version published on this repository? - No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
