### ISSUE TITLE
Possibility to create IAM Identity Center (IIC) users and groups, not just assignments?

### ISSUE THREAD

**Issue by stefan-matic** [awslabs/landing-zone-accelerator-on-aws#533]
**Is your feature request related to a problem? Please describe.**
To my understanding, in order to create Identity Center assignments for users and group, the user/group must exist first?
I don't see any way to create IIC users and groups through the LZA, or am I missing something?

**Describe the feature you'd like**
Would it be possible to create and maintain the list of users and group within the identityCenter block?

**Additional context**
`iam-config.yaml`:

```
identityCenter:
  name: cloud-foundation-sso
  delegatedAdminAccount: Audit
  identityCenterPermissionSets:
    - name: CustomPermissionSet-Admin
      policies:
        awsManaged:
          - AdministratorAccess
    - name: CustomPermissionSet-Test
      policies:
         awsManaged:
           - AdministratorAccess
      sessionDuration: 60
  identityCenterAssignments:
    - name: AdminAccess
      permissionSetName: CustomPermissionSet-Admin
      principals:
        - type: USER
          name: manually-created-user@example.com
        - type: GROUP
          name: Administrators
      deploymentTargets:
        organizationalUnits:
          - Root
    - name: TestAccess
      permissionSetName: CustomPermissionSet-Test
      principals:
        - type: USER
          name: non-existing-user@example.com
      deploymentTargets:
        accounts:
          - SharedServices
  ```
  
  The first assignment creates the assignment for the user (because I manually created it in IIC) but not the group (not created manually)
  The second assignment creates no assignments (user not created manually)
