### ISSUE TITLE
Unable to configure deploymentTargets for securityHub without CIS AWS Foundations Benchmark v1.2.0 being enabled

### ISSUE THREAD

**Issue by gr-georgeshort** [awslabs/landing-zone-accelerator-on-aws#537]
**Describe the bug**
When attempting to configure securityHub with deploymentTargets, we receive the error:
'securityHub standard (CIS AWS Foundations Benchmark v1.2.0) "deploymentTargets" is required when "deploymentTargets" for securityHub is defined'

This is not mentioned within the documentation for LZA.

**To Reproduce**
Something like:
```
securityHub:
  enable: true
  regionAggregation: true
  excludeRegions: []
  deploymentTargets:
    organizationalUnits:
      - Root
  standards:
    - name: AWS Foundational Security Best Practices v1.0.0
      deploymentTargets:
      organizationalUnits:
        -  Root
      enable: true
      controlsToDisable:
        # Refer to the document for the controls
        # https://docs.aws.amazon.com/securityhub/latest/userguide/fsbp-standard.html
        - Control1
        - Control2
  logging:
    cloudWatch:
      enable: true
      logLevel: MEDIUM
```

**Expected behavior**
Security Hub to be enabled in provided OUs under deployment targets without the requirement for CIS standard to be enabled.

**Please complete the following information about the solution:**

- [ ] Version: v1.9.1
- [ ] Region: eu-west-1

**Comment by erwaxler** [comment]
Hi @gr-georgeshort , thanks for reaching out to the team. The indentation of your configuration appears to be incorrect, please try adding an extra indentation to `organizationalUnits` and try again to see if that resolves your issue:

```
    deploymentTargets:
      organizationalUnits:
        -  Root
```

**Comment by gr-georgeshort** [comment]
Hi @erwaxler, 
Sorry I made up the example from the github pages as do not have access to the real world example atm. Our indentation is correct 👍

**Comment by erwaxler** [comment]
@gr-georgeshort thanks for confirming! I'll create an issue in the team's backlog to update our documentation and fix the indentation. I'll add that the `deploymentTargets` property on the top-level `securityHub` configuration is optional - if you are targeting the entire AWS Organization through `Root`, there's no need to specify `deploymentTargets` there.

**Comment by gr-georgeshort** [comment]
@erwaxler Sorry should have waited to provide a real world example. We are however not targeting Root, we are targeting specific OUs as we do not want to currently enable securityHub / best practices standard across the whole Org. 

Our end goal is to have a subnet of OUs with security hub configured and only the AWS best practices standard enabled. When trying to implement this is when we received the error. I will now test configuring deploymentTarget within the securityHub configuration and remove the deploymentTargets from best practices standard if you believe this will work?

**Comment by gr-georgeshort** [comment]
Hey @erwaxler, I believe the issue we originally had was that CIS was listed but with enabled: false so your answer above now corresponds to this validation.
We have removed the CIS reference completely now, the pipeline did not fail but it didn't actually disable the standard within Security Hub. We have manually disabled it, rerun LZA and it hasn't re-enabled.
Real world example now:
```
  securityHub:
    enable: true
    regionAggregation: true
    autoEnableOrgMembers: false
    deploymentTargets:
      organizationalUnits:
        - Security
        - Infrastructure
        - Sandbox
    standards:
      - name: AWS Foundational Security Best Practices v1.0.0
        deploymentTargets:
          organizationalUnits:
            - Security
            - Infrastructure
            - Sandbox
        enable: true
```
