### ISSUE TITLE
Tagging policy does not detach from organization if it is removed from organizationalUnits

### ISSUE THREAD

**Issue by yaolu-dtp** [awslabs/landing-zone-accelerator-on-aws#543]
**Describe the bug**

Tagging policy does not detach from organization if it is removed from organizationalUnits

e.g.

before
```
taggingPolicies:
  - name: TagPolicy
    description: Organization Tagging Policy
    policy: tagging-policies/org-tag-policy.json
    deploymentTargets:
      organizationalUnits:
        - root
```

after
```
taggingPolicies:
  - name: TagPolicy
    description: Organization Tagging Policy
    policy: tagging-policies/org-tag-policy.json
    deploymentTargets:
      organizationalUnits:
        - Team1
        - Infrastructure
```

And the tagging policy is still attached to root
![Screenshot 2024-08-22 at 12 08 07 PM](https://github.com/user-attachments/assets/850a13b3-b5f7-4296-af67-ed0ff370b804)

**To Reproduce**
As described above

**Expected behavior**
Tagging policy no longer attached to root OU.

**Please complete the following information about the solution:**

- [x] Version: [v1.9.1]

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [x] Region: [ap-southeast-1]
- [x] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
