### ISSUE TITLE
Extend the IBaseAccountConfig to support tagging an account on creation

### ISSUE THREAD

**Issue by m-franke-tqgg** [awslabs/landing-zone-accelerator-on-aws#583]
**Is your feature request related to a problem? Please describe.**
During the account creation process, we would like to be able to define a set of tags being applied to our new accounts. We use them for Cost Management and other control mechanisms like for example network layout or TransitGatewayAttachments.

**Describe the feature you'd like**
I would like to extend the IBaseAccountConfig interface to contain to have a "tags" field, so we have a single source of truth about the account and it's configuration.

For example like so:
```yaml
accounts:
- name: Workload01
  description: Workload account 01
  email: example-email+workload01@example.com
  organizationalUnit: Workloads
  warm: true
  tags:
    Environment: 'Production'
    Department: 'Procurement'
    Owner: 'John Doe'
    TGWAttachment: True
    NetworkLayout: 'Single'
```

**Additional context**

A possible solution could be to either create another `extends` version of the IBaseAccountConfig or to extend the IBaseAccountConfig like so:
```typescript
export interface IBaseAccountConfig {
  name: t.NonEmptyNoSpaceString;
  description?: t.NonEmptyString;
  email: t.EmailAddress;
  organizationalUnit?: t.NonEmptyString;
  tags?: t.ITag[];
}
```

And of course the necessary code to tag the newly created account in the Organization.
