### ISSUE TITLE
GuardDuty - Specify S3 Prefix for GuardDuty logs

### ISSUE THREAD

**Issue by thetechbender** [awslabs/landing-zone-accelerator-on-aws#59]
**Is your feature request related to a problem? Please describe.**
Right now, GuardDuty logs are exported to the central logging bucket in the log archive account #14. 

[It is possible to store GuardDuty logs with a custom S3 Object Prefix as part of the destination ARN](https://docs.aws.amazon.com/guardduty/latest/APIReference/API_DestinationProperties.html#guardduty-Type-DestinationProperties-destinationArn). In the current implementation of LZA, GuardDuty logs are **not** stored with a custom S3 Object prefix.

The LZA configuration bundles the GuardDuty logs with other `AWSLogs` such as Config Logs. The Logs are collectively stored under `AWSLogs/{AWS::AccountId}`. See this screenshot where GuardDuty and Config logs are stored under the Account ID.

![image](https://user-images.githubusercontent.com/24513457/218191225-716f8f97-2570-446a-a0cb-eded939f22d1.png)

This limits the capability to use S3 event notifications to send notifications when GuardDuty events are written to the S3 Bucket. We use S3 event notifications integration with SQS as part of a solution to do log processing and analytics on GuardDuty logs. [S3 event notifications do not support wildcards in prefix filters](https://repost.aws/knowledge-center/s3-event-notification-filter-wildcard), so we cannot set up a single S3 event notification filter for all GuardDuty Logs. Instead, we would have to create a new S3 event notification with a filter for every new Account ID in the landing zone, which adds additional complexity and has scaling issues. 

**Describe the feature you'd like**
Allow the capability to specify S3 Prefix in the `exportConfiguration` for `guardduty` in `security-config.yml`. 
```
guardduty:
    enable: true
    excludeRegions: []
    s3Protection:
      enable: true
      excludeRegions: []
    exportConfiguration:
      enable: true
      overrideExisting: true
      destinationType: S3
      exportFrequency: FIFTEEN_MINUTES
```
