### ISSUE TITLE
Service Catalog propagate-portfolio-associations via permission set not working since 1.7.0

### ISSUE THREAD

**Issue by vanja-zecevic** [awslabs/landing-zone-accelerator-on-aws#600]
**Describe the bug**
Service Catalog portfolio associations that are defined in LZA and are based on permission set, are not propagated to target accounts correctly. In the target account, rather than providing access to the role that is associated with the intended permission set, LZA will grant access to a random role.

**To Reproduce**
Add a portfolio with a product to serviceCatalogPortfolios in customizations-config.yaml and associate it with a permission set:
```
  serviceCatalogPortfolios:
    - name: test-portfolio
      provider: LZA
      account: Management
      regions:
        - *HOME_REGION
      shareTargets:
        accounts:
          - test-account
      portfolioAssociations:
        - type: PermissionSet
          name: target-permission-set
          propagateAssociation: true
      products:
        - name: test-product
          description: this is a test product
          distributor: LZA
          versions:
            - name: v1
              template: servicecatalog-templates/product-template.yaml
              deprecated: false
```

**Expected behavior**
Would expect to see the SC portfolio and product appear in 'test-account' and for the arn of the role associated with 'target-permission-set' to appear under 'access'. In reality, access is granted to a random role that may not be associated with the permission set.

**Please complete the following information about the solution:**

- [ ] Version: 1.8.1 (this bug will affect all version from 1.7.0 - 1.9.2)
- [ ] Region: ap-southeast-2
- [ ] Was the solution modified from the version published on this repository? No
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes, it is not related to service quotas.
- [ ] Were there any errors in the CloudWatch Logs? Not errors, however there is information that illustrates the problem in CW logs.

**Additional context**
This bug was introduced in the following commit.
[https://github.com/awslabs/landing-zone-accelerator-on-aws/commit/d2b8920b5d25767255327b0e7fc14b3687e83431](url)
In file source/packages/@aws-accelerator/constructs/lib/aws-servicecatalog/propagate-portfolio-associations/index.ts
The function getPermissionSetRoleArn is supposed to return the arn of the role that corresponds to a specified permission set name. This was the previously working code
```
 const iamRoleList = await getIamRoleList(iamClient);
  const roleArn = iamRoleList.find(role => {
    const regex = new RegExp(`AWSReservedSSO_${permissionSetName}_([0-9a-fA-F]{16})`);
    const match = regex.test(role.RoleName);
    console.log(`Test ${role} for pattern ${regex} result: ${match}`);
    return match;
  })?.Arn;
```
The function that is passed to the find method returns true when it finds a regex match. In the new code,
```
  const regex = new RegExp(`AWSReservedSSO_${permissionSetName}_([0-9a-fA-F]{16})`);
  const roles = await getIamRoleList(iamClient, ssoRolePrefix);
  const foundRole = roles.find(role => {
    const match = regex.test(role.RoleName!);
    console.log(`Test ${JSON.stringify(role)} for pattern ${regex} result: ${match}`);
    return role;
  });
  const roleArn = foundRole?.Arn ?? undefined;
```
the function that is passed to the find method returns 'role' rather than 'match' which seems to be a mistake. This function should return a boolean value however because it returns 'role' object, foundRole ends up being a random role that doesn't necessarily match the regex. Would need to double check, but I believe the fix should be as simple as returning 'match' instead of 'role'.
