### ISSUE TITLE
bug: Using StringList replacement doesn't properly work/validate

### ISSUE THREAD

**Issue by mbevc1** [awslabs/landing-zone-accelerator-on-aws#607]
**Describe the bug**
When using a `StringList` from replacements in Array field in other configs validation succeeds, but `Prepare` fails in the pipeline with:
```
* /reports/budgets/0/notifications/0/recipients/0 => must be string
* /reports/budgets/0/notifications/1/recipients/0 => must be string
* /reports/budgets/0/notifications/2/recipients/0 => must be string
* /reports/budgets/0/notifications/3/recipients/0 => must be string
```

**To Reproduce**
Create a variable in `replacements-config.yaml`:
```
- key: BudgetEmails
    type: StringList
    value: [ email1@domain.com, email2@domain.com ]
```

then use it in `global-config.yaml`:
```
reports:
  budgets:
    - deploymentTargets:
        accounts:
          - Management
      name: accel-budget
      timeUnit: MONTHLY
      type: COST
      amount: 100
      includeUpfront: true
      includeTax: true
      includeSupport: true
      includeSubscription: true
      includeRecurring: true
      includeOtherSubscription: true
      includeDiscount: true
      includeCredit: false
      includeRefund: false
      useBlended: false
      useAmortized: false
      unit: USD
      notifications:
        - type: FORECASTED
          thresholdType: PERCENTAGE
          threshold: 100
          comparisonOperator: GREATER_THAN
          subscriptionType: EMAIL
          recipients: [ {{ BudgetEmails }} ]
```

**Expected behavior**
Validation succeeds and so should the pipeline.

**Please complete the following information about the solution:**

- [x] Version: [v1.9.2]

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [x] Region: [e.g. eu-west-1]
- [x] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [x] Were there any errors in the CloudWatch Logs? No

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
