### ISSUE TITLE
VPC is exhausted of address space 

### ISSUE THREAD

**Issue by JimToupet** [awslabs/landing-zone-accelerator-on-aws#613]
**Describe the bug**
We want to add a VPC of /27 with 2 subnets of /28 at the far end of our AWS CIDR range. We use IPAM pools. 

In AWS Console I can see that the VPC is created and the first /28 associate to Subnet A is allocated. But failed with this error when it's time to create the second Subnet B : **Error while calculating next subnet CIDR: Error: VPC is exhausted of address space. Cannot allocate a CIDR with /28 prefix.**

_Please note that we have other VPC that uses other subnets and still have gap between the last used and the one we try to create. For a management consistency purpose we when to uses "small" subnets at the end of our AWS supernet._ 

**To Reproduce**
Create a IPAM Pool, named `NewPool`, with this subnet `10.193.255.224/27` within the AWS Range CIDR of `10.192.0.0/15`
Create a VPC and associate this pool in the ipamAllocations section :  ipamPoolName `NewPool` with netmaskLength of 27
Add two /28 subnets with ipamAllocation : ipamPoolName `NewPool`

**Expected behavior**
Both /28 subnets to be allocate in the /27 Pool. 

**Please complete the following information about the solution:**

- [x] Version: v1.9.2
- [x] Region: ca-central-1
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by bo1984** [comment]
Hi Jim!

Thank you for reaching out. I'd like to get your IPAM Configuration posted in this ticket if you don't mind. I'm assuming your configuration looks similar to the following:

```
ipams:
    - name: accelerator-ipam
      region: *HOME_REGION
      description: Accelerator IPAM
      operatingRegions:
        - *HOME_REGION
      pools:
        - name: NewPool
          description: Base IPAM Pool
          provisionedCidrs:
            - 10.192.0.0/15
        - name: us-east-1-region-pool
          description: IPAM Pool
          locale: *HOME_REGION
          provisionedCidrs:
            - 10.192.0.0/15
          sourceIpamPool: NewPool
          shareTargets:
            organizationalUnits:
              - Root
          autoImport: true

vpcs:
  - name: Sample
    account: Network
    region: us-east-1
    ipamAllocations:
      - ipamPoolName: us-east-1-region-pool
        netmaskLength: 27
    enableDnsHostnames: true
    enableDnsSupport: true
    instanceTenancy: default
    routeTables:
       - name: RouteTableA
          routes: []
       - name: RouteTableB
          routes: []
    subnets: 
      - name: accelerator-ipam-subnet-a
        availabilityZone: a
        routeTable: RouteTableA
        ipamAllocation:
          ipamPoolName: accelerator-regional-pool
          netmaskLength: 28
     - name: accelerator-ipam-subnet-b
        availabilityZone: b
        routeTable: RouteTableB
        ipamAllocation:
          ipamPoolName: accelerator-regional-pool
          netmaskLength: 28
    natGateways: []
    transitGatewayAttachments: []
    tags: []
```

**Comment by JimToupet** [comment]
Thank you Bo for the return.  Below the IPAM and VPC config.  For readability I omit all workloads pool but they are all /18 starting at the beginning. 

Also, please note that I simplify the VPC configuration while our VPC serve a specific needs linked to our DX that I don't think have anything to do with the current issue. 

```
ipams:
    - name: accelerator-ipam
      region: *HOME_REGION
      description: Accelerator IPAM
      operatingRegions:
        - *HOME_REGION
      pools:
        - name: ca-central-Pool
          description: Pool for ca-central-1
          locale: *HOME_REGION
          provisionedCidrs:
            - 10.192.0.0/15
          shareTargets:
            organizationalUnits:
              - Infrastructure
	# 6 /18 Workload Pools from 10.192.0.0/18 to 10.193.64.0/18
        - name: central-Pool
          description: Pool for Central VPC
          locale: *HOME_REGION
          sourceIpamPool: ca-central-Pool
          provisionedCidrs:
            - 10.193.128.0/18
          shareTargets:
            organizationalUnits:
              - Infrastructure
		- name: perimeter-Pool
          description: Pool for Perimeter VPC
          locale: *HOME_REGION
          sourceIpamPool: ca-central-Pool
          provisionedCidrs:
            - 10.193.192.0/22
          shareTargets:
            accounts:
              - Perimeter
        - name: endpoints-Pool
          description: Pool for Endpoints VPC
          locale: *HOME_REGION
          sourceIpamPool: ca-central-Pool
          provisionedCidrs:
            - 10.193.196.0/22
          shareTargets:
            organizationalUnits:
              - Infrastructure
        - name: NewPool
          description: NewPool for New VPC
          locale: *HOME_REGION
          sourceIpamPool: ca-central-Pool
          provisionedCidrs:
            - 10.193.255.224/27
          shareTargets:
            organizationalUnits:
              - Infrastructure
			  
- name: NewVPC
    tags:
      - key: Name
        value: NewVPC
    account: CentralNetwork
    region: ca-central-1
    ipamAllocations:
      - ipamPoolName: NewPool
        netmaskLength: 27
    routeTables:
       - name: RouteTable
          routes: []
    subnets:
      - name: NewVPC-A
        availabilityZone: 1
        routeTable: RouteTable
        ipamAllocation:
          ipamPoolName: NewPool
          netmaskLength: 28
      - name: NewVPC-B
        availabilityZone: 2
        routeTable: RouteTable
        ipamAllocation:
          ipamPoolName: NewPool
          netmaskLength: 28
```
