### ISSUE TITLE
Deployment of Network Firewall and Resource Sharing in YAML Configuration

### ISSUE THREAD

**Issue by klucmally** [awslabs/landing-zone-accelerator-on-aws#627]
Summary:
Deployment does not properly provision Network Firewall resources and other cross-account resources using shareTargets, causing resources to be missing in specific accounts or regions.

Steps to Reproduce:

Configure the AWS Accelerator deployment with a YAML file specifying:
transitGateways with shareTargets for cross-account sharing.
networkFirewall policies and rules configured with shareTargets.
VPCs and subnets within a transit VPC for network inspection.
Additional centralNetworkServices and gatewayLoadBalancers.
Run the deployment in AWS CodeBuild.
Observe deployment logs for successful execution or differences between expected and deployed resources.
Expected Behavior:

All specified resources, including the network firewall, gateway load balancers, transit gateways, and associated route tables, should be deployed and configured according to the YAML file.
shareTargets should allow resources to be accessible across specified organizational units and accounts without deployment errors.
Actual Behavior:

Deployment completes without critical errors, but network firewall , gatewayLoadBalancers resources and some cross-account sharing configurations do not appear in the expected accounts.

Any insights into dependencies or order-of-declaration requirements for shareTargets and cross-account network resources would be helpful.

**Comment by bo1984** [comment]
Hi @klucmally! Thank you for reaching out and utilizing the Landing Zone Accelerator on AWS (LZA) solution. The formatting of the output makes this a bit hard to read, but I do see that you have the `centralNetworkServices` property where the Network Firewalls is provisioned. I want to make sure that the aforementioned property is at the root-level (same level where the `transitGateway` property is in as an example) in your network-config. In your configuration, the Network Firewall should be created in the `Transit` account, and the endpoints distributed out via AWS Resource Access Manager (AWS RAM) to the Accounts that exists in your `Infrastructure` Organizational Unit. Are you seeing these resources?

**Comment by fdjahnke** [comment]
Hello @klucmally, thank you for filing an issue with the Landing Zone Accelerator team! This appears to be a configuration issue specific to your deployment rather than a defect in LZA.

In your `network-config.yaml`, `networkFirewall` and `gatewayLoadBalancers` are defined at the top level. LZA only reads these as properties of `centralNetworkServices`, so top-level entries are ignored and the resources are never created (which is why the deployment finishes without errors but nothing shows up). Please nest both blocks under `centralNetworkServices`, alongside `delegatedAdminAccount`:

```yaml
centralNetworkServices:
  delegatedAdminAccount: Transit
  gatewayLoadBalancers:
    - name: Transit-Gwlb
      # ...
  networkFirewall:
    firewalls:
      - name: Transit-Inspection-FwEndpoint
        # ...
    policies:
      - name: Transit-Inspection-FwPolicy
        # ...
    rules:
      - name: Transit-Inspection-Fw-Stateful-Group
        # ...
```

Closing this issue as it is specific to your deployment configuration. If after correcting the nesting you still see resources missing, this would be best triaged through AWS Support — or feel free to re-open with detailed steps to reproduce (and please ping me so I see it). Thanks!
