### ISSUE TITLE
TGW Peering issue

### ISSUE THREAD

**Issue by benyo1892** [awslabs/landing-zone-accelerator-on-aws#632]
Please provide the following information:
Hi,
I have implemented LZA on region Israel, I have 2 TGW, and I tried to do peering between them.
I have configured it according to the documentation.
The pipeline failed on NetworkingVpcStack.
Also important to mention I have AutoAccept flag on true.

- [ ] Version: [ v1.10.0]

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [ ] Region: [il-central-1]

Here is my configuration of the peering:

```
transitGatewayPeering:
 - name: medasys-vpn-peering-tgw-tlv
   autoAccept: true
   requester:
     transitGatewayName: medasys-vpn-tgw-tlv
     account: medasys-aws-networking
     region: il-central-1
     routeTableAssociations: vpn-tgw-rt-tlv
     tags:
       - key: Name
         value: medasys-vpn-peering-tgw-tlv
   accepter:
     transitGatewayName: medasys-tgw-tlv
     account: medasys-aws-networking
     region: il-central-1
     routeTableAssociations: egress-tgw-rt-tlv
     autoAccept: true
     applyTags: true
```

Please let me know if there any suggestion for that issue.

Thanks,
