### ISSUE TITLE
Transit Gateway RouteTable Propagation

### ISSUE THREAD

**Issue by ahammoud-murex** [awslabs/landing-zone-accelerator-on-aws#634]
In the documentation its mentioned that this parameter in Transit Gateway Configuration can be like the below.
**defaultRouteTablePropagation: enable or disable**

When choosing enable, the pipeline is crashing in the middle as it is expecting a route table ID but its not mentioned where it should be provided.

AWSAccelerator-NetworkPrepStack-99999999999-eu-west-1 \| 0/3 \| 4:17:25 PM \| UPDATE_FAILED        \| AWS::EC2::TransitGateway           \| AWSTESTTgwTransitGateway (AWSTESTTRANSITGATEWAY) Resource handler returned message: "enable DefaultRouteTablePropagation conflicts with PropagationDefaultRouteTableId null (Service: Ec2, Status Code: 400, Request ID: f2a6e5bd-ea36-4947-9418-1666a8834d6c)" (RequestToken: 61ab64e4-e751-0266-45f4-2c78bb4dda3b, HandlerErrorCode: GeneralServiceException)
--
542 | new TransitGateway (/codebuild/output/src4133/src/s3/00/source/packages/@aws-accelerator/constructs/lib/aws-ec2/transit-gateway.ts:503:22)

**Comment by bo1984** [comment]
Hi @ahammoud-murex ! Thank you for reaching out and utilizing the Landing Zone Accelerator on AWS (LZA) solution. I've tested out provisioning a TGW with this configuration and was unable to replicate:

```
transitGateways:
  - name: Testing-Tgw
    account: Network
    region: *HOME_REGION
    shareTargets:
      organizationalUnits:
        - Infrastructure
    asn: 65530
    dnsSupport: enable
    vpnEcmpSupport: enable
    defaultRouteTableAssociation: disable
    defaultRouteTablePropagation: enable
    autoAcceptSharingAttachments: enable
    routeTables:
      - name: Test-Core
        routes: []
      - name: Test-Segregated
        routes: []
```

```
"TransitGateways": [
        {
            "TransitGatewayId": "[REDACTED]",
            "TransitGatewayArn": "arn:aws:ec2:us-east-1:[REDACTED]:transit-gateway/[REDACTED]",
            "State": "available",
            "OwnerId": "341643402581",
            "CreationTime": "2025-02-04T17:22:45+00:00",
            "Options": {
                "AmazonSideAsn": 65530,
                "AutoAcceptSharedAttachments": "enable",
                "DefaultRouteTableAssociation": "disable",
                "DefaultRouteTablePropagation": "enable",
                "PropagationDefaultRouteTableId": "[REDACTED]",
                "VpnEcmpSupport": "enable",
                "DnsSupport": "enable",
                "SecurityGroupReferencingSupport": "disable",
                "MulticastSupport": "disable"
            },
            "Tags": [
                {
                    "Key": "Tag1",
                    "Value": "Global"
                },
                {
                    "Key": "Accelerator",
                    "Value": "AWSAccelerator"
                },
                {
                    "Key": "Name",
                    "Value": "Testing-Tgw"
                }
            ]
        }
    ]
}
```

What does your TGW configuration look like? Also, what version of LZA are you on?
