### ISSUE TITLE
Add Support for IP addresses from outside the VPC in ALB TargetGroups created by LZA

### ISSUE THREAD

**Issue by sriharshakns** [awslabs/landing-zone-accelerator-on-aws#661]
**Is your feature request related to a problem? Please describe.**
TargetGroup allows to add IP addresses from both within and outside the VPC via EC2 Console. The same feature is also supported in underlying CloudFormation resource [AWS::ElasticLoadBalancingV2::TargetGroup](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-targetgroup-targetdescription.html) and can be enabled by setting "AvailabilityZone" property to "all".

However, as per the source code [network-associations](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/source/packages/%40aws-accelerator/accelerator/lib/stacks/network-stacks/network-associations-stack/network-associations-stack.ts#L544) and [target-group](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/11a38bd38aa931a75121a81f50e222ccec6f4202/source/packages/%40aws-accelerator/constructs/lib/aws-elasticloadbalancingv2/target-group.ts#L112), there is no such provision in LZA.

**To Reproduce:**
Define the targetGroups as follows:
```
vpcs: 
  - name: Network-Ingress
    ...
    cidrs:
      - 10.54.240.0/24   #VPC CIDR
    ....
    targetGroups:
      - name: Test
        port: 80
        protocol: HTTP
        type: ip
        targets:
          - '10.54.69.14'   # Fails as it is outside VPC
          - '10.54.240.100' # Works as it is within the same VPC
        healthCheck:
          enabled: true
          port: 80
          protocol: HTTP
```

Any attempts to create the same will fail the NetworkAssociationsStack with below error:

```
Resource handler returned message: "You must specify a valid Availability Zone or select 'all' for all enabled Availability zones, since the IP address '10.54.69.14' is outside the VPC (Service: ElasticLoadBalancingV2, Status Code: 400, ..., HandlerErrorCode: GeneralServiceException)
```

**Describe the feature you'd like**
Ability to set the "AvailabilityZone" property in LZA manifests.

**Possible Workaround:**
Add the desired Listener and TargetGroup using template file under cloudFormationStacks in customizations-config.yaml.

*Sample Template Snippet:*
```
Resources:
  ElasticLoadBalancingV2TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      ....
      Targets:
        - AvailabilityZone: all    <----------
          Port: 80
          Id: 10.54.69.14
```

**Additional context**
Console screenshot.

![image](https://github.com/user-attachments/assets/1e3b1437-a84b-4eb7-adf7-4b32f90083ed)
