### ISSUE TITLE
"You don't have permissions to access this resource." in SecurityAudit stack

### ISSUE THREAD

**Issue by andreprawira** [awslabs/landing-zone-accelerator-on-aws#673]
**Describe the bug**
We have an AWS account that before we deploy LZA, its already our delegated administrator of SecurityHub, so we enabled securityhub and designated that account as the administrator. Keep in mind this isnt the Audit Account, this is our security-config.yaml

```
centralSecurityServices:
  delegatedAdminAccount:  <already-existsting-securityhub-administrator-account-not-Audit-Account>
  securityHub:
    enable: true
    regionAggregation: true
    excludeRegions: []
    standards:
      - name: AWS Foundational Security Best Practices v1.0.0
        enable: true
        controlsToDisable:
          - IAM.1
          - EC2.10
          - Lambda.4
  ssmAutomation:
    excludeRegions: []
    documentSets: []
```

when we deploy the pipeline, it passes the build stage, but fails at the SecurityAudit stack, here is the build log

```
AWSAccelerator-SecurityAuditStack-<Audit-Account-ID>-us-east-1 | 5/10 | 8:18:50 PM | CREATE_FAILED        | Custom::SecurityHubCreateMembers     | SecurityHubMembers/Resource/Default (SecurityHubMembers2A2B77C4) Received response status [FAILED] from custom resource. Message returned: AccessDeniedException: You don't have permissions to access this resource.
```

whats interesting is that the securityauditstack fails with the audit account id, not that account that we use as the securityhub delegated administrator account. additionally, if i scroll up on the build log, i see this 

```
Assuming role arn:aws:iam::<audit-account-id>:role/OrganizationAccountAccessRole for 3600 seconds
--
171 | AWSAccelerator-SecurityAuditStack-<audit-account-id>-us-east-1: deploying... [1/1]
172 | AWSAccelerator-SecurityAuditStack-<audit-account-id>-us-east-1: creating CloudFormation changeset...
```

**To Reproduce**
1. have an account that serves as the securityhub delegated administrator
2. add that account in LZA configuration
3. pipeline will fail with that error
**Expected behavior**

**Please complete the following information about the solution:**
- [ ] Version: v1.10.0
- [ ] Region: e.g. us-east-1
- [ ] Was the solution modified from the version published on this repository? yes
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? yes, its got nothing to do with that
- [ ] Were there any errors in the CloudWatch Logs? yes, i posted the error
