### ISSUE TITLE
Moving SCP in Organization did not work

### ISSUE THREAD

**Issue by m-franke-tqgg** [awslabs/landing-zone-accelerator-on-aws#699]
**Describe the bug**
We rolled out a Service Control Policy via the organization-config.yaml. The SCP was configured to be attached to the `- Root` of the Organization because we wanted it to protect resources on a global scale for all accounts. The only problem was that the SCP turned out to be faulty and caused problems for the software we were going to protect. I then changed the configuration of that particular SCP so that it was configured to only one OU in the Organization where we store our quarantined accounts and could do no more harm.

The only problem was that when the pipeline finished running, and I checked the organization's settings, the SCP was still attached to the root level of the Organization.

To disable the SCP, I had to manually detach it from the root-level object, which is what the LZA config change should have done.

**To Reproduce**
* Create a SCP and config object in the organization-config.yaml file with 
```
serviceControlPolicies:
  - name: TestSCP
    description: Just a test
    policy: service-control-policies/test-scp.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits:
        - Root
```
* Then change the organizationalUnits setting to a different OU
* Run the LZA pipeline
* Check settings in Org-Root-Account

**Expected behavior**
The Service Control Policy should only be attached to the OU it was configured for and not still be attached to the former Root Level.

I did another test by moving the SCP from one OU to another, and that change did work properly.

**Please complete the following information about the solution:**

- [x] Version: v1.11.0

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [x] Region: eu-central-1
- [ ] Was the solution modified from the version published on this repository? No
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? 
  Not applicable, the pipeline ran without issues.
- [ ] Were there any errors in the CloudWatch Logs?
  Haven't checked, but I expect none as the pipeline run finished successfully.

**Comment by turqual** [comment]
Was it also applied to the new target?

**Comment by nagmesh** [comment]
Thank you for your patience on this. 
I tried to replicate this issue and was unable to do so. 

Environment - v1.12.1

Config was
```yaml
enable: true
organizationalUnits:
  - name: Security
  - name: Infrastructure
serviceControlPolicies: 
  - name: AcceleratorGuardrails1
    description: >
      Accelerator GuardRails 1
    policy: service-control-policies/full-access.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits:
        - Root
taggingPolicies: []
backupPolicies: []
```

After pipeline run, confirmed it using cli
```zsh
> POLICY_ID=$(aws organizations list-policies --filter SERVICE_CONTROL_POLICY --query 'Policies[?Name==`AcceleratorGuardrails1`].Id' --output text)
> aws organizations list-targets-for-policy --policy-id $POLICY_ID --query 'Targets[*].Name' --output text
Root
```

Change config to 
```yaml
enable: true
organizationalUnits:
  - name: Security
  - name: Infrastructure
serviceControlPolicies: 
  - name: AcceleratorGuardrails1
    description: >
      Accelerator GuardRails 1
    policy: service-control-policies/full-access.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits:
        - Security
taggingPolicies: []
backupPolicies: []
```

Ran it in v1.12.1 and it shows its showed that its attached to Security

```zsh
> POLICY_ID=$(aws organizations list-policies --filter SERVICE_CONTROL_POLICY --query 'Policies[?Name==`AcceleratorGuardrails1`].Id' --output text)
> aws organizations list-targets-for-policy --policy-id $POLICY_ID --query 'Targets[*].Name' --output text
Security
```

Within CloudTrail console, check for eventName as DetachPolicy and see if there is an error in response. 
For example, for a successful call I can see
```json
{
    "eventVersion": "1.09",
      ...
    "eventSource": "organizations.amazonaws.com",
    "eventName": "DetachPolicy",
    "awsRegion": "us-east-1",
   ...
    "userAgent": "aws-sdk-js/3.638.0 ua/2.0 os/linux#5.10.236-248.928.amzn2.x86_64 lang/js md/nodejs#20.19.0 api/organizations#3.638.0 exec-env/AWS_Lambda_nodejs20.x AwsSolution/SO0199/1.12.1",
    "requestParameters": {
        "policyId": "p-ztmkokx1",
        "targetId": "r-l63a"
    },
    "responseElements": null,
    ...
}
```

There is an exception that gets ignored if the detached policy is already detached. 
```json
{
    "eventVersion": "1.09",
    ...
    "eventSource": "organizations.amazonaws.com",
    "eventName": "DetachPolicy",
    "awsRegion": "us-east-1",
    ...
    "userAgent": "aws-sdk-js/3.638.0 ua/2.0 os/linux#5.10.236-248.928.amzn2.x86_64 lang/js md/nodejs#20.19.0 api/organizations#3.638.0 exec-env/AWS_Lambda_nodejs20.x AwsSolution/SO0199/1.12.1",
    "errorCode": "PolicyNotAttachedException",
    "errorMessage": "The specified policy is not currently attached to the target.",
    "requestParameters": {
        "policyId": "p-ztmkokx1",
        "targetId": "ou-l63a-9iciupx3"
    },
    "responseElements": null,
    ....
}
```

Can you share? 
- what version you used? 
- exact config changes done to replicate it
- If you see something in cloudwatch logs saying `Detaching AcceleratorGuardrails1 policy from $ROOT_ID target`
- if there exceptions you see in Cloudtrail that is not shown above
