### ISSUE TITLE
GlobalConfig: ISnsConfig inconsistent documentation / functionality for snsTopics property

### ISSUE THREAD

**Issue by Flojolomo** [awslabs/landing-zone-accelerator-on-aws#700]
**Describe the bug**
The JSON Schema of global config does not define `snsTopcis.topics` as required. When deploying the configuration with `snsTopics` defined, but `topics` not set, validation fails.

```yaml
snsTopics:
  deploymentTargets:
    organizationalUnits:
      - Root
  # topics:
  #   - name: Security
  #     emailAddresses:
  #       - dummy@test.com
```

**To Reproduce**
* Change configuration of `snsTopics` to not include the property `topics` 
```yaml
homeRegion: &HOME_REGION eu-west-1
enabledRegions:
  - *HOME_REGION
managementAccountAccessRole: AWSControlTowerExecution
cloudwatchLogRetentionInDays: 30
terminationProtection: true
cdkOptions:
  centralizeBuckets: true
  useManagementAccessRole: true
snsTopics:
  deploymentTargets:
    organizationalUnits:
      - Root
  # This section causes the validation to fail
  # topics:
  #   - name: Security
  #     emailAddresses:
  #       - user@company.com
controlTower:
  enable: true
  landingZone:
    version: '3.3'
    logging:
      loggingBucketRetentionDays: 30
      accessLoggingBucketRetentionDays: 365
      organizationTrail: true
    security:
      enableIdentityCenterAccess: false
logging:
  account: LogArchive
  cloudtrail:
    enable: true
    organizationTrail: true
    organizationTrailSettings:
      multiRegionTrail: true
      globalServiceEvents: true
      managementEvents: true
      s3DataEvents: false
      lambdaDataEvents: false
      sendToCloudWatchLogs: true
      apiErrorRateInsight: false
      apiCallRateInsight: false
    accountTrails: []
  sessionManager:
    sendToCloudWatchLogs: false
    sendToS3: false
    lifecycleRules: []
```
* Validate you configuration, either in the pipeline or locally 
* Validation fails 
<img width="842" alt="Image" src="https://github.com/user-attachments/assets/dadd1055-79f1-4d60-8d85-70fd3924a06a" />

**Expected behavior**
* JSON Schema matches the actual validation
* Validation fails with a helpful message to track down the root cause

**Please complete the following information about the solution:**

- [ ] Version: release/v1.11.0
- [ ] Region: eu-west-1 & eu-central-1
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
See screenshot above to reproduce the issue

**Additional context**
