### ISSUE TITLE
GlobalConfig: Toggling controlTower.landingZone.logging.organizationTrail does not update the ControlTower landing zone

### ISSUE THREAD

**Issue by florian-netlight** [awslabs/landing-zone-accelerator-on-aws#703]
**Describe the bug**
Updating the configuration `controlTower.landingZone.logging.organizationTrail` in the global config does not effect the ControlTower landing zone. It is not updated and gets out of sync.

**To Reproduce**
* Deploy the LZA with the following segment in global-config.yaml
```yaml
controlTower:
enable: true
landingZone:
  version: '3.3'
  logging:
    loggingBucketRetentionDays: 365
    accessLoggingBucketRetentionDays: 365
    organizationTrail: true
``` 
* Deploy the LZA with the following segment in global-config.yaml
```yaml
controlTower:
enable: true
landingZone:
  version: '3.3'
  logging:
    loggingBucketRetentionDays: 365
    accessLoggingBucketRetentionDays: 365
    organizationTrail: false
``` 

**Expected behavior**
ControlTower landing zone is updated

**Please complete the following information about the solution:**

- [ ] Version: v1.11.0
- [ ] Region: eu-west-1
- [ ] Was the solution modified from the version published on this repository? 
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? (not relevant)
- [ ] Were there any errors in the CloudWatch Logs? (not relevant)
