### ISSUE TITLE
Unable to create commonly named IAM roles across multiple AWS accounts with unique trust policies

### ISSUE THREAD

**Issue by edhull** [awslabs/landing-zone-accelerator-on-aws#707]
**Describe the bug**
I'm attempting to use the LZA to create a commonly named IAM role across multiple AWS accounts, but to specify a unique trust policy for that role depending on which account this role lives in. See this diagram for an example:

<img width="1187" alt="Image" src="https://github.com/user-attachments/assets/d5df3c0e-cacf-4b08-92e1-1dc74d4589b4" />

An 'automation' role should be available across multiple accounts, but have a unique trust setup. Account A should be allowed to assume to the 'automation' role in Account W, Account B should be allowed to assume to the 'automation' role in Account X, etc.

The following code is an example snippet of how this has been attempted via the LZA in `iam-config.yaml`:

```
roleSets:
  - deploymentTargets:
      accounts:
        - AccountW
    roles:
    - name: automation
      assumedBy:
        - type: account
          principal: "arn:aws:iam::{{account AccountA}}:root"
      policies:
        awsManaged:
          - AWSSupportAccess
          - ReadOnlyAccess
  - deploymentTargets:
      accounts:
        - AccountX
    roles:
    - name: automation
      assumedBy:
        - type: account
          principal: "arn:aws:iam::{{account AccountB}}:root"
      policies:
        awsManaged:
          - AWSSupportAccess
          - ReadOnlyAccess
```

When the LZA runs the `Build` stage, this code fails the validation stating that roles must be uniquely named:

<img width="936" alt="Image" src="https://github.com/user-attachments/assets/343d54a3-2fe3-477a-8902-dcc28d7e6190" />

This validation is trying to ensure that the same role is not attempting to be being created in the same account multiple times, but as a result it is not possible to assign unique trust policies to multiple roles of the same name deployed across _different_ accounts. 

This validation should be updated to allow for the same role appearing multiple times, but ensuring that the deploymentTargets.accounts entries do not overlap for the same role.

**To Reproduce**
Leverage the example snippet above to create multiple roles of the same name with unique trust policies. 

**Expected behavior**
LZA should not block the process of creating the same role across multiple AWS accounts which have unique trust policies

**Please complete the following information about the solution:**

- [x] Version: v1.10.1

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [x] Region: eu-west-2
- [x] Was the solution modified from the version published on this repository? No
- [x] If the answer to the previous question was yes, are the changes available on GitHub? N/A
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes
- [x] Were there any errors in the CloudWatch Logs? N/A
