### ISSUE TITLE
VPC Flow Logs not enabled

### ISSUE THREAD

**Issue by Jreamz** [awslabs/landing-zone-accelerator-on-aws#728]
**Describe the bug**
When enabling *strictly* VPC flow logs in the `network-config.yaml` and not defining any VPCs, VPC flow logs are not enabled for our VPCs.

**To Reproduce**
Enabling only the VPC flow logs in the `network-config.yaml` and defining your own VPCs outside of the `network-config.yaml`

**Expected behavior**
VPC Flow Logs would still be enabled for our VPCs to leverage the centralized logging account and mechanisms within the LZA. The docs [here](https://awslabs.github.io/landing-zone-accelerator-on-aws/v1.11.0/typedocs/latest/classes/___packages__aws_accelerator_config_lib_common_types.VpcFlowLogsConfig.html) do not show a VPC requirement.

**Please complete the following information about the solution:**

- [x] Version: [e.g. v1.11.0]
- [x] Region: us-east-1
- [ ] Was the solution modified from the version published on this repository? **No**
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? ***N/A***
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? **N/A**
- [ ] Were there any errors in the CloudWatch Logs? **No**

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

![Image](https://github.com/user-attachments/assets/9a020071-158b-4ba9-bc13-f0be29df0538)

![Image](https://github.com/user-attachments/assets/72dfa81d-e23b-4d2d-9a19-e2914d8cc618)

**Additional context**

Context: We are creating our own network stack via CDK, but wanted to use the `network-config.yaml` and the `vpcFlowLogs` to leverage the centralized logging within the LZA:

```
homeRegion: &HOME_REGION us-east-1
defaultVpc:
  delete: true
  excludeAccounts: []

transitGateways: []
endpointPolicies: []
vpcs: []

# VPCFlowLogs configuration
vpcFlowLogs:
  trafficType: ALL
  maxAggregationInterval: 600
  destinations:
    - cloud-watch-logs
  destinationsConfig:
    cloudWatchLogs:
      retentionInDays: 30
  defaultFormat: false
  customFields:
    - version
    - account-id
    - interface-id
    - srcaddr
    - dstaddr
    - srcport
    - dstport
    - protocol
    - packets
    - bytes
    - start
    - end
    - action
    - log-status
    - vpc-id
    - subnet-id
    - instance-id
    - tcp-flags
    - type
    - pkt-srcaddr
    - pkt-dstaddr
    - region
    - az-id
    - pkt-src-aws-service
    - pkt-dst-aws-service
    - flow-direction
    - traffic-path
```
Does the `network-config.yaml` need to be creating the VPCs for this to work? Can we pass our own vpc-ids, names, fields, etc. into the config from our stacks?
