### ISSUE TITLE
Cannot disable security hub or exclude regions

### ISSUE THREAD

**Issue by bpauwels** [awslabs/landing-zone-accelerator-on-aws#729]
**Describe the bug**
If security hub has been activated, it cannot be disabled by setting `enable: false` or adding regions to excluded regions

**To Reproduce**
In `security-config.yaml` enable security hub, then disable.

**Expected behavior**
When setting `enable: false`, security hub should be disabled. When adding regions to excluded regions, it should be disabled in these regions.
```yaml
  securityHub:
    enable: false
    regionAggregation: true
    excludeRegions: 
      - eu-west-1
    standards:
      - name: AWS Foundational Security Best Practices v1.0.0
        # https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html
        enable: true
```

**Please complete the following information about the solution:**

- [v1.10.0] Version: [e.g. v1.5.1]

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [eu-central-1] Region: [e.g. us-east-1]
- [no] Was the solution modified from the version published on this repository?
- [-] If the answer to the previous question was yes, are the changes available on GitHub?
- [n/a] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [no] Were there any errors in the CloudWatch Logs?

**Screenshots**
n/a

**Additional context**
-
