### ISSUE TITLE
iam-config.yaml IDC configuration doesn't implement changes

### ISSUE THREAD

**Issue by farmerbean** [awslabs/landing-zone-accelerator-on-aws#73]
**Describe the bug**
Config in iam-config.yaml doesn't run in the pipeline - it's ignored

**To Reproduce**
Put IDC configuration into iam-config.yaml:

```
providers: []
policySets: []
roleSets: []
userSets: []
identityCenter:
  name: ctIdentityCenter
identityCenterPermissionSets:
  - name: ISVPermissionSetViewOnly
    policies:
      awsManaged:
      - arn:aws:iam::aws:policy/ViewOnlyAccess
    sessionDuration: 60
identityCenterAssignments:
  - name: Assignment002
    permissionSetName: ISVPermissionSetViewOnly
    principalId: "82b53444-6051-7037-dda5-663a916ece5c"
    principalType: GROUP
    deploymentTargets:
      accounts:
      - someWorkloadAccount
```

**Expected behavior**
Creates permission sets for the group specified in the assignment

**Please complete the following information about the solution:**

- [ 1.3.0] Version: [e.g. v1.1.0]

- [ eu-west-1] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
