### ISSUE TITLE
Spawn OIDC providers in member accounts

### ISSUE THREAD

**Issue by dyfox1** [awslabs/landing-zone-accelerator-on-aws#74]
**Is your feature request related to a problem? Please describe.**
We'd like to be able to deploy OIDC providers in member accounts similar to how SAML providers are deployed today.  This helps us bootstrap accounts for use with OIDC-backed services like GitHub.

**Describe the feature you'd like**
Ideally extend this: https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.IamConfig.html#providers to include OIDC providers.  Also would like to target these providers to accounts in a specific OU.

**Additional context**
This is the resource we'd like to have the LZA create for us: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-oidcprovider.html

**Comment by awsclemj** [comment]
Hello @dyfox1, and thanks for reaching out to the LZA team!

I wanted to inform you that we have filed a feature request on your behalf. We'll leave this issue open until the feature has been integrated into one of our future release branches.

Thanks for your support and interest in the solution!

**Comment by rdkls** [comment]
Same need here. Our use case is we're building an organization (many accounts) platform on AWS, with Gitlab (like Github, its CICD supports OIDC) for SCM + CICD.

**Comment by rdkls** [comment]
fwiw my workaround has been to use the custom CFN stack e.g.

customizations-config.yaml
```homeRegion: &HOME_REGION ap-southeast-2
customizations:
  # Please note that deployed custom CloudFormation Stacks are not deleted if they are removed from customizations-config.yaml. All custom stacks deployed by LZA must be deleted manually if they are no longer needed
  # https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.CloudFormationStackConfig.html
  cloudFormationStacks:
    - name: GitlabOIDCProvider
      description: Deploy Gitlab OIDC Provider to all Workload accounts
      runOrder: 1
      regions:
        - *HOME_REGION
      template: cloudformation/GitlabOIDCProviderStack.yaml
....
```

```
Resources:
  GitlabOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: !Sub "https://${GitlabDomain}"
      ClientIdList:
        - !Sub "https://${GitlabDomain}"
      ThumbprintList:
        - !Ref GitlabThumbprint
....
```

I suspect your use-case is similar to mine @dyfox1 so I also had an IAM role for the CICD runners to assume like so:

```
  GitlabCicdRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GitlabOIDCProvider
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                GitlabOIDCProvider:sub:
                  Fn::FindInMap:
                    - AccountSubConditionMapping
                    - !Ref "AWS::AccountId"
                    - "sub"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      PermissionsBoundary: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/permissionboundarypolicy"
```

And have the AccountSubConditionMapping up top, mapping account ID to the required sub condition (branch/project) to allow only specific repos/branches to deploy to that account.
