### ISSUE TITLE
GovCloud Accounts Not Vending - Option 1

### ISSUE THREAD

**Issue by josh-moss-lumen** [awslabs/landing-zone-accelerator-on-aws#750]
**Describe the bug**
I have a govcloud linked commercial account. I verified this. I add new govcloud accounts to be created to my accounts-config.yaml and set `enableGovCloud` to true.

```
workloadAccounts:
  - name: LogArchiveGC # referred to as LogArchive in the GovCloud account-config.yaml
    description: The log archive account for GovCloud.
    email: log-archive-gc@customer.com
    organizationalUnit: GovCloud
    # enableGovCloud is a one-time non-reversible option
    # which only works with creation of new accounts
    enableGovCloud: true
  - name: AuditGC # referred to as LogArchive in the GovCloud account-config.yaml
    description: The security audit account (also referred to as the audit account) for GovCloud.
    email: audit-gc@customer.com
    organizationalUnit: GovCloud
    enableGovCloud: true
```

The pipeline runs successfully and vends commercial accounts, but there are no linked GovCloud accounts vended. The linked gov accounts are not present in the dyanamo table. There is no `CreateGovCloudAccount` api call log in cloudtrail. 

**To Reproduce**
Install LZA v1.12.0. 

Add the above to your accounts-config.yaml 

Run the pipeline 

**Expected behavior**
GovCloud accounts vended and account IDs to be present in dynamo table. 

**Please complete the following information about the solution:**

- [ 1.12.0 ] Version: 1.12.0
- [ us-east-2 ] Region: [e.g. us-east-2]
- [ No ] Was the solution modified from the version published on this repository? No
- [ N/A ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ Y ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ N ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

No govcloud account ids on the accounts. 

![Image](https://github.com/user-attachments/assets/a3fa09c1-7bd7-4afe-af4a-6ab2b8cc0762)
