### ISSUE TITLE
Lambda functions with deprecated nodejs versions are not deleted after upgrade to v1.12.1

### ISSUE THREAD

**Issue by aaronlee-ds** [awslabs/landing-zone-accelerator-on-aws#761]
**Describe the bug**
Old Lambda functions with deprecated nodejs versions are not deleted after upgrade to v1.12.1. New Lambdas are created successfully on nodejs v20, but there doesn't seem to be a cleanup process to delete the older lambda functions.

**To Reproduce**
Upgrade LZA solution from 1.10.0 -> 1.12.1.

CloudFormation stacks retain older lambda functions.

**Expected behavior**
I would expect the old lambda resources to be cleaned up and deleted after new lambdas are created. 

**Please complete the following information about the solution:**

- [x] Version: [e.g. v1.12.1]

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [x] Region: [e.g. us-gov-east-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by Athanasii** [comment]
Hello @aaronlee-ds , thank you for filing an issue with the Landing Zone Accelerator team!

To ensure we have all relevant details for this issue, can you please provide which lambda functions are left behind?

Thanks, and we look forward to hearing back from you!

**Comment by aaronlee-ds** [comment]
I believe it is all the lambdas. I can see in the CloudFormation console that it just creates new Lambda resources and doesn't "update" the current.

**Comment by fdjahnke** [comment]
Hello @aaronlee-ds, thank you for the added information. We have not seen this behavior before and are unsure why this is happening. Lambda functions should get updated with an LZA update. Would you be able to provide additional details in your environment? Screenshots, names of old and new Lambda functions, logs?
Did you deploy any other changes during the update?

We would appreciate your help understanding this behavior.

**Comment by cpl-aws-github** [comment]
Hi team

I upgraded from version 1.9.0 to version 1.12.0, and there are some lambdas that are present in Nodejs versions 16 and 18.

![Image](https://github.com/user-attachments/assets/ca132290-16d7-4354-8c64-293cc08e87a1)

![Image](https://github.com/user-attachments/assets/6bba57e2-de7c-48d3-b1e9-8ac725edb425)

**Comment by MarkCondry** [comment]
I am also seeing the same behavior

**Comment by aaronlee-ds** [comment]
> Hi team
> 
> I upgraded from version 1.9.0 to version 1.12.0, and there are some lambdas that are present in Nodejs versions 16 and 18.
> 
> ![Image](https://github.com/user-attachments/assets/ca132290-16d7-4354-8c64-293cc08e87a1)
> 
> ![Image](https://github.com/user-attachments/assets/6bba57e2-de7c-48d3-b1e9-8ac725edb425)

This is exactly the thing I'm seeing. The new version of lambdas get brand new CF resources created and don't actually update the existing CF resources with older lambda versions.

**Comment by bo1984** [comment]
Hello @aaronlee-ds !

To clear up any confusion, at the moment, LZA will provision a number of custom resources that use Lambda for automation around the provisioning of various services. Based on the screenshots, these are Lambda functions that although LZA deployed, the runtime of the Lambda functions are not deployed. These are AWS Config custom rules that look to be Lambda backed that are configured within your security-config.yaml file. Below is a similar function that I have in my testing environment, where you'll see the `runtime` property is something that you have control over.

```
- name: accelerator-target-document-01
          type: Custom
          description: Custom rule for testing target document remediation
          inputParameters:
          customRule:
            lambda:
              sourceFilePath: custom-config-rules/attach-ec2-instance-profile.zip
              handler: index.handler
              runtime: nodejs18.x
              rolePolicyFile: custom-config-rules/attach-ec2-instance-profile-detection-role.json
            periodic: true
            maximumExecutionFrequency: Six_Hours
            configurationChanges: true
            triggeringResources:
              lookupType: ResourceTypes
              lookupKey: ResourceTypes
              lookupValue:
                - AWS::EC2::Instance
          remediation:
            rolePolicyFile: custom-config-rules/attach-ec2-instance-profile-remediation-role.json
            automatic: true
            targetId: Attach-IAM-Instance-Profile
            targetDocumentLambda:
              sourceFilePath: custom-config-rules/targetDocumentLambda.zip
              handler: index.handler
              runtime: nodejs18.x
              rolePolicyFile: custom-config-rules/attach-ec2-instance-profile-remediation-role.json
            retryAttemptSeconds: 60
            maximumAutomaticAttempts: 5
            parameters:
              - name: InstanceId
                value: RESOURCE_ID
                type: String
              - name: IamInstanceProfile
                value: ${ACCEL_LOOKUP::InstanceProfile:EC2-Default-SSM-AD-Role}
                type: StringList
          tags:
            - key: key
              value: value
```
