### ISSUE TITLE
AWSAccelerator-LoggingStack-CustomUpdateSubscription is not authorized to perform kms:Encrypt and kms:Decrypt

### ISSUE THREAD

**Issue by mattyremf** [awslabs/landing-zone-accelerator-on-aws#768]
**Describe the bug**
Currently doing a large migration of accounts from a 3rd Party Cloud Management Party to an Internal Managed landing zone
When adding some accounts to LZA we are experiencing an Error in the Logging stage which prevents the pipeline completing but also unable to easily daignose or recover as the Cloudformation stack is Rolled back.  Even when setting the --no-rollback in CDK_OPTIONS.

***Error***
```
Deployment failed: Error: The stack named AWSAccelerator-LoggingStack-{AccountNumber}:-eu-west-3 failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: AccessDeniedException: User: arn:aws:sts::{AccountNumber}::assumed-role/AWSAccelerator-LoggingSta-CustomUpdateSubscriptionF-{miniGUID}/AWSAccelerator-LoggingSta-CustomUpdateSubscription-{miniGUID} is not authorized to perform: kms:Encrypt on resource: arn:aws:kms:eu-west-3:{Account Number}::key/{KeyID} because no identity-based policy allows the kms:Encrypt action
    at de_AccessDeniedExceptionRes (/var/task/index.js:52:67203)
    at de_CommandError (/var/task/index.js:52:65823)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/task/index.js:2:11287
    at async /var/task/index.js:3:6621
    at async /var/task/index.js:13:16356
    at async /var/task/index.js:1:7492 (RequestId: 6ad829cf-a892-4707-8708-cc9c024aa429)
    at FullCloudFormationDeployment.monitorDeployment (/codebuild/output/src592/src/s3/00/source/node_modules/aws-cdk/lib/api/deploy-stack.ts:523:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack (/codebuild/output/src592/src/s3/00/source/node_modules/aws-cdk/lib/cdk-toolkit.ts:332:24)
    at async /codebuild/output/src592/src/s3/00/source/node_modules/aws-cdk/lib/util/work-graph.ts:105:11
2025-04-15 20:18:07.427 | error | toolkit | The stack named AWSAccelerator-LoggingStack-{Account Number}:-eu-west-3 failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: AccessDeniedException: User: arn:aws:sts::{AccountNumber}::assumed-role/AWSAccelerator-LoggingSta-CustomUpdateSubscriptionF-{miniGUID}/AWSAccelerator-LoggingSta-CustomUpdateSubscription-{miniGUID} is not authorized to perform: kms:Encrypt on resource: arn:aws:kms:eu-west-3:{Account Number}::key/{KeyID} because no identity-based policy allows the kms:Encrypt action
    at de_AccessDeniedExceptionRes (/var/task/index.js:52:67203)
    at de_CommandError (/var/task/index.js:52:65823)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/task/index.js:2:11287
    at async /var/task/index.js:3:6621
    at async /var/task/index.js:13:16356
    at async /var/task/index.js:1:7492 (RequestId: {RequestID})
Deployment failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

 
**To Reproduce**
Create an account in one AWS Organization, create log group in eu-west-3 (Paris),  empty and un-encrypted .
Invite account to the LZA Organization which has empty un-encrypted CloudWatch logs in the eu-west-3 (Paris) region.
Accept invitation to AWS Organizations. 
Enroll to Control Tower
Run Landing Zone Accelerator
 
Landing zone has the following config for Cloudwatch in global-config.yaml
```
logging:
  account: LogArchive
  cloudtrail:
    enable: false
    organizationTrail: false
    organizationTrailSettings:
      multiRegionTrail: true
      globalServiceEvents: true
      managementEvents: true
      s3DataEvents: true
      lambdaDataEvents: true
      sendToCloudWatchLogs: true
      apiErrorRateInsight: false
      apiCallRateInsight: false
    accountTrails: []
    lifecycleRules: []
  sessionManager:
    sendToCloudWatchLogs: false
    sendToS3: false
    excludeRegions: []
    excludeAccounts: []
    lifecycleRules: []
    attachPolicyToIamRoles: []
 
  cloudwatchLogs:
    enable: true
    encryption:
      useCMK: true
      deploymentTargets:
        organizationalUnits:
          - Root
    dynamicPartitioning: dynamic-partitioning/log-filters.json
  accessLogBucket:
    lifecycleRules:
      - enabled: true
        abortIncompleteMultipartUpload: 7
        expiration: 1000
        noncurrentVersionExpiration: 1000
        transitions:
          - storageClass: GLACIER_IR
            transitionAfter: 365
        noncurrentVersionTransitions:
          - storageClass: GLACIER_IR
            transitionAfter: 365
  centralLogBucket:
    lifecycleRules:
      - enabled: true
        abortIncompleteMultipartUpload: 7
        expiration: 1000
        noncurrentVersionExpiration: 1000
        transitions:
          - storageClass: GLACIER_IR
            transitionAfter: 365
        noncurrentVersionTransitions:
          - storageClass: GLACIER_IR
            transitionAfter: 365
    s3ResourcePolicyAttachments:
      - policy: bucket-policies/central-log-bucket.json
  elbLogBucket:
    lifecycleRules:
      - enabled: true
        abortIncompleteMultipartUpload: 7
        expiration: 1000
        noncurrentVersionExpiration: 1000
        transitions:
          - storageClass: GLACIER_IR
            transitionAfter: 365
        noncurrentVersionTransitions:
          - storageClass: GLACIER_IR
            transitionAfter: 365

``` 
dynamic-partitioning/log-filters.json
`[
  { "logGroupPattern": "/AWSAccelerator-SecurityHub", "s3Prefix": "security-hub" }
]`
 
 
bucket-policies/central-log-bucket.json
`{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Allow Organization principals to put session manager logs",
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": "s3:PutObject",
      "Resource": "arn:${PARTITION}:s3:::${ACCELERATOR_CENTRAL_LOGS_BUCKET_NAME}/*",
      "Condition": {
        "StringEquals": {
          "aws:PrincipalOrgID": "${ORG_ID}"
        },
        "ArnLike": {
          "aws:PrincipalARN": "arn:${PARTITION}:iam::*:role/EC2-Default-SSM-AD-Role"
        }
      }
    }
  ]
}`
 
 
**Expected behavior**
Landing Zone Accelerator to onboard the eu-west-3 region during the logging stage including the placement of the subscriptionfilter to the log, whilst also correctly handling KMS encryption.
 
 
**Please complete the following information about the solution:**
 
- [ ] Version: v1.11.1 & v1.11.2
 
- [ ] Region: eu-west-3
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? N/A
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes
- [ ] Were there any errors in the CloudWatch Logs? Yes
 
 
**Additional Context**
The eventual manual workaround I put in place was to copy the cloudformation stack and modify the Role policy applied to the Lambda function which was trying to complete the custom action to create the subscriptionfilters.  Adding Action KMS:Decrypt and modifying the resource to omit the last **:** <- Colon and replace it with either nothing or a **/** <- forward slash.
 

I believe the bug can be traced back to line 104 of cloudwatch-logs-subscription-filter.ts
https://github.com/awslabs/landing-zone-accelerator-on-aws/blame/8edb330eccb2f730916a135f25c0ca2000f01a90/source/packages/%40aws-accelerator/constructs/lib/aws-cloudwatch-logs/cloudwatch-logs-subscription-filter.ts#L104
