### ISSUE TITLE
Unable to add multiple emails from replacements config

### ISSUE THREAD

**Issue by srcndogan** [awslabs/landing-zone-accelerator-on-aws#774]
**Describe the bug**
Hello team, is it possible to use multiple email values in replacements-config.yaml and pass them into global-config.yaml by using double-curly bracelets like below.

replacements-config.yaml
```yaml
  - key: SecurityHigh
    type: StringList
    value:
      - xxxxxxxxx@amazon.com
      - xxxxxxxxx@amazon.com
 ```
global-config.yaml
```yaml
snsTopics:
  deploymentTargets:
    organizationalUnits:
      - Root
  topics:
    - emailAddresses:
        - "{{SecurityHigh}}"
      name: SecurityHigh
```

If I am defining those emails as a list in global-config.yaml there are no issues., two separate subscription being created in Logging stage, but if trying to use like above, stack fails because its taking values as single string "Endpoint": "xxxxxx@example.com,xxxxxx@example.com".  Also if passing single value in replacements-config that works with no issue as well but problem occurs when adding the second email.

**Expected behavior**
Dynamically process values as an array not single String.

**Please complete the following information about the solution:**

- [ ] Version: [v1.12.1]
- [ ] Region: [us-east-1]
- [No] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [yes] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [No ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
We are able to workaround like below but would have expected to work as above.

global-config.yaml
```yaml
  topics:
    - emailAddresses: 
        - "{{SecurityHigh1}}"
        - "{{SecurityHigh2}}"
      name: SecurityHigh
```
replacements-config.yaml
```yaml
  - key: SecurityHigh1
    type: StringList
    value:
      - xxxx@example.com
  - key: SecurityHigh2
    type: StringList
    value:
      - xxxx@example.com
```
