### ISSUE TITLE
Bootstrap stage fails when using prefixe list in VPC routes

### ISSUE THREAD

**Issue by hpfpv** [awslabs/landing-zone-accelerator-on-aws#79]
**Describe the bug**
The Bootstrap stage fails when using prefix lists in VPC route table routes in the network-config file.
Error bellow:

[2023-02-24 20:26:37] - info:       [network-vpc-stack] Adding VPC xxxxx
[2023-02-24 20:26:37] - info:       [network-vpc-stack] Adding subnet xxxxx
[2023-02-24 20:26:37] - info:       [network-vpc-stack] Adding subnet xxxxxx
[2023-02-24 20:26:37] - info:       [network-vpc-stack] Adding subnet xxxxxx
[2023-02-24 20:26:37] - info:       [network-vpc-stack] Adding subnet xxxxxx
[2023-02-24 20:26:37] - info:       [network-vpc-stack] Adding subnet xxxxxxx
[2023-02-24 20:26:37] - info:       [network-vpc-stack] Adding subnet xxxxxxx
[2023-02-24 20:26:37] - info:       [network-vpc-stack] Adding Transit Gateway Attachment for xxxxx
[2023-02-24 20:26:37] - error:  undefined
[2023-02-24 20:26:37] - error:  undefined
Subprocess exited with error 1
error Command failed with exit code 1.

**To Reproduce**
Create a prefix list like below:
```yaml
prefixLists:
  - name: prefix-list-01
    accounts:
      - Network
    regions:
      - *HOME_REGION
    addressFamily: "IPv4"
    maxEntries: 5
    entries:
      - 192.168.0.0/16
      - 172.16.0.0/16
```
      
Reference the prefix list in a route table for a vpc like below:
```yaml
- name: vpc-test 
    account: Network
    region: *HOME_REGION
    cidrs:
      - 172.22.0.0/24
    internetGateway: false
    routeTables:
      - name: route-subnetnfw-aza 
        routes:
          - name: TgwRoute
            destinationPrefixList: prefix-list-01
            type: transitGateway
            target: tgw-principal
        tags: []
```
   
**Expected behavior**
The route table should be created with the referenced prefix list.

**Please complete the following information about the solution:**

- [ ] Version: 1.3.0

- [ ] Region: ca-central-1
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? Yes
- [ ] Were there any errors in the CloudWatch Logs? Yes

**Additional context**
I added a separate route for all the CIDRs in the prefix list as a workaround. This solved the issue.
