### ISSUE TITLE
parameters are broken for StackSets in customizations-config.yaml

### ISSUE THREAD

**Issue by thetechbender** [awslabs/landing-zone-accelerator-on-aws#93]
**Describe the bug**
LZA v1.3.1 added the ability to pass parameters to CloudFormation Stacks and StackSets as part of `customizations-config.yaml`

- `feat(customizations): add capability to pass parameters to Stacks and StackSets`

This feature does not work for CloudFormation StackSets. It does appear to work for CloudFormation stacks. 

**To Reproduce**
Try to create a CloudFormation StackSet as part of `customizations-config.yaml` and add pass parameters to the StackSet in the yaml file.

Instructions to reproduce:

Create a CloudFormation template `cloudformation/test-cfn-parameter.yaml` , and add it to `aws-accelerator-config`. Contents of the CloudFormation template:

```
AWSTemplateFormatVersion: "2010-09-09"
Description: Test stack for CFN Parameters in customizations-config.yaml
Parameters:
  pMyTestParameter:
    Type: String
    Description: Test Parameter
    Default: my-default-value
Resources:
  rSsmParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /test/cfn-parameter
      Type: String
      Description: Creates SSM Parameter from CFN parameter
      Value: !Ref pMyTestParameter
```

Update `customizations-config.yaml` to deploy new template as a StackSet with custom parameters. Relevant config from `customizations-config.yaml`:

```
homeRegion: &HOME_REGION us-east-1
customizations:
  cloudFormationStackSets:
    - deploymentTargets:
        organizationalUnits:
          - Root
      description: Test CFN Parameter Stack
      name: Test-CFN-Parameter-stack
      regions:
        - us-east-1
      template: cloudformation/test-cfn-parameter.yaml
      terminationProtection: false
      parameters:
        - name: rMyTestParameter
          value: my-override-parameter
```

Validate config:
```
yarn validate-config $MY_CONFIG
yarn run v1.22.19
$ ts-node $PWD/packages/@aws-accelerator/accelerator/lib/config-validator.ts /home/ebender/aws-accelerator-config/
2023-03-13 11:21:32.099 | info | config-validator | Config source directory -  /home/ebender/aws-accelerator-config/
2023-03-13 11:21:32.113 | info | iam-config-validator | iam-config.yaml file validation started
2023-03-13 11:21:32.119 | info | network-config-validator | network-config.yaml file validation started
2023-03-13 11:21:32.131 | info | customizations-config-validator | customizations-config.yaml file validation started
2023-03-13 11:21:32.142 | info | config-validator | Config file validation successful.
(node:15861) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
Done in 1.79s.
```

Deploy changes. Please note, this example uses the guidance in `DEVELOPING.md` to test the changes. I have also tested the changes in the full `AWSAccelerator-Pipeline`, and get the same results and errors from CodeBuild in the `Customizations` stage.

```
yarn run ts-node --transpile-only cdk.ts deploy --stage customizations --require-approval any-change --config-dir $MY_CONFIG --partition aws --region us-east-1 --account $MY_ACCOUNT
yarn run v1.22.19
$ /home/ebender/landing-zone-accelerator-on-aws/source/packages/@aws-accelerator/accelerator/node_modules/.bin/ts-node --transpile-only cdk.ts deploy --stage customizations --require-approval any-change --config-dir /home/ebender/aws-accelerator-config/ --partition aws --region us-east-1 --account 111222333444
2023-03-13 11:22:28.225 | info | toolkit | Executing cdk deploy customizations for aws://111222333444/us-east-1
...
... (abbreviated output)
```

Result:
CloudFormation StackSet fails to deploy. Relevant Log snippet:
```
AWSAccelerator-CustomizationsStack-111222333444-us-east-1: creating CloudFormation changeset...
11:23:24 AM | CREATE_FAILED        | AWS::CloudFormation::StackSet | AwsAcceleratorCust...tCfnParameterStack
Properties validation failed for resource AwsAcceleratorCustomTestCfnParameterStack with message:
#: #: only 1 subschema matches out of 2
#/Parameters/0: expected type: JSONObject, found: String

        CustomizationsStack.deployCustomStackSets (/home/ebender/landing-zone-accelerator-on-aws/source/packages/@aws-accelerator/accelerator/lib/stacks/customizations-stack.ts:5 AM | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack    | AWSAccelerator-Cus...35265473-us-east-1
108:9)
        \_ new CustomizationsStack (/home/ebender/landing-zone-accelerator-on-aws/source/packages/@aws-accelerator/accelerator/lib/stacks/customizations-stack.ts:66:12)
        \_ main (/home/ebender/landing-zone-accelerator-on-aws/source/packages/@aws-accelerator/accelerator/bin/app.ts:680:39)
        \_ processTicksAndRejections (node:internal/process/task_queues:95:5)
        \_ async /home/ebender/landing-zone-accelerator-on-aws/source/packages/@aws-accelerator/accelerator/bin/app.ts:846:5


 ❌  AWSAccelerator-CustomizationsStack-111222333444-us-east-1 failed: Error: The stack named AWSAccelerator-CustomizationsStack-111222333444-us-east-1 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Properties validation failed for resource AwsAcceleratorCustomTestCfnParameterStack with message:
#: #: only 1 subschema matches out of 2
#/Parameters/0: expected type: JSONObject, found: String
    at FullCloudFormationDeployment.monitorDeployment (/home/ebender/landing-zone-accelerator-on-aws/source/node_modules/aws-cdk/lib/api/deploy-stack.ts:496:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async deployStack (/home/ebender/landing-zone-accelerator-on-aws/source/node_modules/aws-cdk/lib/cdk-toolkit.ts:241:24)
    at async /home/ebender/landing-zone-accelerator-on-aws/source/node_modules/aws-cdk/lib/deploy.ts:39:11
    at async run (/home/ebender/landing-zone-accelerator-on-aws/source/node_modules/p-queue/dist/index.js:163:29)

 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named AWSAccelerator-CustomizationsStack-111222333444-us-east-1 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Properties validation failed for resource AwsAcceleratorCustomTestCfnParameterStack with message:
#: #: only 1 subschema matches out of 2
#/Parameters/0: expected type: JSONObject, found: String
    at Object.exports.deployStacks (/home/ebender/landing-zone-accelerator-on-aws/source/node_modules/aws-cdk/lib/deploy.ts:61:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CdkToolkit.deploy (/home/ebender/landing-zone-accelerator-on-aws/source/node_modules/aws-cdk/lib/cdk-toolkit.ts:314:7)
    at async Function.execute (/home/ebender/landing-zone-accelerator-on-aws/source/packages/@aws-accelerator/accelerator/lib/toolkit.ts:289:9)
    at async /home/ebender/landing-zone-accelerator-on-aws/source/packages/@aws-accelerator/accelerator/cdk.ts:95:3
2023-03-13 11:26:16.398 | error | toolkit | Stack Deployments Failed: Error: The stack named AWSAccelerator-CustomizationsStack-111222333444-us-east-1 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Properties validation failed for resource AwsAcceleratorCustomTestCfnParameterStack with message:
#: #: only 1 subschema matches out of 2
#/Parameters/0: expected type: JSONObject, found: String
Deployment failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**
CloudFormation StackSet deployments with parameters should work the same way as CloudFormation Stacks with parameters.

For example, this example works to create a CloudFormation stack with parameters passed through `customizations-config.yaml`

Create a CloudFormation template `cloudformation/test-cfn-parameter.yaml` , and add it to `aws-accelerator-config`. Contents of the CloudFormation template:

```
AWSTemplateFormatVersion: "2010-09-09"
Description: Test stack for CFN Parameters in customizations-config.yaml
Parameters:
  pMyTestParameter:
    Type: String
    Description: Test Parameter
    Default: my-default-value
Resources:
  rSsmParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /test/cfn-parameter
      Type: String
      Description: Creates SSM Parameter from CFN parameter
      Value: !Ref pMyTestParameter
```

Update `customizations-config.yaml` to deploy new template as a CloudFormation Stack with custom parameters. Relevant config from `customizations-config.yaml`:

```
homeRegion: &HOME_REGION us-east-1
customizations:
  cloudFormationStacks:
    - deploymentTargets:
        accounts:
          - Management
      description: Test CFN Parameter Stack
      name: Test-CFN-Parameter-stack
      regions:
        - us-east-1
      runOrder: 1
      template: cloudformation/test-cfn-parameter.yaml
      terminationProtection: false
      parameters:
        - name: rMyTestParameter
          value: my-override-parameter
```

The CloudFormation Stack deploys successfully. The value of the SSM Parameter `/test/cfn-parameter` is overridden by the parameter passed through `customizations-config.yaml` - `my-override-parameter`

**Please complete the following information about the solution:**

- [ x ] Version: v1.3.2
- [ x ] Region: us-east-1
- [ x ] Was the solution modified from the version published on this repository? No
- [ x ] If the answer to the previous question was yes, are the changes available on GitHub? Not modified
- [ x ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? Yes
- [ x ] Were there any errors in the CloudWatch Logs? Logs from CodeBuild are provided above
